import { makeAll, type RawRecipe } from "./recipe-types";

const raw: RawRecipe[] = [
  {
    id: "arroz-branco-soltinho",
    t: "Arroz branco soltinho",
    d: "A base de quase todo almoço brasileiro.",
    cat: "Arroz e feijão",
    time: "25 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["2 xícaras de arroz", "4 xícaras de água quente", "2 dentes de alho", "1/2 cebola picada", "2 colheres (sopa) de óleo", "Sal"],
    st: [
      "Lave o arroz até a água sair quase limpa e escorra bem.",
      ["Refogue cebola e alho no óleo até dourar levemente.", 120, "Alho queimado amarga o arroz inteiro."],
      ["Junte o arroz e frite mexendo por 1 minuto.", 60],
      ["Adicione a água quente e o sal, ferva em fogo alto até a água chegar ao nível do arroz.", 300],
      ["Tampe, abaixe o fogo ao mínimo e cozinhe 12 minutos sem abrir.", 720],
      ["Desligue e descanse tampado por 5 minutos antes de soltar com garfo.", 300],
    ],
    tips: ["Proporção 1 de arroz para 2 de água funciona sempre.", "Mexer durante o cozimento é o que empapa o arroz."],
    subs: [["Óleo", "Azeite ou manteiga."], ["Cebola", "Só alho já resolve."]],
  },
  {
    id: "feijao-caseiro",
    t: "Feijão caseiro na pressão",
    d: "Caldo grosso e bem temperado.",
    cat: "Arroz e feijão",
    time: "1 h",
    serv: "6 porções",
    diff: "Médio",
    ing: ["500 g de feijão carioca", "1 folha de louro", "4 dentes de alho", "1 cebola", "2 colheres (sopa) de óleo", "Sal", "Bacon opcional"],
    st: [
      ["Deixe o feijão de molho por 4 horas (ou a noite toda) e descarte a água.", null, "O molho reduz o tempo de cozimento e o desconforto na digestão."],
      ["Cozinhe na pressão com água 3 dedos acima e o louro por 25 minutos após pegar pressão.", 1500],
      "Em outra panela, refogue alho, cebola e bacon no óleo.",
      ["Junte 2 conchas de feijão com caldo, amasse e refogue por 3 minutos.", 180, "Amassar parte dos grãos é o que engrossa o caldo naturalmente."],
      ["Devolve tudo à panela, acerte o sal e cozinhe destampado por 10 minutos.", 600],
    ],
    tips: ["Sal só no final: sal no início endurece a casca.", "Caldo ralo? Ferva sem tampa. Grosso demais? Água quente."],
    subs: [["Feijão carioca", "Preto, fradinho ou branco (ajuste o tempo)."], ["Panela de pressão", "Panela comum: 2 horas com água quente reposta."]],
  },
  {
    id: "feijoada-simples",
    t: "Feijoada simples",
    d: "Versão de casa, sem 20 ingredientes.",
    cat: "Arroz e feijão",
    time: "2 h",
    serv: "6 porções",
    diff: "Difícil",
    ing: ["500 g de feijão preto", "300 g de carne seca dessalgada", "200 g de costelinha salgada", "2 linguiças calabresas", "150 g de bacon", "1 cebola e 5 dentes de alho", "2 folhas de louro", "Laranja para servir"],
    st: [
      ["Dessalgue as carnes salgadas trocando a água 3 vezes, por 12 horas.", null, "Pular o dessalgue arruína o prato: fica intragável de salgado."],
      ["Cozinhe o feijão com louro na pressão por 20 minutos.", 1200],
      ["Ferva as carnes salgadas por 10 minutos e descarte a água.", 600],
      "Doure bacon, linguiça, cebola e alho em uma panela grande.",
      ["Junte todas as carnes e o feijão com o caldo; cozinhe em fogo baixo por 1 hora.", 3600],
      "Acerte o sal só no final e sirva com arroz, couve e laranja.",
    ],
    tips: ["Feijoada melhora no dia seguinte.", "Caldo cremoso: amasse uma concha de feijão e devolva à panela."],
    subs: [["Carne seca", "Músculo fresco + mais tempo de cozimento."], ["Costelinha salgada", "Costela fresca temperada."]],
  },
  {
    id: "arroz-carreteiro",
    t: "Arroz carreteiro",
    d: "Prato único gaúcho com carne e arroz.",
    cat: "Arroz e feijão",
    time: "45 min",
    serv: "4 porções",
    diff: "Médio",
    ing: ["300 g de carne seca dessalgada e desfiada", "2 xícaras de arroz", "1 cebola e 3 dentes de alho", "1 tomate", "4 xícaras de água quente", "Cheiro-verde", "Óleo"],
    st: [
      ["Frite a carne desfiada até dourar bem.", 480, "Deixar dourar de verdade concentra o sabor do prato."],
      "Junte cebola, alho e tomate e refogue.",
      ["Acrescente o arroz e frite por 1 minuto.", 60],
      ["Adicione a água quente, tampe e cozinhe em fogo baixo por 15 minutos.", 900],
      "Finalize com bastante cheiro-verde.",
    ],
    tips: ["Prove antes de salgar: a carne seca já traz sal.", "Sobra de churrasco funciona tão bem quanto carne seca."],
    subs: [["Carne seca", "Carne moída, linguiça ou frango desfiado."], ["Tomate", "1 colher de extrato."]],
  },
  {
    id: "risoto-cogumelos",
    t: "Risoto de cogumelos",
    d: "Cremoso sem creme de leite.",
    cat: "Arroz e feijão",
    time: "40 min",
    serv: "3 porções",
    diff: "Difícil",
    ing: ["1 1/2 xícara de arroz arbóreo", "300 g de cogumelos fatiados", "1 litro de caldo de legumes quente", "1/2 cebola picada fina", "1/2 xícara de vinho branco", "50 g de manteiga gelada", "50 g de parmesão"],
    st: [
      ["Doure os cogumelos em fogo alto, sem lotar a panela, e reserve.", 300, "Cogumelo amontoado solta água e cozinha em vez de dourar."],
      ["Refogue a cebola na manteiga e junte o arroz, tostando por 2 minutos.", 120],
      ["Adicione o vinho e deixe evaporar.", 120],
      ["Vá juntando o caldo quente, uma concha por vez, mexendo, por 18 minutos.", 1080, "Caldo frio interrompe o cozimento — mantenha o caldo fervendo ao lado."],
      "Fora do fogo, junte manteiga gelada, parmesão e os cogumelos: é a mantecatura.",
    ],
    tips: ["Ponto certo: o arroz deve escorrer no prato, não ficar em pé.", "Nunca lave o arroz de risoto — o amido é o creme."],
    subs: [["Vinho branco", "Caldo + 1 colher de vinagre de vinho branco."], ["Arbóreo", "Carnaroli, ou arroz comum (fica menos cremoso)."]],
  },
  {
    id: "arroz-de-forno",
    t: "Arroz de forno cremoso",
    d: "Sobra de arroz vira jantar gratinado.",
    cat: "Arroz e feijão",
    time: "35 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["3 xícaras de arroz cozido", "1 xícara de frango ou presunto picado", "1 xícara de creme de leite ou requeijão", "1 xícara de milho e ervilha", "Queijo ralado", "Sal e pimenta"],
    st: ["Misture tudo, menos o queijo, em um refratário.", "Cubra com queijo generoso.", ["Leve ao forno a 200 °C por 20 minutos até gratinar.", 1200, "Se o topo não dourar, ligue o grill nos últimos 3 minutos."]],
    tips: ["Arroz de véspera é o melhor para essa receita.", "Um pouco de leite deixa a mistura menos seca."],
    subs: [["Creme de leite", "Requeijão, iogurte grego ou molho branco."], ["Frango", "Atum, calabresa ou legumes."]],
  },
  {
    id: "macarrao-ao-alho-manteiga",
    t: "Macarrão na manteiga e parmesão",
    d: "Cinco ingredientes, quinze minutos.",
    cat: "Massas",
    time: "15 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: ["250 g de espaguete", "60 g de manteiga", "60 g de parmesão ralado", "Sal grosso", "Pimenta-do-reino"],
    st: [
      ["Cozinhe a massa em água fervente bem salgada até al dente.", 480, "Água de macarrão deve ser salgada como água do mar."],
      ["Reserve 1 xícara da água do cozimento antes de escorrer.", null, "Essa água com amido é o que liga o molho."],
      "Na frigideira, derreta a manteiga e junte a massa com um pouco da água reservada.",
      ["Fora do fogo, misture o parmesão até virar creme, mexendo por 1 minuto.", 60],
    ],
    tips: ["Parmesão no fogo alto vira bolota — desligue antes.", "Al dente = 1 minuto a menos do que diz o pacote."],
    subs: [["Parmesão", "Grana padano ou queijo curado ralado."], ["Manteiga", "Azeite (fica mais leve)."]],
  },
  {
    id: "molho-tomate-caseiro",
    t: "Molho de tomate caseiro",
    d: "Base para massas, pizzas e o que vier.",
    cat: "Massas",
    time: "45 min",
    serv: "600 ml",
    diff: "Fácil",
    ing: ["1 kg de tomates maduros (ou 800 g pelados)", "4 dentes de alho", "1/2 cebola", "Azeite", "Manjericão", "Sal e uma pitada de açúcar"],
    st: [
      ["Refogue alho e cebola no azeite em fogo baixo por 5 minutos, sem dourar.", 300],
      "Junte os tomates picados (sem pele, se possível) e o sal.",
      ["Cozinhe em fogo baixo por 30 minutos, mexendo de vez em quando.", 1800, "Molho bom é questão de tempo, não de ingrediente caro."],
      "Se estiver ácido, junte a pitada de açúcar. Finalize com manjericão.",
    ],
    tips: ["Para tirar a pele: corte um X, escalde 30 segundos e passe no gelo.", "Congele em porções: dura 3 meses."],
    subs: [["Tomate fresco", "Tomate pelado em lata (mais constante o ano todo)."], ["Manjericão", "Orégano ou salsinha."]],
  },
  {
    id: "espaguete-bolonhesa",
    t: "Espaguete à bolonhesa",
    d: "Molho de carne cozido devagar.",
    cat: "Massas",
    time: "1 h 15 min",
    serv: "4 porções",
    diff: "Médio",
    ing: ["500 g de carne moída", "1 cebola, 1 cenoura e 1 talo de salsão picados fino", "3 dentes de alho", "500 ml de molho de tomate", "1/2 xícara de leite", "Azeite, sal e pimenta", "400 g de espaguete"],
    st: [
      ["Refogue cebola, cenoura e salsão no azeite por 8 minutos.", 480, "Esse trio (soffritto) é a base de sabor do molho italiano."],
      ["Junte a carne e doure bem, sem mexer demais, até secar o líquido.", 600],
      ["Adicione o leite e deixe evaporar.", 300, "O leite amacia a carne e tira a acidez do tomate."],
      ["Acrescente o molho e cozinhe em fogo baixo por 40 minutos.", 2400],
      "Cozinhe a massa al dente e misture ao molho na panela.",
    ],
    tips: ["Nunca sirva o molho por cima: massa e molho devem se encontrar na panela.", "Molho seco? Junte água do cozimento da massa."],
    subs: [["Salsão", "Só cebola e cenoura já funciona."], ["Carne moída", "Carne de porco moída, lentilha ou proteína de soja."]],
  },
  {
    id: "macarrao-carbonara",
    t: "Carbonara de verdade",
    d: "Ovo, queijo e bacon — sem creme de leite.",
    cat: "Massas",
    time: "20 min",
    serv: "2 porções",
    diff: "Difícil",
    ing: ["250 g de espaguete", "120 g de guanciale ou bacon em cubos", "2 gemas + 1 ovo inteiro", "60 g de pecorino ou parmesão ralado", "Pimenta-do-reino moída na hora", "Sal grosso"],
    st: [
      ["Frite o bacon em fogo médio até ficar crocante e reserve a gordura.", 420],
      "Bata gemas, ovo, queijo e muita pimenta em uma tigela.",
      ["Cozinhe a massa al dente e reserve 1 xícara da água.", 480],
      ["Fora do fogo, misture massa quente, gordura do bacon e o creme de ovos, mexendo rápido.", null, "Fora do fogo é regra: no fogo o ovo vira ovo mexido."],
      "Ajuste a textura com a água quente da massa até virar um creme brilhante.",
    ],
    tips: ["Panela morna, nunca no fogo, na hora de juntar o ovo.", "Sal com cuidado: o bacon e o queijo já salgam."],
    subs: [["Guanciale", "Bacon ou pancetta."], ["Pecorino", "Parmesão."]],
  },
  {
    id: "macarrao-quatro-queijos",
    t: "Macarrão quatro queijos",
    d: "Molho branco cremoso com queijos derretidos.",
    cat: "Massas",
    time: "25 min",
    serv: "3 porções",
    diff: "Médio",
    ing: ["350 g de penne", "400 ml de leite", "1 colher (sopa) de manteiga e 1 de farinha", "50 g de cada: muçarela, provolone, parmesão e gorgonzola", "Noz-moscada", "Sal"],
    st: [
      ["Derreta a manteiga, junte a farinha e cozinhe 2 minutos mexendo.", 120, "Cozinhar a farinha tira o gosto de massa crua."],
      ["Adicione o leite aos poucos, mexendo com fouet até engrossar.", 300],
      "Fora do fogo, junte os queijos e a noz-moscada até derreter.",
      "Misture com a massa al dente e sirva imediatamente.",
    ],
    tips: ["Molho empelotou? Bata com mixer ou passe na peneira.", "Gorgonzola é forte: comece com menos."],
    subs: [["Gorgonzola", "Mais provolone, se não gostar de queijo azul."], ["Leite", "Metade leite, metade caldo de legumes."]],
  },
  {
    id: "nhoque-batata",
    t: "Nhoque de batata",
    d: "Leve, se você usar pouca farinha.",
    cat: "Massas",
    time: "1 h",
    serv: "4 porções",
    diff: "Difícil",
    ing: ["1 kg de batatas", "1 ovo", "250 a 350 g de farinha de trigo", "Sal e noz-moscada", "Molho de tomate ou manteiga com sálvia"],
    st: [
      ["Cozinhe as batatas com casca em água ou asse-as no forno.", 2400, "Batata assada absorve menos água e pede menos farinha — nhoque mais leve."],
      "Descasque ainda quentes e passe pelo espremedor.",
      "Espalhe para esfriar, junte ovo, sal e a farinha aos poucos, até dar liga.",
      "Faça rolinhos, corte em pedaços e polvilhe farinha.",
      ["Cozinhe em água fervente salgada: estão prontos quando sobem, 2 minutos.", 120],
    ],
    tips: ["Quanto menos farinha, mais macio — pare assim que a massa parar de grudar.", "Teste um nhoque antes de cozinhar tudo."],
    subs: [["Espremedor", "Garfo, com paciência (evite liquidificador: vira cola)."], ["Ovo", "Pode omitir; a massa fica mais delicada."]],
  },
  {
    id: "lasanha-bolonhesa-branca",
    t: "Lasanha de frango com molho branco",
    d: "Camadas cremosas para o domingo.",
    cat: "Massas",
    time: "1 h 20 min",
    serv: "6 porções",
    diff: "Médio",
    ing: ["500 g de massa de lasanha", "600 g de frango cozido desfiado", "1 litro de molho branco", "300 g de muçarela", "200 g de presunto", "Parmesão ralado"],
    st: [
      "Misture metade do molho branco com o frango.",
      "Monte camadas: molho, massa, frango, presunto, queijo — repita 3 vezes.",
      ["Termine com molho e parmesão e cubra com papel-alumínio.", null, "O papel evita que a superfície queime antes de a massa cozinhar."],
      ["Asse a 180 °C por 40 minutos.", 2400],
      ["Retire o papel e gratine por 10 minutos.", 600],
    ],
    tips: ["Massa que não precisa pré-cozimento exige molho abundante.", "Descanse 10 minutos antes de cortar, senão desmonta."],
    subs: [["Molho branco", "Requeijão diluído em leite."], ["Frango", "Carne moída, atum ou legumes."]],
  },
  {
    id: "macarrao-molho-branco-atum",
    t: "Macarrão com atum",
    d: "Despensa vazia? Esse salva o jantar.",
    cat: "Massas",
    time: "20 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: ["250 g de massa curta", "1 lata de atum escorrido", "2 dentes de alho", "1 xícara de molho de tomate", "Azeitonas e alcaparras", "Azeite, sal e salsinha"],
    st: [
      ["Doure o alho no azeite sem queimar.", 90],
      ["Junte o atum e refogue por 2 minutos.", 120, "Refogar o atum tira o gosto de lata."],
      ["Adicione o molho e as azeitonas, cozinhe 5 minutos.", 300],
      "Misture com a massa al dente e finalize com salsinha.",
    ],
    tips: ["Atum em óleo dá mais sabor que em água.", "Pimenta calabresa combina demais aqui."],
    subs: [["Atum", "Sardinha em lata ou frango desfiado."], ["Alcaparras", "Azeitona picada ou nada."]],
  },
  {
    id: "yakisoba",
    t: "Yakisoba de legumes e frango",
    d: "Wok rápido em fogo alto.",
    cat: "Massas",
    time: "30 min",
    serv: "3 porções",
    diff: "Médio",
    ing: ["300 g de macarrão para yakisoba", "300 g de frango em tiras", "Brócolis, cenoura, repolho e pimentão", "4 colheres (sopa) de shoyu", "1 colher (sopa) de amido dissolvido em água", "Gengibre e alho", "Óleo"],
    st: [
      "Cozinhe o macarrão, escorra e regue com um fio de óleo.",
      ["Em fogo bem alto, doure o frango e reserve.", 300, "Fogo alto e panela grande: legume em panela cheia cozinha no vapor e murcha."],
      ["Salteie os legumes por 4 minutos, começando pelos mais duros.", 240],
      ["Volte o frango, junte shoyu e o amido; cozinhe até engrossar.", 120],
      "Misture o macarrão e sirva imediatamente.",
    ],
    tips: ["Corte tudo antes de acender o fogo: o preparo é de minutos.", "Legume deve ficar crocante, não mole."],
    subs: [["Shoyu", "Molho de soja com um pouco de água e açúcar."], ["Macarrão de yakisoba", "Espaguete cozido al dente."]],
  },
  {
    id: "macarrao-alho-oleo-brocolis",
    t: "Macarrão com brócolis e alho",
    d: "Verdura e massa no mesmo cozimento.",
    cat: "Massas",
    time: "20 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: ["250 g de massa", "1 brócolis em floretes", "4 dentes de alho fatiados", "Azeite generoso", "Pimenta calabresa", "Parmesão"],
    st: [
      ["Cozinhe a massa e jogue o brócolis na mesma panela nos últimos 3 minutos.", 180, "Um cozimento só: menos louça e o brócolis fica no ponto."],
      ["À parte, doure o alho em azeite em fogo baixo até ficar dourado claro.", 180],
      "Escorra tudo, misture com o alho, calabresa e parmesão.",
    ],
    tips: ["Alho dourado escuro amarga: tire do fogo no dourado claro.", "Um pouco de água da massa liga tudo."],
    subs: [["Brócolis", "Couve-flor, vagem ou espinafre."], ["Parmesão", "Farofa de pão tostado com azeite."]],
  },
  {
    id: "polenta-cremosa",
    t: "Polenta cremosa",
    d: "Conforto puro, com queijo e manteiga.",
    cat: "Legumes",
    time: "35 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["1 xícara de fubá", "4 xícaras de água ou caldo", "50 g de manteiga", "50 g de parmesão", "Sal"],
    st: [
      ["Ferva a água com sal e despeje o fubá em chuva, mexendo com fouet.", null, "Fubá jogado de uma vez empelota — em chuva, sempre mexendo."],
      ["Cozinhe em fogo baixo mexendo por 25 minutos.", 1500],
      "Fora do fogo, junte manteiga e queijo.",
    ],
    tips: ["Polenta borbulha como lava: use panela alta e fogo baixo.", "Muito grossa? Água quente. Muito rala? Mais tempo de fogo."],
    subs: [["Fubá comum", "Polenta instantânea (5 minutos)."], ["Parmesão", "Queijo minas ou requeijão."]],
  },
  {
    id: "pure-batata",
    t: "Purê de batata",
    d: "Sedoso, sem grumos e sem virar cola.",
    cat: "Legumes",
    time: "30 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["1 kg de batatas", "100 ml de leite morno", "60 g de manteiga", "Sal e noz-moscada"],
    st: [
      ["Cozinhe as batatas em pedaços grandes até um garfo entrar fácil.", 1200],
      ["Escorra e deixe secar no fogo baixo por 1 minuto.", 60, "Batata seca absorve melhor a manteiga."],
      "Amasse com espremedor, nunca no liquidificador.",
      "Junte manteiga e leite morno aos poucos, mexendo com colher.",
    ],
    tips: ["Liquidificador ou mixer transformam o amido em cola.", "Leite frio esfria e endurece o purê."],
    subs: [["Leite", "Creme de leite ou caldo do cozimento."], ["Batata", "Mandioquinha, mandioca ou couve-flor."]],
  },
  {
    id: "batata-rustica-forno",
    t: "Batata rústica no forno",
    d: "Casca crocante, miolo macio.",
    cat: "Legumes",
    time: "45 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["1 kg de batatas em gomos", "4 colheres (sopa) de azeite", "Alecrim, páprica e alho em pó", "Sal grosso"],
    st: [
      ["Ferva as batatas por 8 minutos e escorra.", 480, "A pré-fervura é o truque para o interior ficar macio e a casca crocante."],
      "Sacuda a panela para 'arranhar' a superfície das batatas.",
      "Misture com azeite e temperos e espalhe em assadeira sem sobrepor.",
      ["Asse a 220 °C por 30 minutos, virando na metade.", 1800],
    ],
    tips: ["Batatas amontoadas cozinham no vapor e não douram.", "Assadeira pré-aquecida ajuda a dourar o fundo."],
    subs: [["Alecrim", "Orégano, tomilho ou só alho."], ["Forno", "Air fryer a 200 °C por 20 minutos."]],
  },
  {
    id: "legumes-assados",
    t: "Legumes assados",
    d: "Uma assadeira, qualquer legume, sempre dá certo.",
    cat: "Legumes",
    time: "40 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["Abobrinha, cenoura, cebola, pimentão e batata-doce", "Azeite", "Sal, pimenta e ervas secas", "Alho em dentes inteiros"],
    st: [
      ["Corte tudo em tamanhos parecidos.", null, "Pedaços iguais assam por igual — essa é a regra número um."],
      "Tempere com azeite e sal e espalhe em camada única.",
      ["Asse a 200 °C por 30 minutos, mexendo na metade.", 1800],
    ],
    tips: ["Legumes mais duros entram antes; os macios, 10 minutos depois.", "Papel-manteiga evita grudar sem precisar de mais óleo."],
    subs: [["Batata-doce", "Abóbora, mandioquinha ou nabo."], ["Ervas secas", "Alecrim fresco ou páprica defumada."]],
  },
  {
    id: "farofa-simples",
    t: "Farofa de manteiga",
    d: "Acompanhamento em 10 minutos.",
    cat: "Legumes",
    time: "12 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["2 xícaras de farinha de mandioca", "3 colheres (sopa) de manteiga", "1/2 cebola picada", "Cheiro-verde", "Sal"],
    st: [
      ["Refogue a cebola na manteiga até ficar transparente.", 240],
      ["Junte a farinha aos poucos, mexendo sempre, até dourar levemente.", 300, "Farofa queima em segundos: fogo baixo e olho na panela."],
      "Finalize com cheiro-verde e sal.",
    ],
    tips: ["Farinha aos poucos evita farofa seca e sem gordura no meio.", "Bacon, ovo ou banana transformam a receita."],
    subs: [["Manteiga", "Azeite ou gordura do assado."], ["Farinha de mandioca", "Farinha de milho (fica mais grossa)."]],
  },
  {
    id: "couve-refogada",
    t: "Couve refogada",
    d: "Verde, crocante e pronta em 5 minutos.",
    cat: "Legumes",
    time: "10 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["1 maço de couve fatiada fina", "3 dentes de alho", "2 colheres (sopa) de óleo ou bacon", "Sal"],
    st: [
      "Lave e seque bem a couve fatiada.",
      ["Doure o alho no óleo bem quente.", 60],
      ["Junte a couve e refogue em fogo alto por 2 minutos, só até murchar.", 120, "Mais que isso e ela perde a cor e o crocante."],
    ],
    tips: ["Couve molhada cozinha no vapor e fica escura.", "Sal só no final, para não desidratar antes da hora."],
    subs: [["Couve", "Espinafre, acelga ou repolho fatiado."], ["Óleo", "Bacon frito com a própria gordura."]],
  },
  {
    id: "abobrinha-refogada",
    t: "Abobrinha refogada com alho",
    d: "Acompanhamento leve para qualquer prato.",
    cat: "Legumes",
    time: "15 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: ["2 abobrinhas em meias-luas", "3 dentes de alho", "Azeite", "Sal, pimenta e orégano"],
    st: [
      ["Aqueça bem a frigideira com azeite e doure o alho.", 60],
      ["Junte a abobrinha em fogo alto e refogue 5 minutos sem mexer muito.", 300, "Mexer demais solta água e a abobrinha desmancha."],
      "Tempere no final.",
    ],
    tips: ["Sal antes libera água: salgue só no fim.", "Fatias grossas resistem melhor ao calor."],
    subs: [["Abobrinha", "Berinjela, chuchu ou vagem."], ["Orégano", "Tomilho ou hortelã picada."]],
  },
  {
    id: "berinjela-assada",
    t: "Berinjela assada com alho e azeite",
    d: "Macia por dentro, dourada por fora.",
    cat: "Legumes",
    time: "40 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: ["2 berinjelas em rodelas", "Azeite", "3 dentes de alho picados", "Sal e pimenta", "Salsinha"],
    st: [
      ["Salgue as rodelas e deixe descansar 15 minutos; seque com papel.", 900, "Essa etapa tira o amargor e a água em excesso."],
      "Pincele azeite dos dois lados e espalhe na assadeira.",
      ["Asse a 200 °C por 20 minutos, virando na metade.", 1200],
      "Finalize com alho cru picado e salsinha.",
    ],
    tips: ["Berinjela bebe azeite: pincele em vez de despejar.", "Bem dourada é bem mais saborosa que pálida."],
    subs: [["Berinjela", "Abobrinha ou abóbora cabotiá."], ["Forno", "Grelha ou air fryer."]],
  },
  {
    id: "escondidinho-carne-seca",
    t: "Escondidinho de carne seca",
    d: "Purê de mandioca gratinado com recheio de carne.",
    cat: "Carnes",
    time: "1 h 15 min",
    serv: "5 porções",
    diff: "Médio",
    ing: ["1 kg de mandioca", "500 g de carne seca dessalgada e desfiada", "1 cebola e 3 dentes de alho", "200 ml de leite", "2 colheres (sopa) de manteiga", "200 g de queijo ralado"],
    st: [
      ["Cozinhe a mandioca até desmanchar e amasse com leite e manteiga.", 2400, "Tire os fiapos do meio da mandioca antes de amassar."],
      ["Refogue a carne com cebola e alho até dourar.", 600],
      "Monte: metade do purê, a carne, o resto do purê e o queijo.",
      ["Gratine a 200 °C por 20 minutos.", 1200],
    ],
    tips: ["Purê muito ralo escorre — prefira firme.", "Prove o sal só depois de dessalgar bem a carne."],
    subs: [["Mandioca", "Batata, mandioquinha ou abóbora."], ["Carne seca", "Frango desfiado ou carne moída."]],
  },
  {
    id: "torta-de-legumes",
    t: "Torta salgada de liquidificador",
    d: "Massa batida em 3 minutos, recheio livre.",
    cat: "Legumes",
    time: "50 min",
    serv: "6 porções",
    diff: "Fácil",
    ing: ["2 xícaras de farinha", "1 xícara de leite", "1/2 xícara de óleo", "3 ovos", "1 colher (sopa) de fermento", "Recheio: frango, legumes ou palmito", "Sal e queijo ralado"],
    st: [
      "Bata no liquidificador leite, óleo, ovos e sal; junte a farinha e por último o fermento.",
      ["Despeje metade da massa em forma untada, coloque o recheio e cubra com o resto.", null, "Recheio deve estar frio: quente, ele afunda a massa."],
      ["Asse a 180 °C por 35 a 40 minutos, até dourar.", 2100],
    ],
    tips: ["Palito no meio deve sair limpo (fora do recheio).", "Queijo ralado por cima cria uma crosta ótima."],
    subs: [["Leite", "Leite vegetal ou caldo de legumes."], ["Frango", "Atum, palmito, milho ou legumes refogados."]],
  },
  {
    id: "quibe-assado",
    t: "Quibe assado",
    d: "Trigo, carne e hortelã no forno.",
    cat: "Carnes",
    time: "1 h",
    serv: "6 porções",
    diff: "Médio",
    ing: ["2 xícaras de trigo para quibe", "500 g de carne moída (patinho)", "1 cebola ralada", "Hortelã picada", "Sal, pimenta e azeite"],
    st: [
      ["Hidrate o trigo em água fria por 30 minutos e esprema muito bem.", 1800, "Trigo mal escorrido deixa o quibe mole e sem liga."],
      "Misture com a carne, cebola, hortelã e temperos até ficar homogêneo.",
      "Espalhe em assadeira, marque losangos e regue com azeite.",
      ["Asse a 200 °C por 30 minutos.", 1800],
    ],
    tips: ["Carne magra funciona melhor: gordura em excesso solta na assadeira.", "Recheio de queijo no meio deixa o quibe mais suculento."],
    subs: [["Trigo para quibe", "Cuscuz marroquino hidratado."], ["Hortelã", "Salsinha (sabor diferente, mas funciona)."]],
  },
  {
    id: "arroz-integral",
    t: "Arroz integral soltinho",
    d: "Mais tempo de cozimento, mesma técnica.",
    cat: "Arroz e feijão",
    time: "45 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["2 xícaras de arroz integral", "5 xícaras de água quente", "2 dentes de alho", "1 colher (sopa) de azeite", "Sal"],
    st: [
      ["Deixe o arroz de molho por 30 minutos e escorra.", 1800, "O molho reduz quase 10 minutos de cozimento."],
      ["Refogue o alho no azeite e junte o arroz por 1 minuto.", 60],
      ["Adicione a água quente e o sal, tampe e cozinhe em fogo baixo por 35 minutos.", 2100],
      ["Descanse tampado por 10 minutos e solte com garfo.", 600],
    ],
    tips: ["Integral pede mais água: 1 para 2,5.", "Se secar antes de amolecer, junte água quente aos poucos."],
    subs: [["Azeite", "Óleo comum ou manteiga."], ["Arroz integral", "Arroz sete grãos (mesmo tempo)."]],
  },
  {
    id: "macarrao-frigideira-tomate-cereja",
    t: "Massa com tomate-cereja e manjericão",
    d: "Molho fresco feito enquanto a massa cozinha.",
    cat: "Massas",
    time: "20 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: ["250 g de massa", "300 g de tomate-cereja", "3 dentes de alho", "Azeite", "Manjericão fresco", "Sal, pimenta e parmesão"],
    st: [
      ["Doure o alho no azeite e junte os tomates inteiros.", 120],
      ["Cozinhe em fogo médio até os tomates estourarem, 8 minutos, amassando alguns.", 480, "Os tomates estourados viram o molho — não precisa de molho pronto."],
      "Junte a massa al dente com um pouco da água do cozimento.",
      "Finalize com manjericão e parmesão fora do fogo.",
    ],
    tips: ["Água da massa liga o azeite ao tomate e cria molho cremoso.", "Manjericão só no final: no fogo ele escurece."],
    subs: [["Tomate-cereja", "Tomate comum em cubos."], ["Parmesão", "Queijo coalho ralado ou nada."]],
  },
];

export const daily2 = makeAll(raw);
