import { makeAll, type RawRecipe } from "./recipe-types";

const raw: RawRecipe[] = [
  {
    id: "frango-assado-inteiro",
    t: "Frango assado inteiro",
    d: "Pele dourada e carne suculenta.",
    cat: "Aves",
    time: "1 h 40 min",
    serv: "4 porções",
    diff: "Médio",
    ing: ["1 frango inteiro (1,5 kg)", "Suco de 1 limão", "4 dentes de alho amassados", "Azeite", "Sal, pimenta e páprica", "1 cebola e batatas"],
    st: [
      ["Tempere o frango por dentro e por fora e deixe na geladeira por 2 horas.", null, "Tempo de tempero vale mais que quantidade de tempero."],
      "Coloque em assadeira sobre cebola e batatas, com o peito para cima.",
      ["Asse coberto com alumínio a 200 °C por 50 minutos.", 3000],
      ["Retire o papel e asse mais 30 minutos para dourar.", 1800],
      ["Descanse 10 minutos antes de cortar.", 600, "Cortar na hora faz todo o suco escorrer para a tábua."],
    ],
    tips: ["Ponto certo: o suco que sai da coxa deve ser transparente.", "Manteiga por baixo da pele = pele extra crocante."],
    subs: [["Frango inteiro", "Coxas e sobrecoxas (40 minutos)."], ["Páprica", "Colorau ou curry."]],
  },
  {
    id: "coxa-sobrecoxa-forno",
    t: "Coxa e sobrecoxa no forno",
    d: "Barato, fácil e quase impossível de errar.",
    cat: "Aves",
    time: "55 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["8 coxas/sobrecoxas", "Suco de 1 limão", "Alho, sal, pimenta e páprica", "Azeite", "1 cebola em rodelas"],
    st: [
      ["Tempere e deixe descansar pelo menos 30 minutos.", 1800],
      "Arrume na assadeira com a pele para cima, sobre as cebolas.",
      ["Asse a 200 °C por 45 minutos, sem cobrir.", 2700, "Peças com pele não precisam de papel-alumínio para ficarem suculentas."],
    ],
    tips: ["Não amontoe: espaço entre as peças é o que doura.", "Um pouco de água no fundo evita fumaça e faz molho."],
    subs: [["Coxa e sobrecoxa", "Asas ou peito (reduza 15 minutos)."], ["Limão", "Vinagre ou vinho branco."]],
  },
  {
    id: "strogonoff-frango",
    t: "Strogonoff de frango",
    d: "O jantar rápido preferido do Brasil.",
    cat: "Aves",
    time: "30 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["600 g de peito de frango em cubos", "1 cebola e 2 dentes de alho", "2 colheres (sopa) de ketchup e 1 de mostarda", "1 caixa de creme de leite", "200 g de champignon", "Manteiga, sal e pimenta"],
    st: [
      ["Doure o frango em fogo alto, em duas levas, e reserve.", 480, "Panela lotada cozinha em vez de dourar — faça em levas."],
      ["Refogue cebola e alho na manteiga.", 180],
      "Volte o frango, junte ketchup, mostarda e champignon.",
      ["Desligue o fogo e só então misture o creme de leite.", null, "Creme de leite fervendo talha."],
    ],
    tips: ["Um pouco de conhaque flambado dá sabor de restaurante.", "Molho ralo? Ferva antes de colocar o creme."],
    subs: [["Creme de leite", "Iogurte natural integral (fora do fogo)."], ["Champignon", "Cogumelo fresco ou palmito."]],
  },
  {
    id: "frango-xadrez",
    t: "Frango xadrez",
    d: "Agridoce com pimentão e amendoim.",
    cat: "Aves",
    time: "30 min",
    serv: "3 porções",
    diff: "Médio",
    ing: ["500 g de frango em cubos", "1 pimentão vermelho e 1 verde", "1 cebola em cubos", "3 colheres (sopa) de shoyu", "1 colher (sopa) de amido + água", "Amendoim torrado", "Gengibre e alho"],
    st: [
      ["Marine o frango no shoyu com gengibre por 15 minutos.", 900],
      ["Doure o frango em fogo alto e reserve.", 300],
      ["Salteie cebola e pimentões por 3 minutos — devem ficar crocantes.", 180, "Pimentão mole perde a graça do prato."],
      ["Volte o frango, junte o amido dissolvido e cozinhe até engrossar.", 120],
      "Finalize com amendoim.",
    ],
    tips: ["Corte tudo do mesmo tamanho antes de começar.", "Fogo alto do início ao fim."],
    subs: [["Amendoim", "Castanha de caju."], ["Shoyu", "Molho de soja com mel."]],
  },
  {
    id: "frango-parmegiana",
    t: "Frango à parmegiana",
    d: "Empanado, molho e queijo gratinado.",
    cat: "Aves",
    time: "50 min",
    serv: "4 porções",
    diff: "Médio",
    ing: ["4 filés de peito de frango", "2 ovos batidos", "Farinha de trigo e farinha de rosca", "500 ml de molho de tomate", "300 g de muçarela", "Óleo para fritar", "Sal e pimenta"],
    st: [
      ["Bata os filés até ficarem finos e tempere.", null, "Filé fino cozinha por igual e fica macio."],
      "Passe na farinha, no ovo e na farinha de rosca, apertando bem.",
      ["Frite em óleo quente por 3 minutos de cada lado.", 360],
      "Coloque em refratário, cubra com molho e queijo.",
      ["Gratine a 200 °C por 15 minutos.", 900],
    ],
    tips: ["Empanado escorregando? Deixe descansar 10 minutos na geladeira antes de fritar.", "Molho só por cima do empanado, nunca embaixo, para não amolecer."],
    subs: [["Frango", "Filé de carne, berinjela ou abobrinha."], ["Fritura", "Forno a 220 °C por 25 minutos com azeite."]],
  },
  {
    id: "frango-ao-curry",
    t: "Frango ao curry com leite de coco",
    d: "Molho aromático em 30 minutos.",
    cat: "Aves",
    time: "35 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["600 g de frango em cubos", "1 cebola e 2 dentes de alho", "1 colher (sopa) de curry em pó", "400 ml de leite de coco", "1 tomate picado", "Gengibre, sal e coentro"],
    st: [
      ["Refogue cebola, alho e gengibre.", 180],
      ["Junte o curry e frite por 30 segundos para liberar o aroma.", 30, "Tostar a especiaria na gordura multiplica o sabor."],
      ["Adicione o frango e doure.", 300],
      ["Junte tomate e leite de coco e cozinhe em fogo baixo por 15 minutos.", 900],
    ],
    tips: ["Não deixe ferver forte: o leite de coco separa.", "Ficou forte? Uma colher de açúcar ou mais coco equilibra."],
    subs: [["Leite de coco", "Creme de leite + 1 colher de coco ralado."], ["Curry", "Cúrcuma + cominho + páprica."]],
  },
  {
    id: "frango-desfiado-pressao",
    t: "Frango desfiado na pressão",
    d: "Base para sanduíches, tortas e recheios.",
    cat: "Aves",
    time: "35 min",
    serv: "6 porções",
    diff: "Fácil",
    ing: ["1 kg de peito de frango", "1 cebola e 4 dentes de alho", "1 folha de louro", "Sal e pimenta", "Água até cobrir"],
    st: [
      "Coloque tudo na panela de pressão com água até quase cobrir.",
      ["Cozinhe por 20 minutos após pegar pressão.", 1200],
      ["Desfie ainda morno, com dois garfos ou na batedeira em velocidade baixa.", null, "Batedeira com pá desfia 1 kg em 30 segundos."],
      "Guarde com um pouco do caldo para não ressecar.",
    ],
    tips: ["Reserve o caldo: vira base de arroz, sopa e molho.", "Congele em porções de 300 g."],
    subs: [["Panela de pressão", "Panela comum: 40 minutos."], ["Peito", "Coxa e sobrecoxa (mais suculento)."]],
  },
  {
    id: "carne-panela",
    t: "Carne de panela desmanchando",
    d: "Cozimento lento até o garfo cortar sozinho.",
    cat: "Carnes",
    time: "2 h 30 min",
    serv: "5 porções",
    diff: "Médio",
    ing: ["1,2 kg de acém ou músculo em pedaços grandes", "2 cebolas e 5 dentes de alho", "2 cenouras", "2 colheres (sopa) de extrato de tomate", "1 folha de louro", "Óleo, sal e pimenta", "Água quente"],
    st: [
      ["Sele a carne em fogo alto, em levas, até dourar bem de todos os lados.", 600, "A crosta escura é a base do sabor de todo cozido."],
      "Refogue cebola, alho e extrato na mesma panela.",
      ["Volte a carne, cubra com água quente e cozinhe tampado em fogo baixo por 2 horas.", 3600],
      ["Junte as cenouras na última meia hora.", 1800],
      "Se o molho estiver ralo, ferva sem tampa até encorpar.",
    ],
    tips: ["Corte com colágeno é obrigatório: filé mignon fica seco.", "Nunca use água fria no meio do cozimento — endurece a carne."],
    subs: [["Acém", "Músculo, paleta ou patinho (mais seco)."], ["Panela comum", "Pressão: 40 minutos."]],
  },
  {
    id: "carne-moida-refogada",
    t: "Carne moída refogada soltinha",
    d: "Base para tudo: recheio, macarrão, escondidinho.",
    cat: "Carnes",
    time: "25 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["500 g de carne moída", "1 cebola e 3 dentes de alho", "1 tomate picado", "Óleo, sal, pimenta e cominho", "Cheiro-verde"],
    st: [
      ["Aqueça bem a panela e junte a carne sem mexer, por 3 minutos.", 180, "Mexer logo faz a carne soltar água e cozinhar em vez de dourar."],
      ["Deixe secar toda a água que soltar e só então doure.", 480],
      "Junte cebola, alho e tomate e refogue mais 5 minutos.",
      "Tempere e finalize com cheiro-verde.",
    ],
    tips: ["Panela grande espalha a carne e ajuda a dourar.", "Carne moída na hora tem textura muito melhor."],
    subs: [["Carne bovina", "Frango moído, carne de porco ou proteína de soja hidratada."], ["Tomate", "1 colher de extrato + 1/2 xícara de água."]],
  },
  {
    id: "almondegas-molho",
    t: "Almôndegas ao molho",
    d: "Macias porque levam pão molhado no leite.",
    cat: "Carnes",
    time: "50 min",
    serv: "4 porções",
    diff: "Médio",
    ing: ["600 g de carne moída", "1 fatia de pão de forma sem casca", "1/4 xícara de leite", "1 ovo", "1/2 cebola ralada e alho", "Salsinha, sal e pimenta", "600 ml de molho de tomate"],
    st: [
      ["Molhe o pão no leite e amasse até virar pasta.", null, "Esse truque (panade) mantém a almôndega macia mesmo cozida no molho."],
      "Misture com a carne, ovo, cebola e temperos sem sovar demais.",
      "Modele bolinhas úmidas com as mãos molhadas.",
      ["Doure as almôndegas na frigideira por 5 minutos.", 300],
      ["Transfira para o molho e cozinhe em fogo baixo por 25 minutos.", 1500],
    ],
    tips: ["Amassar demais deixa a almôndega dura.", "Cozinhar no molho é o que dá sabor aos dois."],
    subs: [["Pão de forma", "Farinha de rosca + leite."], ["Carne bovina", "Metade bovina e metade suína fica mais suculenta."]],
  },
  {
    id: "picanha-frigideira",
    t: "Picanha na frigideira",
    d: "Sem churrasqueira, com crosta de sal grosso.",
    cat: "Carnes",
    time: "25 min",
    serv: "3 porções",
    diff: "Médio",
    ing: ["1 picanha (1,2 kg) em bifes grossos", "Sal grosso moído", "Pimenta-do-reino", "Alho e manteiga (opcional)"],
    st: [
      ["Tire a carne da geladeira 30 minutos antes.", 1800, "Carne gelada por dentro doura por fora e fica crua no centro."],
      "Seque muito bem com papel-toalha e salgue.",
      ["Derreta a gordura da picanha primeiro, na frigideira quente, por 4 minutos.", 240],
      ["Sele cada lado por 3 a 4 minutos para o ponto ao ponto.", 210],
      ["Descanse 5 minutos antes de fatiar, contra as fibras.", 300],
    ],
    tips: ["Carne úmida não doura — secar é obrigatório.", "Toque: macia = malpassada, firme = bem passada."],
    subs: [["Picanha", "Contrafilé, alcatra ou fraldinha."], ["Manteiga", "Só a própria gordura da peça."]],
  },
  {
    id: "costela-forno",
    t: "Costela no forno bem lenta",
    d: "Seis horas de forno baixo e nada mais.",
    cat: "Carnes",
    time: "6 h",
    serv: "6 porções",
    diff: "Difícil",
    ing: ["2 kg de costela bovina", "Sal grosso", "Alho e pimenta", "Papel-alumínio"],
    st: [
      "Tempere a costela generosamente com sal e alho.",
      ["Embrulhe muito bem em duas camadas de papel-alumínio.", null, "Vedação total é o que cozinha a carne no próprio vapor."],
      ["Asse a 150 °C por 5 horas.", 3600],
      ["Abra o papel e asse mais 40 minutos para dourar.", 2400],
    ],
    tips: ["Não abra o pacote no meio: perde vapor e resseca.", "Está pronta quando o osso sai limpo com um puxão leve."],
    subs: [["Costela bovina", "Costelinha suína (3 horas)."], ["Forno", "Panela de pressão por 50 minutos + forno para dourar."]],
  },
  {
    id: "bife-role",
    t: "Bife à rolê",
    d: "Recheado, cozido no molho até amaciar.",
    cat: "Carnes",
    time: "1 h 20 min",
    serv: "4 porções",
    diff: "Médio",
    ing: ["8 bifes finos de coxão mole", "Cenoura e pimentão em tiras", "Bacon em tiras", "Molho de tomate", "Cebola e alho", "Palitos ou barbante", "Sal e pimenta"],
    st: [
      "Bata os bifes, tempere e coloque o recheio em uma ponta.",
      "Enrole apertado e prenda com palito.",
      ["Doure os rolinhos de todos os lados.", 480, "Selar antes evita que se abram durante o cozimento."],
      ["Junte molho e água até quase cobrir; cozinhe tampado em fogo baixo por 50 minutos.", 3000],
    ],
    tips: ["Bife fino e bem batido enrola sem rasgar.", "Retire os palitos antes de servir."],
    subs: [["Coxão mole", "Patinho ou alcatra fatiados finos."], ["Bacon", "Linguiça calabresa ou queijo."]],
  },
  {
    id: "linguica-acebolada",
    t: "Linguiça acebolada",
    d: "Boteco em casa em 20 minutos.",
    cat: "Carnes",
    time: "20 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: ["500 g de linguiça calabresa em rodelas", "2 cebolas em rodelas", "1/2 xícara de água", "Pimenta e cheiro-verde"],
    st: [
      ["Doure a linguiça em fogo médio na própria gordura.", 480],
      ["Junte a água, raspe o fundo e deixe evaporar.", 180, "Raspar o fundo com água (deglaçar) recupera todo o sabor grudado."],
      ["Acrescente a cebola e refogue até dourar nas pontas.", 300],
    ],
    tips: ["Não precisa de óleo: a linguiça solta gordura suficiente.", "Cerveja no lugar da água dá um sabor especial."],
    subs: [["Calabresa", "Linguiça toscana ou de frango."], ["Cebola", "Cebola roxa ou alho-poró."]],
  },
  {
    id: "porco-assado-limao",
    t: "Lombo de porco assado",
    d: "Marinado na véspera, macio no dia.",
    cat: "Carnes",
    time: "2 h",
    serv: "6 porções",
    diff: "Médio",
    ing: ["1,5 kg de lombo suíno", "Suco de 2 laranjas e 1 limão", "6 dentes de alho", "Alecrim e louro", "Sal, pimenta e azeite", "1 xícara de vinho branco"],
    st: [
      ["Marine o lombo por 12 horas na geladeira, virando na metade.", null, "Marinada ácida amacia e perfuma a carne por dentro."],
      ["Asse coberto a 180 °C por 1 hora, regando com a marinada.", 3600],
      ["Descubra e asse mais 30 minutos para dourar.", 1800],
      ["Descanse 15 minutos antes de fatiar.", 900],
    ],
    tips: ["Lombo passa do ponto fácil: 70 °C no centro já basta.", "O líquido da assadeira vira molho: ferva e reduza."],
    subs: [["Lombo", "Pernil ou filé mignon suíno (menos tempo)."], ["Vinho branco", "Suco de laranja + caldo."]],
  },
  {
    id: "costelinha-barbecue",
    t: "Costelinha suína com barbecue",
    d: "Assada devagar e pincelada no final.",
    cat: "Carnes",
    time: "2 h 30 min",
    serv: "4 porções",
    diff: "Médio",
    ing: ["1,5 kg de costelinha suína", "Sal, páprica defumada e alho em pó", "1 xícara de molho barbecue", "Papel-alumínio"],
    st: [
      "Tempere a costelinha com os secos e embrulhe no alumínio.",
      ["Asse a 160 °C por 2 horas.", 3600],
      ["Abra, pincele o barbecue e asse a 220 °C por 15 minutos.", 900, "Molho doce só no final: com calor por muito tempo, ele queima."],
    ],
    tips: ["Retirar a membrana das costelas deixa tudo mais macio.", "Pincele em 2 camadas para uma casquinha brilhante."],
    subs: [["Molho barbecue", "Ketchup + melado + mostarda + fumaça líquida."], ["Costelinha suína", "Asa de frango (30 minutos)."]],
  },
  {
    id: "peixe-assado-forno",
    t: "Peixe assado com limão e ervas",
    d: "Peixe inteiro, forno quente, 25 minutos.",
    cat: "Peixes",
    time: "35 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: ["1 peixe inteiro limpo (tilápia, pargo)", "1 limão em rodelas", "Alho, azeite e sal", "Tomilho ou salsinha", "1 cebola em rodelas"],
    st: [
      "Faça cortes na pele e tempere por dentro e por fora.",
      "Recheie a barriga com limão e ervas.",
      ["Asse a 200 °C por 25 minutos sobre cebolas.", 1500, "A carne se solta da espinha com facilidade quando está pronta."],
    ],
    tips: ["Peixe passa do ponto em minutos: fique de olho.", "Cortes na pele fazem o tempero entrar e o calor circular."],
    subs: [["Peixe inteiro", "Filés (15 minutos)."], ["Tomilho", "Alecrim, coentro ou orégano."]],
  },
  {
    id: "file-tilapia-frigideira",
    t: "Filé de tilápia na frigideira",
    d: "Dourado em 6 minutos, sem grudar.",
    cat: "Peixes",
    time: "15 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: ["2 filés de tilápia", "Suco de 1/2 limão", "Farinha de trigo", "Manteiga e azeite", "Sal e pimenta"],
    st: [
      ["Seque muito bem os filés com papel-toalha.", null, "Peixe seco doura; peixe úmido cozinha e gruda."],
      "Tempere e passe levemente na farinha.",
      ["Frite em azeite quente por 3 minutos sem mexer.", 180],
      ["Vire, junte a manteiga e cozinhe mais 2 minutos regando o peixe.", 120],
    ],
    tips: ["Só vire uma vez: peixe é frágil.", "Frigideira quente antes de o peixe entrar evita que grude."],
    subs: [["Tilápia", "Merluza, pescada ou saint peter."], ["Farinha de trigo", "Fubá ou farinha de arroz."]],
  },
  {
    id: "salmao-grelhado",
    t: "Salmão grelhado com pele crocante",
    d: "Pele crocante, centro rosado.",
    cat: "Peixes",
    time: "15 min",
    serv: "2 porções",
    diff: "Médio",
    ing: ["2 postas de salmão com pele", "Azeite", "Sal grosso e pimenta", "Limão siciliano"],
    st: [
      "Seque a pele e salgue generosamente.",
      ["Coloque com a pele para baixo na frigideira quente e pressione por 20 segundos.", 20, "Pressionar impede que a pele encolha e enrole."],
      ["Cozinhe 5 minutos sem mexer, até a pele soltar sozinha.", 300],
      ["Vire e finalize por 1 a 2 minutos.", 90],
    ],
    tips: ["Se não solta da frigideira, ainda não está na hora de virar.", "Centro levemente rosado = suculento."],
    subs: [["Salmão", "Truta ou atum fresco."], ["Limão siciliano", "Limão tahiti ou laranja."]],
  },
  {
    id: "moqueca-peixe",
    t: "Moqueca de peixe",
    d: "Leite de coco, dendê e pimentões.",
    cat: "Peixes",
    time: "45 min",
    serv: "4 porções",
    diff: "Médio",
    ing: ["800 g de peixe firme em postas", "400 ml de leite de coco", "2 colheres (sopa) de azeite de dendê", "2 tomates, 1 cebola e 2 pimentões em rodelas", "Coentro", "Suco de 1 limão, sal e pimenta"],
    st: [
      ["Tempere o peixe com limão, alho e sal por 20 minutos.", 1200],
      "Monte camadas na panela: cebola, tomate, pimentão, peixe, repetindo.",
      ["Regue com leite de coco e dendê e cozinhe tampado em fogo médio por 20 minutos.", 1200, "Moqueca não se mexe: sacuda a panela para não desmanchar o peixe."],
      "Finalize com coentro fresco.",
    ],
    tips: ["Peixe firme (badejo, cação, robalo) não se desfaz.", "Dendê é forte: 2 colheres bastam."],
    subs: [["Dendê", "Azeite + 1 colher de páprica (fica moqueca capixaba)."], ["Peixe", "Camarão ou misto."]],
  },
  {
    id: "camarao-alho",
    t: "Camarão ao alho e óleo",
    d: "Cinco minutos de fogo, nem um segundo a mais.",
    cat: "Peixes",
    time: "15 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: ["500 g de camarão limpo", "5 dentes de alho fatiados", "Azeite generoso", "Pimenta calabresa", "Salsinha e limão", "Sal"],
    st: [
      ["Seque os camarões e tempere com sal.", null, "Camarão molhado solta água e cozinha em vez de dourar."],
      ["Doure o alho no azeite em fogo médio.", 90],
      ["Junte os camarões em fogo alto e cozinhe 90 segundos de cada lado.", 90],
      "Finalize com salsinha, calabresa e limão fora do fogo.",
    ],
    tips: ["Camarão pronto forma um C; se virar um O, passou do ponto.", "Passou do ponto = borracha. Melhor tirar antes."],
    subs: [["Camarão fresco", "Camarão congelado bem descongelado e seco."], ["Salsinha", "Coentro ou cebolinha."]],
  },
  {
    id: "bacalhau-natas",
    t: "Bacalhau com natas",
    d: "Gratinado português para dia de festa.",
    cat: "Peixes",
    time: "1 h 30 min",
    serv: "6 porções",
    diff: "Difícil",
    ing: ["600 g de bacalhau dessalgado e desfiado", "1 kg de batatas em cubos", "2 cebolas em rodelas", "500 ml de creme de leite fresco", "200 ml de leite", "Azeite, alho e noz-moscada", "Queijo ralado"],
    st: [
      ["Dessalgue o bacalhau por 24 a 36 horas na geladeira, trocando a água 4 vezes.", null, "Sem dessalgue correto, nada salva o prato."],
      ["Frite as batatas até dourarem levemente e reserve.", 900],
      ["Refogue cebola e alho no azeite e junte o bacalhau por 5 minutos.", 300],
      "Misture com batatas, creme, leite e noz-moscada em um refratário.",
      ["Cubra com queijo e gratine a 200 °C por 25 minutos.", 1500],
    ],
    tips: ["Prove antes de salgar: quase nunca precisa de sal.", "Batata frita (não cozida) segura a textura no forno."],
    subs: [["Bacalhau", "Pescada branca salgada ou peixe fresco desfiado."], ["Creme de leite fresco", "Creme de leite de caixinha + leite."]],
  },
  {
    id: "atum-massa-rapida",
    t: "Bolinho de atum de frigideira",
    d: "Lanche proteico com 4 ingredientes.",
    cat: "Peixes",
    time: "20 min",
    serv: "10 bolinhos",
    diff: "Fácil",
    ing: ["2 latas de atum escorrido", "1 ovo", "3 colheres (sopa) de farinha de aveia ou trigo", "Cebolinha, sal e pimenta", "Azeite"],
    st: [
      "Misture tudo até dar liga.",
      ["Se a massa esfarelar, junte mais 1 colher de farinha ou meio ovo.", null, "Massa que fica em pé na colher tem o ponto certo."],
      ["Frite colheradas em azeite, 3 minutos de cada lado.", 360],
    ],
    tips: ["Atum bem escorrido é essencial para a liga.", "Air fryer a 200 °C por 12 minutos também funciona."],
    subs: [["Atum", "Sardinha ou frango desfiado."], ["Farinha de aveia", "Farinha de rosca ou trigo."]],
  },
  {
    id: "frango-empanado-air-fryer",
    t: "Frango empanado na air fryer",
    d: "Crocante com 1 colher de óleo.",
    cat: "Aves",
    time: "30 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: ["600 g de peito em tiras", "1 ovo batido", "1 xícara de farinha de rosca panko", "Sal, páprica e alho em pó", "Spray de óleo"],
    st: [
      "Tempere o frango e passe no ovo e na farinha de rosca.",
      ["Borrife óleo dos dois lados.", null, "Sem óleo, o empanado fica branco e seco."],
      ["Air fryer a 200 °C por 12 minutos, virando na metade.", 720],
    ],
    tips: ["Não empilhe as tiras na cesta.", "Pré-aquecer a air fryer por 3 minutos melhora a crocância."],
    subs: [["Panko", "Farinha de rosca comum + 1 colher de fubá."], ["Air fryer", "Forno a 220 °C por 20 minutos."]],
  },
  {
    id: "peru-natal",
    t: "Peito de peru natalino",
    d: "Marinada de vinho e ervas, assado suculento.",
    cat: "Aves",
    time: "3 h",
    serv: "8 porções",
    diff: "Difícil",
    ing: ["2 kg de peito de peru", "1 litro de água + 80 g de sal (salmoura)", "500 ml de vinho branco", "Alecrim, tomilho e louro", "Manteiga amolecida", "Alho e pimenta"],
    st: [
      ["Deixe o peru na salmoura por 8 horas na geladeira.", null, "Salmoura é o que impede o peito (carne magra) de ressecar."],
      "Seque, passe manteiga com ervas por baixo da pele.",
      ["Asse coberto a 170 °C por 2 horas, regando com o vinho.", 3600],
      ["Descubra e doure por 30 minutos.", 1800],
      ["Descanse 20 minutos antes de fatiar.", 1200],
    ],
    tips: ["Termômetro: 72 °C no centro é o ponto exato.", "Fatie contra as fibras, sempre."],
    subs: [["Vinho branco", "Suco de uva branco + vinagre."], ["Peito de peru", "Frango inteiro grande (menos tempo)."]],
  },
  {
    id: "carne-de-panela-pressao",
    t: "Músculo na pressão com legumes",
    d: "Refeição completa em 50 minutos.",
    cat: "Carnes",
    time: "50 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["800 g de músculo em cubos", "2 batatas e 2 cenouras", "1 cebola e 3 dentes de alho", "2 colheres (sopa) de extrato de tomate", "Louro, sal e pimenta", "Água quente"],
    st: [
      ["Doure a carne na própria panela de pressão, aberta.", 480],
      "Junte cebola, alho e extrato.",
      ["Cubra com água quente e feche; cozinhe 30 minutos após pegar pressão.", 1800],
      ["Abra com segurança, junte os legumes e cozinhe 8 minutos sem tampa de pressão.", 480, "Legumes junto desde o início viram purê."],
    ],
    tips: ["Pressão sempre com água quente para não endurecer a carne.", "Molho ralo? Ferva sem tampa no final."],
    subs: [["Músculo", "Acém ou paleta."], ["Batata", "Mandioca ou mandioquinha."]],
  },
  {
    id: "fraldinha-grelhada",
    t: "Fraldinha grelhada",
    d: "Corte barato com sabor de churrasco.",
    cat: "Carnes",
    time: "25 min",
    serv: "4 porções",
    diff: "Médio",
    ing: ["1 kg de fraldinha", "Sal grosso", "Alho e pimenta", "Azeite"],
    st: [
      ["Tempere e deixe fora da geladeira por 30 minutos.", 1800],
      ["Grelhe em fogo alto por 6 minutos de cada lado.", 360],
      ["Descanse 8 minutos.", 480, "O descanso redistribui o suco por toda a peça."],
      "Fatie sempre contra as fibras, em tiras finas.",
    ],
    tips: ["Fraldinha malpassada ou ao ponto: bem passada endurece.", "Fatiar no sentido errado deixa a carne dura mesmo no ponto certo."],
    subs: [["Fraldinha", "Contrafilé, alcatra ou maminha."], ["Grelha", "Frigideira de ferro bem quente."]],
  },
  {
    id: "carne-de-sol-mandioca",
    t: "Carne de sol com mandioca na manteiga",
    d: "Dupla nordestina indestrutível.",
    cat: "Carnes",
    time: "1 h",
    serv: "4 porções",
    diff: "Médio",
    ing: ["700 g de carne de sol dessalgada", "800 g de mandioca cozida", "100 g de manteiga de garrafa ou comum", "1 cebola em rodelas", "Alho e cheiro-verde"],
    st: [
      ["Dessalgue a carne por 2 horas em água, trocando duas vezes.", null, "Se a carne estiver muito salgada, ferva 5 minutos e descarte a água."],
      ["Cozinhe a mandioca até ficar macia.", 2400],
      ["Corte a carne em cubos e doure na manteiga.", 600],
      ["Junte a mandioca e a cebola e frite até dourar.", 480],
    ],
    tips: ["Mandioca cozida e depois frita fica cremosa por dentro.", "Não salgue: a carne já traz sal suficiente."],
    subs: [["Carne de sol", "Carne seca dessalgada ou fraldinha temperada."], ["Manteiga de garrafa", "Manteiga comum + 1 colher de azeite."]],
  },
];

export const daily3 = makeAll(raw);
