import { makeAll, type RawRecipe } from "./recipe-types";

const raw: RawRecipe[] = [
  {
    id: "sopa-legumes",
    t: "Sopa de legumes",
    d: "Panela única, geladeira limpa.",
    cat: "Sopas",
    time: "40 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["1 batata, 1 cenoura, 1 abobrinha e 1 chuchu", "1 cebola e 2 dentes de alho", "1,5 litro de caldo ou água", "Azeite, sal e pimenta", "Cheiro-verde"],
    st: [
      ["Refogue cebola e alho no azeite.", 180],
      "Junte os legumes em cubos e refogue mais 3 minutos.",
      ["Cubra com o caldo e cozinhe por 25 minutos.", 1500, "Refogar antes de colocar o líquido dá muito mais sabor que só ferver tudo."],
      "Amasse alguns pedaços para engrossar e finalize com cheiro-verde.",
    ],
    tips: ["Cortes iguais cozinham por igual.", "Caldo caseiro (talos e cascas fervidos) muda o resultado."],
    subs: [["Chuchu", "Mandioquinha, abóbora ou vagem."], ["Caldo pronto", "Água + 1 tomate + 1 talo de salsão."]],
  },
  {
    id: "caldo-verde",
    t: "Caldo verde",
    d: "Batata cremosa, couve e calabresa.",
    cat: "Sopas",
    time: "45 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["800 g de batatas", "1 maço pequeno de couve fatiada fina", "200 g de linguiça calabresa em rodelas", "1 cebola e 3 dentes de alho", "1,2 litro de água", "Azeite e sal"],
    st: [
      ["Cozinhe batatas, cebola e alho na água até desmancharem.", 1500],
      "Bata no liquidificador ou com mixer até virar creme.",
      ["Doure a calabresa à parte e junte ao creme.", 300],
      ["Adicione a couve e cozinhe apenas 2 minutos.", 120, "Couve por muito tempo perde a cor e o sabor."],
      "Finalize com bastante azeite.",
    ],
    tips: ["Couve bem fininha é a assinatura do prato.", "Azeite generoso no final não é opcional."],
    subs: [["Calabresa", "Bacon, paio ou nada (versão vegetariana)."], ["Couve", "Espinafre ou agrião."]],
  },
  {
    id: "canja-galinha",
    t: "Canja de galinha",
    d: "Remédio caseiro em forma de sopa.",
    cat: "Sopas",
    time: "50 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["500 g de coxa de frango", "1/2 xícara de arroz", "1 cenoura em cubos", "1 cebola e 2 dentes de alho", "1,5 litro de água", "Salsinha, sal e pimenta"],
    st: [
      ["Cozinhe o frango na água com cebola e alho por 25 minutos.", 1500],
      "Retire, desfie e devolve à panela.",
      ["Junte arroz e cenoura e cozinhe mais 15 minutos.", 900, "O arroz continua absorvendo caldo depois de pronto — faça caldo sobrando."],
      "Finalize com salsinha e pimenta.",
    ],
    tips: ["Coxa dá mais sabor ao caldo que peito.", "Um fio de limão na hora de servir levanta o prato."],
    subs: [["Arroz", "Macarrão cabelo de anjo (5 minutos)."], ["Frango com osso", "Peito desfiado + caldo pronto."]],
  },
  {
    id: "sopa-cebola",
    t: "Sopa de cebola gratinada",
    d: "Cebolas caramelizadas por 40 minutos.",
    cat: "Sopas",
    time: "1 h 15 min",
    serv: "4 porções",
    diff: "Difícil",
    ing: ["1 kg de cebolas em fatias finas", "60 g de manteiga", "1 colher (chá) de açúcar", "1,2 litro de caldo de carne", "1/2 xícara de vinho branco", "Fatias de pão e queijo gruyère"],
    st: [
      ["Cozinhe as cebolas na manteiga com açúcar, em fogo baixo, por 40 minutos.", 3600, "Não tem atalho: a caramelização lenta é o prato inteiro."],
      ["Deglaceie com o vinho, raspando o fundo.", 120],
      ["Junte o caldo e cozinhe 20 minutos.", 1200],
      ["Sirva em tigelas com pão e queijo e gratine no forno até dourar.", 480],
    ],
    tips: ["Cebola mexida demais não carameliza: mexa a cada 5 minutos.", "Fundo escuro na panela é sabor, não queimado — desde que não amargue."],
    subs: [["Gruyère", "Muçarela + parmesão."], ["Vinho branco", "Caldo + 1 colher de vinagre."]],
  },
  {
    id: "creme-mandioquinha",
    t: "Creme de mandioquinha",
    d: "Aveludado e naturalmente adocicado.",
    cat: "Sopas",
    time: "40 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["800 g de mandioquinha", "1 cebola e 2 dentes de alho", "1,2 litro de caldo de legumes", "1 colher (sopa) de manteiga", "Sal, pimenta e noz-moscada"],
    st: [
      ["Refogue cebola e alho na manteiga.", 180],
      ["Junte a mandioquinha e o caldo e cozinhe até desmanchar.", 1500],
      ["Bata com mixer até ficar liso.", null, "Bata com o caldo ainda quente: fica mais sedoso."],
      "Ajuste a consistência com mais caldo e tempere.",
    ],
    tips: ["Passar por peneira deixa textura de restaurante.", "Croutons ou bacon crocante dão contraste."],
    subs: [["Mandioquinha", "Abóbora, batata-doce ou couve-flor."], ["Manteiga", "Azeite."]],
  },
  {
    id: "sopa-feijao",
    t: "Sopa de feijão com macarrão",
    d: "Sobra de feijão vira jantar completo.",
    cat: "Sopas",
    time: "30 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["3 xícaras de feijão cozido com caldo", "1 xícara de macarrão pequeno", "1 cenoura ralada", "Bacon ou calabresa (opcional)", "Alho, sal e cheiro-verde", "Água"],
    st: [
      "Bata metade do feijão com caldo no liquidificador.",
      ["Doure alho e bacon na panela e junte o feijão batido e o inteiro.", 300],
      ["Acrescente água até a consistência de sopa e ferva.", 300],
      ["Junte o macarrão e cozinhe até al dente.", 480, "O macarrão engrossa a sopa depois — deixe mais líquida do que quer."],
    ],
    tips: ["Feijão de véspera é perfeito aqui.", "Torradas de alho por cima completam."],
    subs: [["Macarrão", "Arroz cozido ou mandioca em cubos."], ["Bacon", "Legumes refogados."]],
  },
  {
    id: "sopa-tomate",
    t: "Sopa cremosa de tomate",
    d: "Tomates assados batidos com manjericão.",
    cat: "Sopas",
    time: "50 min",
    serv: "4 porções",
    diff: "Médio",
    ing: ["1 kg de tomates maduros em metades", "1 cebola e 4 dentes de alho", "Azeite, sal e açúcar", "500 ml de caldo de legumes", "Manjericão", "Creme de leite opcional"],
    st: [
      ["Asse tomates, cebola e alho com azeite a 200 °C por 30 minutos.", 1800, "Assar concentra o açúcar do tomate: sopa muito mais saborosa."],
      "Bata tudo com o caldo até ficar liso.",
      ["Ferva por 5 minutos, ajuste sal e junte manjericão.", 300],
    ],
    tips: ["Ácida demais? Pitada de açúcar ou fio de creme.", "Peneirar tira as sementes e deixa aveludada."],
    subs: [["Tomate fresco", "Tomate pelado em lata."], ["Creme de leite", "Leite ou nada."]],
  },
  {
    id: "caldo-mandioca",
    t: "Caldo de mandioca com carne",
    d: "Encorpado, para noites frias.",
    cat: "Sopas",
    time: "1 h",
    serv: "5 porções",
    diff: "Médio",
    ing: ["800 g de mandioca", "400 g de músculo em cubos", "1 cebola e 3 dentes de alho", "1,5 litro de água", "Bacon, sal e pimenta", "Cheiro-verde"],
    st: [
      ["Cozinhe a carne na pressão por 25 minutos.", 1500],
      ["Adicione a mandioca e cozinhe até desmanchar.", 1200],
      ["Bata parte da mandioca com o caldo e devolva à panela.", null, "Bater só uma parte dá cremosidade sem perder os pedaços."],
      ["Ferva mais 10 minutos e finalize com bacon frito.", 600],
    ],
    tips: ["Mandioca velha não amolece: escolha peças frescas.", "Congele em potes individuais."],
    subs: [["Músculo", "Costela, carne seca ou frango."], ["Mandioca", "Batata-doce ou abóbora."]],
  },
  {
    id: "salada-verde-vinagrete",
    t: "Salada verde com vinagrete",
    d: "Molho na proporção clássica 3 para 1.",
    cat: "Saladas",
    time: "10 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["1 pé de alface", "Rúcula e agrião", "3 colheres (sopa) de azeite", "1 colher (sopa) de vinagre", "1 colher (chá) de mostarda", "Sal e pimenta"],
    st: [
      ["Lave e seque muito bem as folhas.", null, "Folha molhada não segura molho — seque sempre."],
      "Bata azeite, vinagre, mostarda, sal e pimenta até emulsionar.",
      "Tempere só na hora de servir.",
    ],
    tips: ["Proporção base: 3 de azeite para 1 de ácido.", "Mostarda é o que faz o molho ligar."],
    subs: [["Vinagre", "Limão ou vinagre balsâmico."], ["Mostarda", "1/2 colher de mel."]],
  },
  {
    id: "salada-tomate-cebola",
    t: "Salada de tomate com cebola",
    d: "Acompanhamento clássico do almoço.",
    cat: "Saladas",
    time: "10 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["4 tomates em rodelas", "1 cebola em fatias finas", "Azeite e vinagre", "Orégano", "Sal e pimenta"],
    st: [
      ["Deixe a cebola de molho em água gelada por 10 minutos.", 600, "Isso tira o ardido da cebola crua."],
      "Monte com o tomate e tempere.",
      "Deixe descansar 5 minutos antes de servir.",
    ],
    tips: ["Sal na hora de servir: antes, o tomate solta muita água.", "Tomate em temperatura ambiente tem muito mais sabor."],
    subs: [["Cebola comum", "Cebola roxa (mais suave)."], ["Orégano", "Manjericão fresco."]],
  },
  {
    id: "salada-maionese",
    t: "Salada de maionese",
    d: "Batata, cenoura e ervilha do churrasco.",
    cat: "Saladas",
    time: "40 min",
    serv: "6 porções",
    diff: "Fácil",
    ing: ["4 batatas e 2 cenouras em cubos", "1 xícara de ervilha", "1 xícara de maionese", "1 cebola pequena ralada", "Salsinha, sal e pimenta"],
    st: [
      ["Cozinhe batata e cenoura até ficarem macias mas firmes, 12 minutos.", 720, "Legume mole demais vira purê ao misturar."],
      ["Escorra e espere esfriar completamente.", 1800, "Maionese em legume quente talha e azeda mais rápido."],
      "Misture com maionese, cebola e temperos.",
    ],
    tips: ["Cozinhe em água salgada: tempera por dentro.", "Consuma em até 2 dias, sempre refrigerada."],
    subs: [["Maionese", "Metade maionese, metade iogurte natural."], ["Ervilha", "Milho ou maçã em cubos."]],
  },
  {
    id: "salada-grao-de-bico",
    t: "Salada de grão-de-bico",
    d: "Proteína vegetal que enche o prato.",
    cat: "Saladas",
    time: "15 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["2 xícaras de grão-de-bico cozido", "1 tomate e 1/2 cebola roxa", "Pepino em cubos", "Azeite, limão, sal e pimenta", "Salsinha e hortelã"],
    st: ["Escorra e lave bem o grão-de-bico.", "Misture com os legumes picados.", ["Tempere e deixe descansar 10 minutos antes de servir.", 600, "O descanso deixa o grão absorver o tempero."]],
    tips: ["Grão-de-bico de lata funciona bem — só lave para tirar o sódio.", "Fica ainda melhor no dia seguinte."],
    subs: [["Grão-de-bico", "Feijão-branco ou lentilha cozida."], ["Hortelã", "Coentro ou manjericão."]],
  },
  {
    id: "tabule",
    t: "Tabule",
    d: "Trigo, muito verde e limão.",
    cat: "Saladas",
    time: "45 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["1 xícara de trigo para quibe", "2 maços de salsinha picada", "Hortelã", "3 tomates sem sementes", "1/2 cebola", "Azeite, suco de 2 limões e sal"],
    st: [
      ["Hidrate o trigo em água fria por 30 minutos e esprema bem.", 1800],
      "Pique tudo bem fininho.",
      ["Misture e tempere generosamente com limão e azeite.", null, "Tabule é mais salsinha que trigo — não economize no verde."],
    ],
    tips: ["Tomate sem semente evita salada aguada.", "Melhora depois de 1 hora na geladeira."],
    subs: [["Trigo para quibe", "Quinoa ou cuscuz marroquino."], ["Hortelã", "Só salsinha, se preferir."]],
  },
  {
    id: "salada-repolho",
    t: "Salada de repolho cremosa",
    d: "Crocante, com molho de iogurte.",
    cat: "Saladas",
    time: "15 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["1/2 repolho fatiado fino", "1 cenoura ralada", "1/2 xícara de maionese ou iogurte", "1 colher (sopa) de vinagre", "1 colher (chá) de açúcar", "Sal e pimenta"],
    st: [
      ["Deixe o repolho em água gelada por 10 minutos e seque.", 600, "Água gelada deixa o repolho extra crocante."],
      "Misture o molho à parte.",
      "Junte tudo pouco antes de servir.",
    ],
    tips: ["Temperado com muita antecedência, murcha.", "Fatiar bem fino faz toda a diferença."],
    subs: [["Maionese", "Iogurte natural + mostarda."], ["Repolho verde", "Repolho roxo (fica mais bonito)."]],
  },
  {
    id: "vinagrete",
    t: "Vinagrete de churrasco",
    d: "O molho que acompanha tudo.",
    cat: "Saladas",
    time: "15 min",
    serv: "6 porções",
    diff: "Fácil",
    ing: ["4 tomates sem sementes", "1 cebola", "1 pimentão", "1/2 xícara de vinagre", "1/4 xícara de azeite", "Cheiro-verde, sal e pimenta"],
    st: ["Pique tudo em cubos pequenos e iguais.", "Misture com vinagre, azeite e sal.", ["Descanse 30 minutos na geladeira antes de servir.", 1800, "O descanso é o que casa os sabores."]],
    tips: ["Sem semente de tomate = vinagrete menos aguado.", "Água gelada na cebola tira o ardido."],
    subs: [["Vinagre", "Limão."], ["Pimentão", "Pepino em cubos."]],
  },
  {
    id: "pudim-leite",
    t: "Pudim de leite condensado",
    d: "Clássico de família, sem furinhos.",
    cat: "Doces",
    time: "1 h 30 min",
    serv: "8 porções",
    diff: "Médio",
    ing: ["1 lata de leite condensado", "2 latas de leite", "3 ovos", "1 xícara de açúcar para a calda"],
    st: [
      ["Faça a calda derretendo o açúcar em fogo médio até dourar e forre a forma.", 480, "Calda escura demais amarga; tire do fogo no tom de caramelo claro."],
      "Bata leite condensado, leite e ovos no liquidificador por 2 minutos.",
      ["Passe por uma peneira antes de despejar na forma.", null, "Peneirar tira a espuma — é isso que evita os furinhos."],
      ["Asse em banho-maria a 180 °C por 1 hora, coberto com alumínio.", 3600],
      ["Gele por 4 horas antes de desenformar.", null, "Pudim morno desmancha ao virar."],
    ],
    tips: ["Água do banho-maria deve estar quente ao entrar no forno.", "Teste: espete uma faca — deve sair limpa."],
    subs: [["Leite", "Leite de coco (pudim tropical)."], ["Forno", "Panela de pressão: 25 minutos sem a válvula, em banho-maria."]],
  },
  {
    id: "brigadeiro",
    t: "Brigadeiro de panela",
    d: "Três ingredientes e ponto certo.",
    cat: "Doces",
    time: "20 min",
    serv: "20 unidades",
    diff: "Fácil",
    ing: ["1 lata de leite condensado", "3 colheres (sopa) de chocolate em pó", "1 colher (sopa) de manteiga", "Granulado"],
    st: [
      "Misture tudo na panela ainda fria.",
      ["Cozinhe em fogo baixo mexendo sem parar por 10 minutos.", 600, "Fogo alto queima o fundo e deixa gosto amargo."],
      ["Ponto: ao inclinar a panela, a massa desliza junta e mostra o fundo.", null, "Para enrolar, cozinhe 2 minutos além do ponto de colher."],
      "Esfrie em prato untado antes de enrolar.",
    ],
    tips: ["Chocolate em pó (não achocolatado) faz diferença enorme.", "Enrole com as mãos untadas com manteiga."],
    subs: [["Chocolate em pó", "Cacau em pó (mais amargo, use 2 colheres)."], ["Manteiga", "Margarina ou óleo de coco."]],
  },
  {
    id: "bolo-cenoura",
    t: "Bolo de cenoura com cobertura",
    d: "Fofinho, batido no liquidificador.",
    cat: "Doces",
    time: "55 min",
    serv: "10 porções",
    diff: "Fácil",
    ing: ["3 cenouras médias", "3 ovos", "1 xícara de óleo", "2 xícaras de açúcar", "2 1/2 xícaras de farinha", "1 colher (sopa) de fermento", "Cobertura: 4 colheres de chocolate em pó, 1 xícara de açúcar, 1 colher de manteiga, 1/2 xícara de leite"],
    st: [
      "Bata cenoura, ovos, óleo e açúcar no liquidificador por 3 minutos.",
      ["Misture a farinha em uma tigela e por último o fermento, com fubá delicadeza.", null, "Fermento entra por último e a massa vai ao forno logo em seguida."],
      ["Asse a 180 °C por 40 minutos.", 2400],
      ["Ferva os ingredientes da cobertura por 5 minutos e despeje sobre o bolo morno.", 300],
    ],
    tips: ["Não abra o forno nos primeiros 25 minutos: o bolo murcha.", "Palito no centro deve sair seco."],
    subs: [["Óleo", "Manteiga derretida (fica mais denso)."], ["Cobertura", "Só açúcar de confeiteiro com limão."]],
  },
  {
    id: "bolo-chocolate-simples",
    t: "Bolo de chocolate simples",
    d: "Uma tigela, um garfo, um bolo.",
    cat: "Doces",
    time: "50 min",
    serv: "10 porções",
    diff: "Fácil",
    ing: ["2 xícaras de farinha", "1 1/2 xícara de açúcar", "1 xícara de chocolate em pó", "1 xícara de leite morno", "1/2 xícara de óleo", "3 ovos", "1 colher (sopa) de fermento"],
    st: [
      "Misture os secos (menos o fermento) em uma tigela.",
      "Junte os líquidos e mexa até ficar homogêneo; por último o fermento.",
      ["Asse a 180 °C por 35 a 40 minutos.", 2400, "Massa de chocolate é escura: use o palito, não a cor, para saber o ponto."],
    ],
    tips: ["Leite morno realça o sabor do cacau.", "Forma untada e enfarinhada com chocolate em pó não deixa marca branca."],
    subs: [["Leite", "Café morno (intensifica o chocolate)."], ["Chocolate em pó", "Cacau + 2 colheres extras de açúcar."]],
  },
  {
    id: "mousse-maracuja",
    t: "Mousse de maracujá",
    d: "Três ingredientes, sem forno.",
    cat: "Doces",
    time: "15 min + geladeira",
    serv: "6 porções",
    diff: "Fácil",
    ing: ["1 lata de leite condensado", "1 lata de creme de leite", "1 xícara de suco concentrado de maracujá", "Polpa com sementes para decorar"],
    st: [
      ["Bata leite condensado, creme de leite e suco por 3 minutos.", 180, "O ácido do maracujá é que dá firmeza — não precisa de gelatina."],
      "Despeje em taças e cubra com a polpa.",
      "Leve à geladeira por no mínimo 4 horas.",
    ],
    tips: ["Suco concentrado, não refresco pronto.", "Menos suco = mousse mais doce e mais mole."],
    subs: [["Maracujá", "Limão (mesma proporção) ou morango batido."], ["Creme de leite", "Creme de leite fresco batido em chantilly."]],
  },
  {
    id: "arroz-doce",
    t: "Arroz doce cremoso",
    d: "Canela, leite e paciência.",
    cat: "Doces",
    time: "45 min",
    serv: "6 porções",
    diff: "Fácil",
    ing: ["1 xícara de arroz", "2 xícaras de água", "1 litro de leite", "1 lata de leite condensado", "Canela em pau e cravo", "Canela em pó"],
    st: [
      ["Cozinhe o arroz na água com canela e cravo até secar.", 900],
      ["Junte o leite aos poucos e cozinhe em fogo baixo por 20 minutos, mexendo.", 1200, "Leite de uma vez só e fogo alto = leite queimado no fundo."],
      "Adicione o leite condensado e cozinhe mais 5 minutos.",
      "Sirva com canela em pó.",
    ],
    tips: ["Ele engrossa muito ao esfriar: desligue mais ralo do que quer.", "Arroz comum funciona melhor que parboilizado."],
    subs: [["Leite condensado", "1 xícara de açúcar."], ["Leite", "Leite de coco na metade da quantidade."]],
  },
  {
    id: "cocada-cremosa",
    t: "Cocada cremosa",
    d: "Coco, leite condensado e 15 minutos.",
    cat: "Doces",
    time: "20 min",
    serv: "6 porções",
    diff: "Fácil",
    ing: ["100 g de coco ralado", "1 lata de leite condensado", "1 caixa de creme de leite", "1/2 xícara de leite"],
    st: [
      ["Cozinhe leite condensado, coco e leite em fogo baixo por 10 minutos, mexendo.", 600],
      ["Desligue e junte o creme de leite.", null, "Creme de leite fora do fogo mantém a textura sedosa."],
      "Sirva morna ou gelada.",
    ],
    tips: ["Coco fresco ralado dá muito mais sabor.", "Ponto: cremosa, nunca dura."],
    subs: [["Creme de leite", "Leite de coco (mais líquida)."], ["Coco ralado seco", "Coco fresco ralado."]],
  },
  {
    id: "banana-caramelizada",
    t: "Banana caramelizada",
    d: "Sobremesa de 8 minutos com o que tem em casa.",
    cat: "Doces",
    time: "8 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: ["2 bananas em rodelas grossas", "2 colheres (sopa) de açúcar", "1 colher (sopa) de manteiga", "Canela"],
    st: [
      ["Derreta a manteiga com o açúcar até borbulhar.", 120],
      ["Coloque as bananas e deixe caramelizar 2 minutos de cada lado, sem mexer.", 240, "Mexer desmancha a banana antes de ela dourar."],
      "Polvilhe canela e sirva com sorvete.",
    ],
    tips: ["Banana firme (nem muito madura) segura o formato.", "Um fio de limão equilibra o doce."],
    subs: [["Banana", "Maçã ou abacaxi."], ["Manteiga", "Óleo de coco."]],
  },
  {
    id: "pave-chocolate",
    t: "Pavê de chocolate",
    d: "Camadas de biscoito e creme para o Natal.",
    cat: "Doces",
    time: "40 min + geladeira",
    serv: "10 porções",
    diff: "Médio",
    ing: ["2 pacotes de biscoito maisena", "1 litro de leite", "2 latas de leite condensado", "4 gemas e 2 claras", "3 colheres (sopa) de amido", "200 g de chocolate meio amargo", "Leite para molhar os biscoitos"],
    st: [
      ["Cozinhe leite, 1 lata de condensado, gemas e amido até engrossar.", 600, "Mexa sem parar com fouet: gema parada vira grumo."],
      "Faça o creme de chocolate com a outra lata e o chocolate derretido.",
      "Monte camadas: creme branco, biscoitos molhados no leite, creme de chocolate.",
      ["Cubra com claras em neve batidas com açúcar e leve à geladeira por 6 horas.", null, "Sem geladeira suficiente, o pavê não corta em fatias."],
    ],
    tips: ["Biscoito só passa rápido pelo leite, não fica de molho.", "Melhor feito na véspera."],
    subs: [["Biscoito maisena", "Champanhe ou bolo pronto fatiado."], ["Chocolate meio amargo", "Chocolate em pó + mais leite condensado."]],
  },
  {
    id: "torta-limao",
    t: "Torta de limão",
    d: "Base de biscoito, creme ácido e merengue.",
    cat: "Doces",
    time: "1 h + geladeira",
    serv: "8 porções",
    diff: "Difícil",
    ing: ["200 g de biscoito maisena triturado", "100 g de manteiga derretida", "2 latas de leite condensado", "1 xícara de suco de limão", "4 gemas", "4 claras e 8 colheres de açúcar"],
    st: [
      ["Misture biscoito e manteiga, forre a forma e asse a 180 °C por 10 minutos.", 600],
      "Bata leite condensado, gemas e suco de limão até engrossar.",
      ["Despeje sobre a base e leve à geladeira por 4 horas.", null, "O ácido do limão cozinha o creme a frio — não precisa de forno."],
      ["Bata as claras com açúcar em banho-maria até merengue firme e cubra.", 480],
      ["Doure o merengue com maçarico ou 5 minutos de forno alto.", 300],
    ],
    tips: ["Suco de limão fresco, coado, sem a parte branca (amarga).", "Merengue firme quando forma bico que não cai."],
    subs: [["Merengue", "Chantilly ou raspas de limão."], ["Biscoito maisena", "Bolacha de chocolate ou água e sal."]],
  },
  {
    id: "limonada-suica",
    t: "Limonada suíça",
    d: "Limão inteiro batido com leite condensado.",
    cat: "Bebidas",
    time: "6 min",
    serv: "3 copos",
    diff: "Fácil",
    ing: ["2 limões taiti bem lavados", "1 litro de água gelada", "4 colheres (sopa) de leite condensado", "Gelo"],
    st: [
      "Corte os limões em 8 partes, sem descascar.",
      ["Bata com a água por apenas 15 segundos.", 15, "Bater demais extrai o amargor da casca branca."],
      "Coe imediatamente e misture o leite condensado e o gelo.",
    ],
    tips: ["Coar na hora é obrigatório: a bebida amarga em minutos.", "Água gelada reduz o amargor."],
    subs: [["Leite condensado", "Açúcar ou adoçante."], ["Limão taiti", "Limão siciliano (mais suave)."]],
  },
  {
    id: "chocolate-quente",
    t: "Chocolate quente cremoso",
    d: "Espesso, de colher, com chocolate de verdade.",
    cat: "Bebidas",
    time: "15 min",
    serv: "3 xícaras",
    diff: "Fácil",
    ing: ["500 ml de leite", "150 g de chocolate meio amargo picado", "2 colheres (sopa) de chocolate em pó", "1 colher (sopa) de amido de milho", "Açúcar a gosto", "Canela"],
    st: [
      "Dissolva o amido em um pouco do leite frio.",
      ["Aqueça o restante do leite com o chocolate em pó e o açúcar.", 300],
      ["Junte o amido e cozinhe mexendo até engrossar, 4 minutos.", 240, "Amido precisa ferver para engrossar de verdade."],
      "Desligue e junte o chocolate picado, mexendo até derreter.",
    ],
    tips: ["Chocolate em barra fora do fogo mantém o brilho.", "Pitada de sal realça o chocolate."],
    subs: [["Chocolate meio amargo", "Ao leite (reduza o açúcar)."], ["Leite", "Leite vegetal (aveia funciona melhor)."]],
  },
  {
    id: "caipirinha-limao",
    t: "Caipirinha de limão",
    d: "Feita como manda o figurino.",
    cat: "Bebidas",
    time: "5 min",
    serv: "1 copo",
    diff: "Fácil",
    ing: ["1 limão taiti", "2 colheres (chá) de açúcar", "50 ml de cachaça", "Gelo em cubos"],
    st: [
      ["Corte o limão em 4, retire o miolo branco central.", null, "O miolo branco é o que deixa a caipirinha amarga."],
      "Macere com o açúcar sem esmagar a casca com força.",
      "Junte gelo e cachaça e mexa bem.",
    ],
    tips: ["Macerar demais a casca amarga a bebida.", "Gelo em cubos grandes derrete devagar e não agua."],
    subs: [["Cachaça", "Vodka (caipiroska) ou saquê (caipisake)."], ["Limão", "Morango, abacaxi ou maracujá."]],
  },
];

export const daily4 = makeAll(raw);
