import { makeAll, type Recipe } from "./recipe-types";

// Lote 6: café da manhã, lanches, doces, bebidas, peixes, saladas, legumes e sopas — para quem está começando.
export const daily6: Recipe[] = makeAll([
  {
    id: "tapioca-simples",
    t: "Tapioca simples com manteiga",
    d: "Só 3 ingredientes e 5 minutos. O café da manhã salvo de todo mundo.",
    cat: "Café da manhã",
    time: "5 min",
    serv: "1 porção",
    diff: "Fácil",
    ing: [
      "3 colheres (sopa) cheias de goma de tapioca granulada",
      "1 pitada de sal",
      "1 colher (chá) de manteiga",
    ],
    st: [
      "Peneire a goma em uma tigela junto com o sal, para separar os pedaços duros.",
      "Molhe aos poucos com 2 colheres de água, mexendo com os dedos até virar uma farofa úmida.",
      "Peneire essa farofa sobre uma frigideira fria antiaderente, formando um disco uniforme.",
      ["Deixe em fogo baixo por 3 minutos, até os grãos grudarem e formarem uma massa única.", 180, "Não vire a tapioca: ela é feita de um lado só."],
      "Espalhe a manteiga por cima, dobre ao meio e sirva na hora.",
    ],
    tips: [
      "A goma granulada já vem pronta para molhar. Se a sua for a goma seca de pacote, peneire direto na frigideira sem molhar.",
      "Frigideira fria na hora de polvilhar evita buracos na tapioca.",
      "Recheie depois de dobrada: queijo, coco ou geleia entram por cima, sem desmontar nada.",
    ],
    subs: [
      ["Manteiga", "Azeite ou queijo cremoso"],
      ["Sal", "1 colher de açúcar, se preferir doce"],
    ],
  },
  {
    id: "mingau-milho-verde",
    t: "Mingau de milho verde",
    d: "Cremoso, quentinho e pronto em 15 minutos na panela.",
    cat: "Café da manhã",
    time: "15 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: [
      "1 lata de milho verde escorrido",
      "2 xícaras de leite",
      "3 colheres (sopa) de açúcar",
      "1 colher (sopa) de amido de milho",
      "1 pitada de sal",
      "Canela em pó para polvilhar",
    ],
    st: [
      "Bata no liquidificador o milho, o leite, o açúcar, o amido e o sal por 2 minutos.",
      ["Leve à panela em fogo médio e mexa sem parar até engrossar, uns 8 minutos.", 480, "Mexer é o que evita grumos — deixa de mexer e forma pelota."],
      "Sirva quente com canela por cima.",
    ],
    tips: [
      "Prefere liso como creme? Coe o líquido batido por uma peneira antes de ir ao fogo.",
      "Se engrossar demais, junte leite quente aos poucos até chegar no ponto.",
    ],
    subs: [
      ["Leite", "Leite vegetal de aveia ou coco"],
      ["Açúcar", "1 colher de leite condensado (fica mais gostoso ainda)"],
      ["Milho em lata", "Milho congelado cozido"],
    ],
  },
  {
    id: "vitamina-abacate",
    t: "Vitamina de abacate",
    d: "O café da manhã mais cremoso do Brasil, em 3 minutos.",
    cat: "Bebidas",
    time: "5 min",
    serv: "1 copo grande",
    diff: "Fácil",
    ing: [
      "1/2 abacate maduro em pedaços",
      "1 xícara de leite gelado",
      "1 colher (sopa) de açúcar ou mel",
      "1 pitada de sal (opcional, realça o sabor)",
    ],
    st: [
      "Coloque tudo no liquidificador e bata por 1 minuto, até ficar liso.",
      "Prove e ajuste o açúcar. Sirva gelado, sem coar.",
    ],
    tips: [
      "Abacate maduro cede à pressão do dedo. Se estiver duro, espere 2 a 3 dias na fruteira.",
      "Uma pitada de sal e umas gotas de limão cortam o 'engraçado' que algumas pessoas sentem no abacate.",
      "Quer mais cremoso? Use menos leite ou junte 2 colheres de iogurte.",
    ],
    subs: [
      ["Leite", "Leite de coco — combina demais"],
      ["Açúcar ou mel", "1 colher de leite condensado"],
    ],
  },
  {
    id: "suco-laranja",
    t: "Suco de laranja natural",
    d: "Duas laranjas, um copo, zero conservantes.",
    cat: "Bebidas",
    time: "5 min",
    serv: "1 copo",
    diff: "Fácil",
    ing: ["3 laranjas maduras", "Água gelada e gelo a gosto", "Açúcar ou mel (opcional)"],
    st: [
      "Corte as laranjas ao meio e esprema com um espremedor manual (ou com as mãos, virando a metade contra um garfo espetado na polpa).",
      "Coe em uma peneira fina, direto no copo, se não gostar de polpa.",
      "Complete com água gelada e gelo. Prove antes de adoçar — laranja doce quase não precisa.",
    ],
    tips: [
      "Laranja em temperatura ambiente rende mais suco que a gelada.",
      "Esprema com movimento leve: apertar demais a casca deixa o suco amargo.",
      "Beba logo — vitamina C perde força ao ficar esperando.",
    ],
    subs: [
      ["Laranja pera", "Laranja lima (naturalmente doce) ou tangerina"],
      ["Açúcar", "Mel ou nada mesmo"],
    ],
  },
  {
    id: "suco-maracuja",
    t: "Suco de maracujá",
    d: "Azedinho, aromático e pronto na batedeira em 2 minutos.",
    cat: "Bebidas",
    time: "5 min",
    serv: "2 copos",
    diff: "Fácil",
    ing: [
      "2 maracujás maduros",
      "500 ml de água gelada",
      "3 colheres (sopa) de açúcar",
      "Gelo a gosto",
    ],
    st: [
      "Corte os maracujás ao meio e retire a polpa com uma colher para uma tigela.",
      "Coloque a polpa no liquidificador com a água e dê 3 batidas de 1 segundo apenas.",
      ["Coe por uma peneira, pressionando de leve com uma colher.", null, "NÃO bata muito: as sementes trituradas deixam o suco amargo."],
      "Misture o açúcar até dissolver e sirva com gelo.",
    ],
    tips: [
      "Maracujá maduro tem a casca enrugada e pesa na mão.",
      "Quer suco cremoso? Use leite no lugar da água e bata mais um pouquinho.",
    ],
    subs: [
      ["Açúcar", "Mel ou açúcar demerara"],
      ["Água", "Leite gelado para a versão cremosa"],
    ],
  },
  {
    id: "smoothie-manga",
    t: "Smoothie de manga",
    d: "Duas frutas, um pouco de leite e o melhor lanche líquido do mundo.",
    cat: "Bebidas",
    time: "5 min",
    serv: "2 copos",
    diff: "Fácil",
    ing: [
      "1 manga madura em cubos (cerca de 1 xícara)",
      "1 banana madura",
      "1/2 xícara de leite gelado",
      "1 colher (sopa) de mel",
      "4 cubos de gelo",
    ],
    st: [
      "Coloque tudo no liquidificador e bata por 1 minuto, até ficar bem liso.",
      "Despeje em copos gelados e sirva na hora, sem coar.",
    ],
    tips: [
      "Manga madura cede ao apertar leve e tem cheiro doce perto do cabinho.",
      "Congele a manga em cubos com antecedência: o smoothie fica mais grosso e gelado, sem precisar de gelo.",
    ],
    subs: [
      ["Leite", "Iogurte natural (mais denso) ou água de coco"],
      ["Mel", "Açúcar ou data hidratada"],
    ],
  },
  {
    id: "sanduiche-natural",
    t: "Sanduíche natural",
    d: "Pão de forma macio, frango desfiado e legumes. Lanche de graça de culpa.",
    cat: "Lanches",
    time: "10 min",
    serv: "2 sanduíches",
    diff: "Fácil",
    ing: [
      "4 fatias de pão de forma sem casca",
      "1/2 xícara de frango desfiado (pode ser resto de frango cozido)",
      "2 colheres (sopa) de maionese",
      "1/2 cenoura ralada fininha",
      "1 colher (sopa) de milho verde",
      "1 folha de alface picada",
      "Sal e pimenta a gosto",
    ],
    st: [
      "Misture o frango, a maionese, a cenoura, o milho, o sal e a pimenta em uma tigela.",
      "Espalhe a mistura em duas fatias de pão, cubra com a alface e feche com as outras fatias.",
      "Corte em triângulos e sirva — ou embrulhe em filme para levar.",
    ],
    tips: [
      "Se o recheio ficar molenga, escorra bem os ingredientes molhados e use maionese de colher, não de balde.",
      "O sanduíche natural fica melhor 'descansando' 10 minutos na geladeira embrulhado — o pão absorve a umidade certa.",
    ],
    subs: [
      ["Frango", "Atum escorrido ou presunto picado"],
      ["Maionese", "Cream cheese ou requeijão cremoso"],
      ["Pão de forma", "Pão francês amanhecido"],
    ],
  },
  {
    id: "sanduiche-atum",
    t: "Sanduíche de atum com cenoura",
    d: "Pronto em 5 minutos com o que tem na despensa.",
    cat: "Lanches",
    time: "5 min",
    serv: "2 sanduíches",
    diff: "Fácil",
    ing: [
      "1 lata de atum escorrido",
      "2 colheres (sopa) de maionese",
      "1/2 cenoura ralada",
      "1 colher (sopa) de cebola bem picada (opcional)",
      "4 fatias de pão de forma",
      "Sal e pimenta a gosto",
    ],
    st: [
      "Escorra muito bem o atum, apertando com um garfo para sair todo o óleo.",
      "Misture o atum, a maionese, a cenoura, a cebola, o sal e a pimenta.",
      "Monte os sanduíches e corte ao meio.",
    ],
    tips: [
      "Atum mal escorrido deixa o sanduíche encharcado — aperte de verdade com o garfo.",
      "Uma gota de limão na mistura dá vida ao sabor do atum.",
    ],
    subs: [
      ["Maionese", "Iogurte natural escorrido ou requeijão"],
      ["Cenoura", "Milho verde ou ervilha"],
      ["Pão de forma", "Pão integral ou baguete"],
    ],
  },
  {
    id: "bolinho-arroz",
    t: "Bolinho de arroz",
    d: "O destino do arroz de ontem. Dourado por fora, macio por dentro.",
    cat: "Lanches",
    time: "25 min",
    serv: "15 bolinhos",
    diff: "Fácil",
    ing: [
      "2 xícaras de arroz cozido (de véspera fica melhor)",
      "1 ovo",
      "1/4 de xícara de leite",
      "3 colheres (sopa) de farinha de trigo",
      "1/2 cebola bem picada",
      "2 colheres (sopa) de salsinha e cebolinha picadas",
      "Sal, pimenta e queijo ralado a gosto",
      "Óleo para fritar",
    ],
    st: [
      "Misture tudo em uma tigela até formar uma massa úmida que desgruda da mão.",
      "Aqueça o óleo em fogo médio: o bolinho deve borbulhar ao entrar.",
      "Molde bolinhas com uma colher (mão molhada ajuda a não grudar) e frite poucas por vez.",
      ["Frite por 3 a 4 minutos, virando para dourar por igual. Escorra em papel-toalha.", 240, "Óleo frio = bolinho encharcado. Óleo fumegando = queima por fora. Fogo médio é o ponto."],
    ],
    tips: [
      "Arroz quente gruda nas mãos e embola: use arroz frio, de preferência de véspera.",
      "Massa mole demais? Junte farinha aos poucos até firmar.",
      "Tire uma colherada, frite e prove o tempero antes de moldar tudo.",
    ],
    subs: [
      ["Fritura em óleo", "Air fryer a 200 °C por 15 minutos, virando na metade, pincelado com óleo"],
      ["Queijo ralado", "Queijo meia-cura ou muçarela em cubo no centro"],
      ["Farinha de trigo", "Farinha de rosca ou de mandioca"],
    ],
  },
  {
    id: "pipoca-panela",
    t: "Pipoca doce de panela",
    d: "A pipoca de caçarola do sítio, em 10 minutos.",
    cat: "Lanches",
    time: "10 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "1/2 xícara de milho de pipoca",
      "3 colheres (sopa) de óleo",
      "3 colheres (sopa) de açúcar",
      "1 pitada de sal",
    ],
    st: [
      "Coloque o óleo e 2 grãos de milho na panela tampada em fogo médio.",
      "Quando esses 2 grãos estourarem, desligue o fogo, despeje o milho restante com o açúcar e o sal, tampe e deixe 30 segundos fora do fogo.",
      ["Volte ao fogo médio e vá sacudindo a panela de vez em quando, entreaberta para sair o vapor, até os estouros espaçarem. Não abra para olhar!", 300, "Cada vez que abre a tampa, o calor escapa e grãos ficam sem estourar."],
      "Desligue e despeje em uma tigela grande, sacudindo para o açúcar distribuir.",
    ],
    tips: [
      "Panela larga estoura mais: pipoca amontoada queima antes de estourar tudo.",
      "Açúcar queima mais rápido que sal: fogo médio sempre, nunca alto.",
      "Quer salgado? Tire o açúcar e junte manteiga derretida com sal no final.",
    ],
    subs: [
      ["Açúcar", "Mel ou leite condensado derramado no final"],
      ["Óleo", "Manteiga (fica mais saborosa, mas queima mais fácil — fogo baixinho)"],
    ],
  },
  {
    id: "bolo-laranja",
    t: "Bolo de laranja",
    d: "Suco da fruta na massa e calda de açúcar por cima. Cheiro de fim de tarde.",
    cat: "Doces",
    time: "1h",
    serv: "12 fatias",
    diff: "Médio",
    ing: [
      "3 ovos",
      "2 xícaras de açúcar",
      "1/2 xícara de óleo",
      "Suco de 3 laranjas (cerca de 1 xícara)",
      "3 xícaras de farinha de trigo",
      "1 colher (sopa) de fermento em pó",
      "Raspas de 1 laranja (opcional)",
    ],
    st: [
      "Preaqueça o forno a 180 °C e unte uma forma de buraco no meio com manteiga e farinha.",
      "Bata no liquidificador ovos, açúcar, óleo e o suco por 2 minutos.",
      "Despeje em uma tigela e misture a farinha aos poucos, mexendo só até incorporar.",
      "Por último, junte o fermento e as raspas com movimentos leves.",
      ["Asse por 40 a 45 minutos. Faça o teste do palito: deve sair seco.", 2700],
      "Desenforme morno e regue com 1/2 xícara de suco misturado com 3 colheres de açúcar.",
    ],
    tips: [
      "Rale só a parte laranja da casca: o miolo branco (albedo) é amargo.",
      "Não abra o forno antes dos 30 minutos — bolo cai com corrente de ar frio.",
      "A massa tem que cair da colher em fita. Mole demais? Junte 2 colheres de farinha.",
    ],
    subs: [
      ["Suco de laranja", "Suco de tangerina ou de limão (metade da quantidade)"],
      ["Óleo", "Manteiga derretida (usar a mesma medida)"],
    ],
  },
  {
    id: "bolo-banana",
    t: "Bolo de banana",
    d: "Aproveita as bananas passadas que ninguém ia comer.",
    cat: "Doces",
    time: "55 min",
    serv: "10 fatias",
    diff: "Fácil",
    ing: [
      "4 bananas maduras amassadas",
      "2 ovos",
      "1/2 xícara de óleo",
      "1 e 1/2 xícara de açúcar",
      "2 xícaras de farinha de trigo",
      "1 colher (sopa) de fermento em pó",
      "1 colher (chá) de canela (opcional)",
    ],
    st: [
      "Preaqueça o forno a 180 °C e unte uma forma retangular.",
      "Amasse as bananas com um garfo em uma tigela grande.",
      "Misture ovos, óleo e açúcar até incorporar. Junte a canela.",
      "Adicione a farinha e, por fim, o fermento.",
      ["Asse por 35 a 40 minutos, até o palito sair seco.", 2400],
    ],
    tips: [
      "Banana quanta mais escura, mais doce fica o bolo — perfeitas são as que parecem 'passadas demais'.",
      "Decore com rodelas de banana e um fio de mel antes de assar.",
      "Banana mole demais a massa empapa: se estiver muito líquida, junte mais 2 colheres de farinha.",
    ],
    subs: [
      ["Açúcar", "Açúcar mascavo — fica mais caramelo"],
      ["Óleo", "Manteiga derretida"],
    ],
  },
  {
    id: "bolo-iogurte",
    t: "Bolo de iogurte (medida do pote)",
    d: "A receita que a gente mede tudo no pote de iogurte. Impossível errar.",
    cat: "Doces",
    time: "50 min",
    serv: "10 fatias",
    diff: "Fácil",
    ing: [
      "1 pote (170 g) de iogurte natural (guarde o pote para medir)",
      "2 potes de açúcar",
      "3 potes de farinha de trigo",
      "1/2 pote de óleo",
      "3 ovos",
      "1 colher (sopa) de fermento em pó",
      "1 colher (chá) de raspas de limão (opcional)",
    ],
    st: [
      "Preaqueça o forno a 180 °C e unte uma forma.",
      "Bata ovos, iogurte, açúcar e óleo com um garfo ou fouet por 2 minutos.",
      "Misture a farinha e, por último, o fermento e as raspas.",
      ["Asse por 35 a 40 minutos, até o palito sair seco.", 2400],
    ],
    tips: [
      "Use o pote do iogurte como medida para TUDO — é a regra da receita.",
      "Quer bolo de limão? Junte o suco de meio limão junto com as raspas.",
      "Massa bem misturada mas sem exagero: bolo de iogurte tolera mexer mais que o bolo de chocolate.",
    ],
    subs: [
      ["Iogurte natural", "Iogurte de coco ou leite + 1 colher de limão (para talhar)"],
      ["Óleo", "Manteiga derretida"],
    ],
  },
  {
    id: "beijinho",
    t: "Beijinho de coco",
    d: "O irmão do brigadeiro. Três ingredientes e muita festa junina.",
    cat: "Doces",
    time: "20 min",
    serv: "20 brigadeiros",
    diff: "Fácil",
    ing: [
      "1 lata de leite condensado (395 g)",
      "1 colher (sopa) de manteiga",
      "100 g de coco ralado (fresh ou seco)",
      "Açúcar cristal para enrolar",
      "Cravos-da-índia para decorar (opcional)",
    ],
    st: [
      "Coloque o leite condensado, a manteiga e o coco em uma panela em fogo médio-baixo.",
      ["Mexa sem parar por uns 10 minutos, até a massa desgrudar do fundo ao inclinar a panela.", 600, "Mesmo ponto do brigadeiro: você vê o fundo da panela por 2 segundos ao incliná-la."],
      "Despeje em um prato untado e deixe esfriar por completo.",
      "Unte as mãos com manteiga, enrole bolinhas e passe no açúcar cristal. Coroe cada um com um cravo.",
    ],
    tips: [
      "Coco seco hidrata um pouco na panela; se a massa ficar rala, cozinhe 2 minutos a mais.",
      "Se a massa grudar nas mãos mesmo untadas, espere mais: massa quente não enrola.",
    ],
    subs: [
      ["Coco ralado", "Coco em flocos grossos (textura mais rústica)"],
      ["Leite condensado", "Versão de leite condensado caseiro: 1 xícara de leite + 1/2 de açúcar, cozida"],
    ],
  },
  {
    id: "mousse-chocolate",
    t: "Mousse de chocolate",
    d: "Aerada, escura e feita no liquidificador. Só precisa de geladeira.",
    cat: "Doces",
    time: "15 min + geladeira",
    serv: "6 porções",
    diff: "Fácil",
    ing: [
      "200 g de chocolate meio amargo",
      "1 lata de creme de leite sem soro",
      "2 claras",
      "3 colheres (sopa) de açúcar",
      "Raspas de chocolate para decorar",
    ],
    st: [
      "Derreta o chocolate no micro-ondas em 30 em 30 segundos, mexendo entre cada pausa. Deixe amornar.",
      "Bata o chocolate com o creme de leite no liquidificador até homogeneizar.",
      "Em uma tigela limpa, bata as claras em neve com o açúcar, aos poucos, até firmar (uns 4 minutos na batedeira ou a braço com fouet).",
      "Incorpore as claras ao creme de chocolate com movimentos de baixo para cima, devagar.",
      ["Leve à geladeira por pelo menos 3 horas antes de servir.", 10800, "Incorporar com carinho é o que dá a textura de nuvem — não misture com força."],
    ],
    tips: [
      "Chocolate quente demais cozinha as claras e murcha o mousse: amorne até morno ao toque.",
      "Tigela e fouet limpos e sem gordura: clara não sobe com resíduo de óleo.",
      "Sem batedeira? Bata as claras com fouet fazendo círculos rápidos, 5 minutos de braço firme.",
    ],
    subs: [
      ["Chocolate meio amargo", "Ao leite (mais doce) ou 70% cacau (mais intenso)"],
      ["Creme de leite", "Nata ou 3 colheres de leite condensado (mais doce)"],
    ],
  },
  {
    id: "cookie-facil",
    t: "Cookies de chocolate",
    d: "Casquinha crocante, miolo macio. Saem 20 cookies de uma vez.",
    cat: "Doces",
    time: "35 min",
    serv: "20 cookies",
    diff: "Fácil",
    ing: [
      "150 g de manteiga em temperatura ambiente",
      "3/4 de xícara de açúcar mascavo",
      "1/2 xícara de açúcar",
      "1 ovo",
      "1 colher (chá) de essência de baunilha",
      "2 xícaras de farinha de trigo",
      "1/2 colher (chá) de bicarbonato de sódio",
      "1 pitada de sal",
      "150 g de gotas ou picados de chocolate",
    ],
    st: [
      "Preaqueça o forno a 180 °C e forre duas assadeiras com papel-manteiga.",
      "Bata a manteiga com os dois açúcares por 3 minutos, até ficar um creme claro.",
      "Junte o ovo e a baunilha e bata mais 1 minuto.",
      "Misture farinha, bicarbonato e sal, e incorpore na massa sem bater demais.",
      "Junte o chocolate e faça bolinhas do tamanho de uma colher (sopa), bem espaçadas — elas espalham.",
      ["Asse por 12 a 15 minutos, até as bordas dourarem. O centro ainda vai parecer mole.", 900, "Cookie endurece ao esfriar: tirar 'pouco assado' do forno é a regra."],
      "Espere 5 minutos na assadeira antes de passar para uma grade.",
    ],
    tips: [
      "Açúcar mascavo é o segredo da umidade e do sabor de caramelo.",
      "Massa gelada (30 minutos na geladeira) espalha menos e fica mais recheada.",
      "Congele bolinhas prontas: quando bater a vontade, asse direto do freezer somando 2 minutos.",
    ],
    subs: [
      ["Açúcar mascavo", "Açúcar refinado (cookie fica mais crocante, menos úmido)"],
      ["Manteiga", "Margarina com boa quantidade de gordura"],
      ["Chocolate", "Nozes, castanhas ou aveia"],
    ],
  },
  {
    id: "pudim-pao",
    t: "Pudim de pão",
    d: "Sobremesa de aproveitamento que parece sofisticada.",
    cat: "Doces",
    time: "1h15",
    serv: "8 fatias",
    diff: "Fácil",
    ing: [
      "4 pães velhos em cubos (ou 8 fatias)",
      "3 xícaras de leite",
      "1 lata de leite condensado",
      "3 ovos",
      "1 colher (chá) de essência de baunilha",
      "1 canela em pó a gosto",
      "1 xícara de açúcar para a calda",
    ],
    st: [
      "Faça a calda: derreta o açúcar em fogo médio até dourar, junte 1/2 xícara de água com cuidado (espirra!) e ferva até dissolver. Forre o fundo de uma forma e reserve.",
      "Misture o pão com o leite e deixe de molho por 10 minutos.",
      "Bata no liquidificador a mistura de pão com leite condensado, ovos, baunilha e uma pitada de canela.",
      "Despeje na forma caramelizada e cubra com papel-alumínio.",
      ["Asse em banho-maria a 180 °C por 50 minutos, até firmar ao toque.", 3000],
      "Espere esfriar e geladeira por 2 horas antes de desenformar.",
    ],
    tips: [
      "Banho-maria é a forma dentro de uma assadeira maior com água quente — garante a cremosidade.",
      "Pão duro é MELHOR que pão fresco: absorve mais o leite.",
      "Desenforme só frio: quente, o pudim desmonta.",
    ],
    subs: [
      ["Pão de forma", "Pão francês amanhecido ou biscoito champanhe"],
      ["Leite condensado", "1/2 xícara de açúcar no lugar"],
      ["Baunilha", "Raspas de limão"],
    ],
  },
  {
    id: "tilapia-empanada",
    t: "Tilápia empanada crocante",
    d: "Peixe empanado sem fritura profunda. Assa no forno e fica crocante.",
    cat: "Peixes",
    time: "35 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: [
      "2 filés de tilápia",
      "Suco de meio limão",
      "Sal, pimenta e páprica a gosto",
      "1/2 xícara de farinha de trigo",
      "1 ovo batido",
      "1 xícara de farinha panko (ou farinha de rosca)",
      "2 colheres (sopa) de azeite",
    ],
    st: [
      "Preaqueça o forno a 200 °C e unte uma assadeira com o azeite.",
      "Tempere os filés com limão, sal, pimenta e páprica. Deixe 10 minutos.",
      "Passe cada filé na farinha de trigo, depois no ovo batido e por fim no panko, pressionando bem para grudar.",
      ["Asse por 20 a 25 minutos, virando na metade, até dourar.", 1500, "Panko é mais crocante que farinha de rosca — vale procurar no mercado."],
      "Sirva com limão e arroz.",
    ],
    tips: [
      "Use uma mão para a farinha úmida e outra para a seca: nada de mãos de luva de farinha.",
      "Peixe pronto se desfaz em camadas com o garfo — se ele 'caçapa', já passou do ponto.",
    ],
    subs: [
      ["Tilápia", "Merluza, pescada ou filé de qualquer peixe branco"],
      ["Panko", "Farinha de rosca peneirada ou cornflakes esmagados"],
      ["Forno", "Air fryer a 200 °C por 12 minutos, virando na metade"],
    ],
  },
  {
    id: "isca-peixe",
    t: "Isca de peixe frita",
    d: "Tirinhas de peixe na massa de cerveja. Entrada de boteco em casa.",
    cat: "Peixes",
    time: "30 min",
    serv: "3 porções",
    diff: "Médio",
    ing: [
      "500 g de filé de peixe branco em tiras (tilápia, pescada ou merluza)",
      "Suco de 1 limão",
      "Sal e pimenta a gosto",
      "1 xícara de farinha de trigo",
      "1 colher (chá) de fermento em pó",
      "3/4 de xícara de cerveja bem gelada (ou água com gás)",
      "Óleo para fritar",
    ],
    st: [
      "Tempere as tiras de peixe com limão, sal e pimenta. Deixe 10 minutos na geladeira.",
      "Misture a farinha com o fermento e a cerveja gelada até formar um creme de panqueca grosso. Não mexa demais (grumos pequenos são bons).",
      "Aqueça o óleo a 180 °C: uma gota de massa deve subir borbulhando na hora.",
      "Passe as tiras na massa, deixe escorrer o excesso e frite poucas por vez.",
      ["Frite 3 a 4 minutos por leva, até dourar. Escorra em grade ou papel-toalha e salpique sal na hora.", 240, "Óleo na temperatura certa: massa que afunda = óleo frio, massa que queima = óleo quente demais."],
    ],
    tips: [
      "Cerveja gelada dá crocância: o gás faz bolhas na casquinha.",
      "Frite em levas pequenas — lotar o óleo derruba a temperatura e a isca fica encharcada.",
      "Sirva imediatamente: isca espera mal e amolece.",
    ],
    subs: [
      ["Cerveja", "Água com gás gelada + 1 colher de vinagre"],
      ["Peixe branco", "Camarão médio limpo"],
      ["Fritura", "Air fryer: pincele azeite e asse a 200 °C por 12 minutos"],
    ],
  },
  {
    id: "peixe-leite-coco",
    t: "Peixe no leite de coco",
    d: "Moqueca daeira sem esforço: tudo em uma frigideira e 20 minutos.",
    cat: "Peixes",
    time: "30 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: [
      "600 g de filé de peixe branco em postas ou pedaços",
      "Suco de 1 limão",
      "Sal e pimenta a gosto",
      "1 cebola em rodelas",
      "1 tomate em rodelas",
      "1 pimentão em tiras (opcional)",
      "1 lata de leite de coco (200 ml)",
      "2 colheres (sopa) de azeite de dendê (ou azeite comum)",
      "Coentro ou salsinha picada",
    ],
    st: [
      "Tempere o peixe com limão, sal e pimenta. Deixe marinar 10 minutos.",
      "Na frigideira, faça uma 'cama' com cebola, tomate e pimentão.",
      "Coloque o peixe por cima, despeje o leite de coco e regue com o dendê.",
      ["Tampe e cozinhe em fogo médio-baixo por 15 minutos, sem mexer — só sacuda a panela de vez em quando.", 900, "Mexer desmancha o peixe. Sacudir a panela mantém tudo intacto e cozido por igual."],
      "Prove o caldo, ajuste o sal e finalize com coentro. Sirva com arroz branco.",
    ],
    tips: [
      "Peixe cozinha rápido: 15 minutos resolve quase tudo; mais que isso desmancha.",
      "Quer mais picante? Junte 1 pimenta de cheiro ou pimenta biquinho na cama de vegetais.",
    ],
    subs: [
      ["Leite de coco", "Creme de leite + 1/2 limão (versão 'do norte' vira 'do sul')"],
      ["Dendê", "Azeite comum + 1 pitada de urucum (colorau) para a cor"],
      ["Peixe", "Camarão médio (cozinhe só 8 minutos)"],
    ],
  },
  {
    id: "salada-macarrao-fria",
    t: "Salada fria de macarrão",
    d: "Almoço de Tupperware que fica melhor no dia seguinte.",
    cat: "Saladas",
    time: "25 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "250 g de massa curta (parafuso ou penne)",
      "1 lata de atum escorrido (ou frango desfiado)",
      "1/2 xícara de milho verde",
      "1/2 xícara de ervilha",
      "1 tomate sem sementes picado",
      "1/2 cebola roxa fatiada fininha",
      "3 colheres (sopa) de azeite",
      "1 colher (sopa) de vinagre ou suco de limão",
      "Sal, pimenta e orégano a gosto",
    ],
    st: [
      "Cozinhe a massa al dente (1 minuto a menos que a embalagem), escorra e passe por água fria para parar o cozimento.",
      "Em uma tigela, misture azeite, vinagre, sal, pimenta e orégano para o molho.",
      "Junte a massa fria, o atum e todos os legumes. Misture bem e leve à geladeira por 30 minutos antes de servir.",
    ],
    tips: [
      "Massa fria absorve tempero: prove depois de gelada e corrija o sal.",
      "Sem sementes no tomate = salada que não solta água.",
      "Ótimo para marmita: faça na noite anterior e leve no dia seguinte.",
    ],
    subs: [
      ["Atum", "Frango desfiado, queijo em cubos ou nada (versão vegetariana)"],
      ["Massa", "Macarrão integral ou de arroz"],
      ["Maionese", "Junte 2 colheres para a versão cremosa"],
    ],
  },
  {
    id: "salada-batata",
    t: "Salada de batata com ervas",
    d: "Sem maionese, no azeite: leve, fresca e nem parece salada de batata.",
    cat: "Saladas",
    time: "30 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "4 batatas médias em cubos",
      "3 colheres (sopa) de azeite extra virgem",
      "1 colher (chá) de mostarda",
      "1/2 cebola roxa picadinha",
      "2 colheres (sopa) de salsinha picada",
      "Suco de meio limão",
      "Sal e pimenta a gosto",
    ],
    st: [
      "Cozinhe os cubos de batata em água com sal até ficarem macios mas inteiros (uns 12 minutos a partir da fervura).",
      ["Escorra e deixe esfriar por 10 minutos, destampada.", 600, "Batata quente absorve tempero; fria de geladeira não. Tempere morna, sirva fria."],
      "Misture azeite, mostarda, limão, sal e pimenta. Despeje sobre a batata.",
      "Junte cebola e salsinha, misture com carinho e sirva morna ou gelada.",
    ],
    tips: [
      "Cozinhe a batata começando na água fria: cozinha por dentro sem desmanchar.",
      "Teste com um palito: entra com leve resistência é o ponto. Macia demais vira purê.",
    ],
    subs: [
      ["Batata", "Batata-doce ou mandioquinha"],
      ["Mostarda", "Vinagre de vinho tinto"],
      ["Salsinha", "Cebolinha, dill ou hortelã"],
    ],
  },
  {
    id: "cenoura-refogada",
    t: "Cenoura refogada com alho",
    d: "O acompanhamento de 10 minutos que vai com absolutamente tudo.",
    cat: "Legumes",
    time: "12 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: [
      "3 cenouras em rodelas finas ou palitos",
      "2 dentes de alho picados",
      "1 colher (sopa) de azeite",
      "2 colheres (sopa) de água",
      "Sal, pimenta e salsinha a gosto",
    ],
    st: [
      "Aqueça o azeite em frigideira e refogue a cenoura por 5 minutos, mexendo de vez em quando.",
      ["Junte o alho, a água, a tampa e cozinhe por mais 4 minutos, até a cenoura ficar dente ao morder.", 240, "Água + tampa = vapor que termina de cozinhar sem queimar o alho."],
      "Tempere com sal, pimenta e finalize com salsinha.",
    ],
    tips: [
      "Corte uniforme = cozimento uniforme. Rodelas fininhas ficam prontas em minutos.",
      "Cenoura deve ter leve resistência ao morder — passa disso vira papa doce.",
      "Um fio de mel no final vira o acompanhamento preferido das crianças.",
    ],
    subs: [
      ["Cenoura", "Abobrinha, vagem ou brócolis (ajuste o tempo: brócolis 8 min, abobrinha 5 min)"],
      ["Azeite", "Manteiga — fica mais saborosa"],
    ],
  },
  {
    id: "pure-mandioca",
    t: "Purê de mandioca (macaxeira)",
    d: "Cremoso, puxa-puxa e o melhor amigo da carne assada.",
    cat: "Legumes",
    time: "45 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "700 g de mandioca em pedaços, sem casca e sem o fio do miolo",
      "Água para cozinhar e sal a gosto",
      "2 colheres (sopa) de manteiga",
      "1/2 xícara de leite quente",
      "Sal e pimenta a gosto",
    ],
    st: [
      "Cozinhe a mandioca em água fervente com sal por 25 a 30 minutos, até se desfazer ao espetar o garfo.",
      ["Escorra, retire o fio duro do miolo (se houver) e amasse com um garfo ou passe no espremedor.", null, "O fio do meio da mandioca é fibroso e duro: retire com uma faca antes de amassar."],
      "Volte à panela com a manteiga em fogo baixo e vá juntando o leite quente, mexendo, até ficar cremoso.",
      "Tempere com sal e pimenta e sirva.",
    ],
    tips: [
      "Mandioca bem cozida se desfaz sozinha: se o garfo entra com força, cozinhe mais 10 minutos.",
      "Leite quente evita que o purê esfrie e fique puxa-puxa demais.",
      "Versão nordestina: amasse com queijo coalho e manteiga da terra.",
    ],
    subs: [
      ["Mandioca", "Mandioquinha-salsa (cozinha em 20 minutos, mais leve)"],
      ["Leite", "Leite de coco — combina com peixe"],
      ["Manteiga", "Azeite + alho refogado"],
    ],
  },
  {
    id: "couve-flor-gratinada",
    t: "Couve-flor gratinada",
    d: "Queijo dourado em cima, couve-flor macia embaixo. Convertendo céticos desde sempre.",
    cat: "Legumes",
    time: "45 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "1 couve-flor média em buquês",
      "2 colheres (sopa) de manteiga",
      "2 colheres (sopa) de farinha de trigo",
      "2 xícaras de leite",
      "1 pitada de noz-moscada",
      "1/2 xícara de queijo muçarela ralado + 2 colheres de parmesão",
      "Sal e pimenta a gosto",
    ],
    st: [
      "Preaqueça o forno a 200 °C.",
      "Cozinhe os buquês em água fervente com sal por 6 minutos — devem ficar levemente macios, não desmanchando. Escorra bem.",
      "Molho bechamel: derreta a manteiga, junte a farinha e cozinhe 2 minutos mexendo, adicione o leite aos poucos mexendo sempre até engrossar. Tempere com sal, pimenta e noz-moscada.",
      "Misture a couve-flor no molho, coloque em um refratário e cubra com os queijos.",
      ["Asse por 20 minutos, até o queijo dourar e borbulhar.", 1200],
    ],
    tips: [
      "Cozinhe a menos: ela ainda vai ao forno. Couve-flor mole demais vira papa no gratinado.",
      "Um fio de azeite no queijo antes de assar deixa a casquinha dourada uniforme.",
    ],
    subs: [
      ["Couve-flor", "Brócolis ou abobrinha"],
      ["Bechamel", "Creme de leite + queijo cremoso"],
      ["Muçarela", "Queijo minas ou qualquer queijo que derreta"],
    ],
  },
  {
    id: "creme-milho",
    t: "Creme de milho",
    d: "Sopa cremosa de inverno que fica pronta em 20 minutos.",
    cat: "Sopas",
    time: "20 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "2 latas de milho verde escorrido (ou 2 xícaras de milho fresco)",
      "4 xícaras de água",
      "1 tablete de caldo de frango (ou legumes)",
      "1 cebola picada",
      "2 colheres (sopa) de manteiga",
      "1 colher (sopa) de amido de milho",
      "Sal e pimenta a gosto",
      "Salsinha e queijo ralado para servir",
    ],
    st: [
      "Refogue a cebola na manteiga até transparente. Junte o milho e refogue 2 minutos.",
      "Transfira metade para o liquidificador com 1 xícara da água, bata e volte à panela.",
      ["Junte a água restante com o caldo e o amido dissolvido em um pouco de água fria. Cozinhe em fogo médio mexendo até engrossar, uns 8 minutos.", 480],
      "Ajuste o sal e sirva com salsinha e queijo ralado.",
    ],
    tips: [
      "Bater só metade do milho dá textura de creme com 'blocos' de milho inteirinho — bem melhor.",
      "Quer creme mais aveludado? Finalize com 2 colheres de creme de leite fora do fogo.",
    ],
    subs: [
      ["Milho em lata", "Milho fresco ralado da espiga"],
      ["Caldo de frango", "Caldo de legumes para a versão vegetariana"],
      ["Manteiga", "Azeite"],
    ],
  },
  {
    id: "minestrone",
    t: "Minestrone simples",
    d: "Sopa italiana de legumes com macarrão. Um prato completo na tigela.",
    cat: "Sopas",
    time: "50 min",
    serv: "6 porções",
    diff: "Fácil",
    ing: [
      "2 cenouras em cubos",
      "2 batatas em cubos",
      "1 abobrinha em cubos",
      "1 xícara de feijão branco cozido (ou de lata, escorrido)",
      "1 lata de tomate pelado",
      "1 cebola e 2 dentes de alho picados",
      "1/2 xícara de macarrão pequeno (conchinha ou penne curto)",
      "6 xícaras de caldo de legumes",
      "3 colheres (sopa) de azeite",
      "Sal, pimenta, orégano e folhas de manjericão",
      "Queijo parmesão para servir",
    ],
    st: [
      "Refogue cebola e alho no azeite até dourar levemente.",
      "Junte cenoura e batata, refogue 3 minutos.",
      ["Adicione o tomate pelado (amasse com a colher), o caldo e cozinhe por 25 minutos, até os legumes ficarem macios.", 1500],
      "Junte a abobrinha, o feijão branco e o macarrão. Cozinhe por mais 10 minutos.",
      ["Tempere, finalize com manjericão e sirva com parmesão.", 600, "Macarrão cozido na sopa bebe caldo: deixe a sopa mais rala do que o ponto final desejado."],
    ],
    tips: [
      "Minestrone não tem regra rígida: use o que tiver na geladeira, respeitando tempos (raízes primeiro, folhas no final).",
      "Se for sobrar para o dia seguinte, cozinhe o macarrão à parte e junte na hora de servir — ele incha na sopa que fica guardada.",
    ],
    subs: [
      ["Feijão branco", "Grão-de-bico ou feijão carioca"],
      ["Caldo de legumes", "Água + 2 tabletes de caldo"],
      ["Macarrão", "Arroz ou quinoa (cozinhe 15 minutos)"],
    ],
  },
  {
    id: "tutu-feijao",
    t: "Tutu de feijão",
    d: "Feijão engrossado com farinha, mineiro de raiz. Com torresmo, é festa.",
    cat: "Arroz e feijão",
    time: "30 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "3 xícaras de feijão carioca cozido COM o caldo",
      "1 cebola picada",
      "3 dentes de alho",
      "2 colheres (sopa) de óleo",
      "3/4 de xícara de farinha de mandioca (ou fubá mimoso)",
      "Sal e pimenta a gosto",
      "Salsinha, ovo cozido e bacon frito para servir",
    ],
    st: [
      "Bata metade do feijão com o caldo no liquidificador até virar um creme liso.",
      "Refogue a cebola e o alho no óleo até dourar.",
      "Junte o feijão inteiro, o creme batido e cozinhe em fogo médio por 10 minutos.",
      ["Vá polvilhando a farinha aos poucos, mexendo sempre, até engrossar ao ponto de 'virar de colher' — uns 5 minutos.", 300, "Farinha de uma vez só forma pelotas. Polvilhe como quem pega neve, mexendo sem parar."],
      "Ajuste o sal e sirva com salsinha, ovo cozido e bacon por cima.",
    ],
    tips: [
      "O ponto certo é quando a colher de pau fica de pé no meio da panela (ou quase).",
      "Fubá mimoso dá textura mais lisa; farinha de mandioca dá o rústico tradicional.",
    ],
    subs: [
      ["Feijão carioca", "Feijão preto (versão paulista)"],
      ["Farinha de mandioca", "Fubá mimoso ou farinha de milho"],
      ["Bacon", "Torresmo ou linguiça fritinha"],
    ],
  },
  {
    id: "fricasse-frango",
    t: "Fricassê de frango",
    d: "Frango cremoso coberto com purê e queijo dourado. Almoço de domingo sem esforço.",
    cat: "Aves",
    time: "50 min",
    serv: "5 porções",
    diff: "Fácil",
    ing: [
      "500 g de peito de frango em cubos",
      "1 cebola picada",
      "2 dentes de alho",
      "2 tomates sem pele picados (ou 1/2 lata de tomate pelado)",
      "1 lata de milho verde",
      "1 caixa de creme de leite",
      "1 xícara de água",
      "Sal, pimenta e cheiro-verde",
      "4 batatas grandes (para o purê)",
      "100 g de muçarela ralada",
    ],
    st: [
      "Cozinhe as batatas até ficarem macias e amasse com leite e manteiga para o purê. Reserve.",
      "Doure o frango temperado em uma panela por 8 minutos. Reserve.",
      ["Na mesma panela, refogue cebola e alho, junte o tomate e cozinhe 5 minutos.", 300],
      "Bata o milho com a água no liquidificador e despeje na panela com o creme de leite. Cozinhe 5 minutos até engrossar.",
      ["Volte o frango, cozinhe 10 minutos, ajuste o sal e finalize com cheiro-verde.", 600],
      "Despeje o frango em um refratário, cubra com o purê, depois com a muçarela.",
      ["Gratine no forno a 200 °C por 15 minutos, até dourar.", 900],
    ],
    tips: [
      "Monte com o frango quente e o purê morno: gratina mais rápido e uniforme.",
      "Quer uma versão sem purê? Cubra com batata palha na hora de servir — o 'fricassê de boteco'.",
    ],
    subs: [
      ["Creme de leite", "Requeijão cremoso (fica ainda mais cremoso)"],
      ["Batata", "Mandioca cozida amassada"],
      ["Peito de frango", "Sobras de frango assado desfiadas"],
    ],
  },
  {
    id: "escondidinho-frango",
    t: "Escondidinho de frango",
    d: "Frango cremoso 'escondido' debaixo do purê. Reconforto em forma de travessa.",
    cat: "Aves",
    time: "55 min",
    serv: "5 porções",
    diff: "Fácil",
    ing: [
      "500 g de peito de frango cozido e desfiado",
      "1 cebola picada",
      "2 dentes de alho",
      "2 tomates picados",
      "1/2 xícara de caldo de frango (ou da água do cozimento)",
      "2 colheres (sopa) de requeijão ou creme de leite",
      "Sal, pimenta e cheiro-verde",
      "1 kg de mandioca cozida (ou 5 batatas grandes)",
      "2 colheres (sopa) de manteiga e 1/2 xícara de leite (para o purê)",
      "50 g de queijo parmesão ralado",
    ],
    st: [
      "Cozinhe a mandioca em água com sal até desmanchar no garfo. Amasse com manteiga e leite quente para um purê firme. Reserve.",
      "Refogue cebola e alho, junte o tomate e cozinhe até virar molho, uns 5 minutos.",
      ["Junte o frango desfiado e o caldo, cozinhe 8 minutos até ficar cremoso. Finalize com requeijão, cheiro-verde, sal e pimenta.", 480],
      "Em um refratário, espalhe o frango e cubra com o purê, alisando com um garfo.",
      ["Polvilhe o parmesão e asse a 200 °C por 20 minutos, até dourar em cima.", 1200],
    ],
    tips: [
      "Frango desfiado na mão (ou com garfo) absorve o molho melhor que picado.",
      "Faça um risco com o garfo no purê antes do queijo: doura mais bonito.",
      "Monte no dia anterior e leve ao forno na hora — escondidinho é ótimo para receber gente.",
    ],
    subs: [
      ["Mandioca", "Batata ou abóbora cabotiá assada"],
      ["Frango", "Carne-seca dessalgada ou carne moída"],
      ["Requeijão", "Creme de leite"],
    ],
  },
]);
