import { makeAll, type RawRecipe } from "./recipe-types";

const raw: RawRecipe[] = [
  {
    id: "ovo-frito-perfeito",
    t: "Ovo frito perfeito",
    d: "Clara firme, gema mole e sem queimar a borda.",
    cat: "Café da manhã",
    time: "5 min",
    serv: "1 porção",
    diff: "Fácil",
    ing: ["2 ovos", "1 colher (chá) de óleo ou manteiga", "Sal", "Pimenta-do-reino"],
    st: [
      ["Aqueça a frigideira em fogo médio-baixo por 2 minutos com o óleo.", 120, "Fogo alto queima a borda antes da clara cozinhar."],
      "Quebre o ovo em uma xícara e escorregue na frigideira — assim a gema não estoura.",
      ["Cozinhe por 3 minutos. Para a gema selada, tampe a panela nos últimos 40 segundos.", 180],
      "Tempere só no final, com sal e pimenta.",
    ],
    tips: ["Sal antes da hora deixa manchinhas brancas na gema.", "Manteiga dá mais sabor, óleo aguenta mais calor."],
    subs: [["Manteiga", "Azeite ou óleo comum."], ["Frigideira antiaderente", "Qualquer frigideira bem aquecida com um pouco mais de gordura."]],
  },
  {
    id: "omelete-simples",
    t: "Omelete simples",
    d: "Três ovos, uma frigideira e cinco minutos.",
    cat: "Café da manhã",
    time: "8 min",
    serv: "1 porção",
    diff: "Fácil",
    ing: ["3 ovos", "1 colher (sopa) de água", "Sal e pimenta", "Queijo ralado ou fatiado", "1 colher (chá) de manteiga"],
    st: [
      "Bata os ovos com a água, sal e pimenta até ficar homogêneo.",
      ["Derreta a manteiga em fogo médio-baixo e despeje os ovos.", 60],
      ["Puxe as bordas para o centro com a espátula até quase firmar, cerca de 3 minutos.", 180, "O centro deve ficar levemente úmido — ele termina de cozinhar fora do fogo."],
      "Coloque o recheio de um lado, dobre ao meio e sirva.",
    ],
    tips: ["Água (não leite) deixa a omelete mais leve.", "Frigideira pequena = omelete alta e macia."],
    subs: [["Queijo", "Presunto, tomate picado ou cebolinha."], ["Manteiga", "Azeite."]],
  },
  {
    id: "panqueca-americana",
    t: "Panqueca americana",
    d: "Fofinha, com mel ou geleia por cima.",
    cat: "Café da manhã",
    time: "20 min",
    serv: "8 panquecas",
    diff: "Fácil",
    ing: ["1 xícara de farinha de trigo", "1 colher (sopa) de açúcar", "1 colher (chá) de fermento em pó", "1 ovo", "3/4 xícara de leite", "2 colheres (sopa) de manteiga derretida", "Pitada de sal"],
    st: [
      "Misture os secos em uma tigela e os líquidos em outra.",
      ["Junte os dois e mexa só até sumir a farinha seca — grumos são bem-vindos.", null, "Bater demais deixa a panqueca borrachuda."],
      ["Deixe a massa descansar 10 minutos.", 600],
      ["Frite conchas da massa em fogo médio-baixo até surgirem bolhas na superfície, 2 a 3 minutos.", 150],
      ["Vire e doure o outro lado por 1 a 2 minutos.", 90],
    ],
    tips: ["Frigideira quente demais queima por fora e deixa cru dentro.", "Só unte na primeira panqueca."],
    subs: [["Leite", "Leite vegetal ou água com 1 colher de iogurte."], ["Manteiga", "Óleo neutro."]],
  },
  {
    id: "panqueca-brasileira",
    t: "Panqueca de carne moída",
    d: "Massa fina recheada e coberta com molho de tomate.",
    cat: "Café da manhã",
    time: "40 min",
    serv: "4 porções",
    diff: "Médio",
    ing: ["1 xícara de leite", "1 xícara de farinha de trigo", "2 ovos", "1 colher (sopa) de óleo", "300 g de carne moída refogada", "1 xícara de molho de tomate", "Sal"],
    st: [
      "Bata leite, farinha, ovos, óleo e sal no liquidificador até ficar liso.",
      ["Descanse a massa por 15 minutos.", 900, "O descanso hidrata a farinha e evita massa que rasga."],
      ["Faça discos finos em frigideira antiaderente, 1 minuto de cada lado.", 60],
      "Recheie com a carne, enrole e coloque em um refratário.",
      ["Cubra com molho e leve ao forno a 180 °C por 15 minutos.", 900],
    ],
    tips: ["Massa muito grossa? Junte leite, colher a colher.", "Faça os discos com antecedência: eles congelam bem separados por papel-manteiga."],
    subs: [["Carne moída", "Frango desfiado, queijo com presunto ou legumes refogados."], ["Molho pronto", "Tomate pelado amassado com alho e azeite."]],
  },
  {
    id: "tapioca-recheada",
    t: "Tapioca recheada",
    d: "Pronta em 5 minutos, sem glúten.",
    cat: "Café da manhã",
    time: "6 min",
    serv: "1 porção",
    diff: "Fácil",
    ing: ["4 colheres (sopa) de goma de tapioca hidratada", "Queijo coalho ou muçarela", "Sal", "Recheio a gosto"],
    st: [
      ["Passe a goma por uma peneira para desmanchar os grumos.", null, "Peneirar é o segredo da tapioca lisa, sem bolinhas duras."],
      ["Espalhe na frigideira quente (sem óleo) e espere firmar, cerca de 1 minuto.", 60],
      "Coloque o recheio, dobre ao meio e aqueça mais 1 minuto de cada lado.",
    ],
    tips: ["Frigideira antiaderente bem quente e seca — óleo estraga a textura.", "Camada fina une melhor do que camada grossa."],
    subs: [["Queijo coalho", "Muçarela, requeijão ou banana com canela."], ["Goma hidratada", "Goma seca umedecida com 1 colher de água e peneirada."]],
  },
  {
    id: "crepioca",
    t: "Crepioca de queijo",
    d: "Ovo + tapioca: café da manhã proteico em 6 minutos.",
    cat: "Café da manhã",
    time: "6 min",
    serv: "1 porção",
    diff: "Fácil",
    ing: ["1 ovo", "2 colheres (sopa) de goma de tapioca", "1 colher (sopa) de queijo ralado", "Sal e orégano"],
    st: [
      "Misture tudo com um garfo até homogeneizar.",
      ["Despeje na frigideira antiaderente em fogo médio e cozinhe 2 minutos.", 120],
      ["Vire e doure mais 1 minuto.", 60],
    ],
    tips: ["Se grudar, a frigideira estava fria demais na hora de despejar.", "1 colher de água deixa a massa mais macia."],
    subs: [["Queijo ralado", "Requeijão ou cottage."], ["Goma de tapioca", "1 colher de aveia fina."]],
  },
  {
    id: "pao-na-chapa",
    t: "Pão na chapa na manteiga",
    d: "O clássico de padaria feito em casa.",
    cat: "Café da manhã",
    time: "6 min",
    serv: "1 porção",
    diff: "Fácil",
    ing: ["1 pão francês", "1 colher (sopa) de manteiga", "Pitada de sal"],
    st: [
      "Corte o pão ao meio no sentido do comprimento.",
      "Passe manteiga generosa nos dois lados cortados.",
      ["Aperte contra a frigideira quente em fogo médio por 2 a 3 minutos até dourar.", 150, "Aperte com uma espátula: o contato total é o que cria a crosta."],
    ],
    tips: ["Pão de véspera fica ainda melhor na chapa.", "Fogo médio: alto queima a manteiga e amarga."],
    subs: [["Manteiga", "Requeijão ou azeite com alho."], ["Pão francês", "Pão de forma, ciabatta ou baguete."]],
  },
  {
    id: "misto-quente",
    t: "Misto quente",
    d: "Queijo derretido entre duas fatias douradas.",
    cat: "Lanches",
    time: "8 min",
    serv: "1 porção",
    diff: "Fácil",
    ing: ["2 fatias de pão de forma", "2 fatias de queijo muçarela", "2 fatias de presunto", "Manteiga"],
    st: [
      "Monte o sanduíche e passe manteiga na parte de fora das duas fatias.",
      ["Leve à frigideira em fogo baixo, com peso por cima, por 3 minutos.", 180, "Fogo baixo é obrigatório: o queijo precisa de tempo para derreter."],
      ["Vire e doure o outro lado por mais 3 minutos.", 180],
    ],
    tips: ["Queijo ralado derrete mais rápido que fatiado.", "Uma panela menor por cima serve de prensa."],
    subs: [["Presunto", "Peito de peru, frango desfiado ou tomate."], ["Pão de forma", "Pão francês aberto."]],
  },
  {
    id: "sanduiche-frango",
    t: "Sanduíche de frango cremoso",
    d: "Sobra de frango vira lanche em 10 minutos.",
    cat: "Lanches",
    time: "10 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: ["1 xícara de frango cozido desfiado", "3 colheres (sopa) de requeijão ou maionese", "1 cenoura ralada", "Cheiro-verde", "Sal e pimenta", "4 fatias de pão"],
    st: [
      "Misture frango, requeijão, cenoura e temperos.",
      ["Prove e ajuste o sal — recheio frio precisa de mais tempero.", null, "Sempre prove recheios frios antes de montar."],
      "Recheie os pães e sirva, ou toste rapidamente na frigideira.",
    ],
    tips: ["Frango de panela de pressão desfia sozinho ainda quente.", "Um fio de limão realça tudo."],
    subs: [["Requeijão", "Iogurte natural grego ou creme de ricota."], ["Cenoura", "Milho, azeitona ou maçã picada."]],
  },
  {
    id: "torrada-abacate",
    t: "Torrada com abacate",
    d: "Café da manhã moderno em 7 minutos.",
    cat: "Café da manhã",
    time: "7 min",
    serv: "1 porção",
    diff: "Fácil",
    ing: ["2 fatias de pão integral", "1/2 abacate maduro", "Suco de 1/2 limão", "Azeite", "Sal e pimenta"],
    st: [
      ["Toste o pão até ficar firme e dourado, 3 minutos.", 180],
      "Amasse o abacate com limão, sal e pimenta.",
      ["Espalhe no pão e finalize com azeite.", null, "Limão além de temperar impede o abacate de escurecer."],
    ],
    tips: ["Abacate maduro cede à pressão do dedo sem afundar.", "Ovo pochê ou frito por cima transforma em refeição."],
    subs: [["Abacate", "Guacamole pronto ou pasta de grão-de-bico."], ["Pão integral", "Qualquer pão tostado."]],
  },
  {
    id: "vitamina-banana",
    t: "Vitamina de banana",
    d: "Três ingredientes, dois minutos.",
    cat: "Bebidas",
    time: "3 min",
    serv: "1 copo grande",
    diff: "Fácil",
    ing: ["1 banana", "1 copo de leite", "1 colher (sopa) de aveia", "Mel a gosto", "Canela"],
    st: ["Bata tudo no liquidificador por 40 segundos.", "Prove e ajuste o mel.", "Sirva na hora, com canela por cima."],
    tips: ["Banana congelada em rodelas deixa a vitamina cremosa sem gelo.", "Aveia dá corpo e sacia mais."],
    subs: [["Leite", "Leite vegetal, água de coco ou iogurte batido com água."], ["Mel", "Açúcar, tâmara ou nada, se a banana estiver bem madura."]],
  },
  {
    id: "cafe-coado",
    t: "Café coado bem tirado",
    d: "Proporção, temperatura e paciência.",
    cat: "Bebidas",
    time: "8 min",
    serv: "2 xícaras",
    diff: "Fácil",
    ing: ["24 g de café moído (4 colheres de sopa)", "400 ml de água", "Filtro de papel"],
    st: [
      ["Ferva a água e espere 40 segundos fora do fogo.", 40, "Água fervendo queima o pó e amarga o café."],
      "Escalde o filtro com um pouco de água quente e descarte essa água.",
      ["Molhe todo o pó com 60 ml e espere 30 segundos (pré-infusão).", 30],
      ["Despeje o restante em movimentos circulares, em 2 minutos.", 120],
    ],
    tips: ["Proporção base: 60 g de pó por litro.", "Café amargo = moagem fina demais ou água quente demais."],
    subs: [["Filtro de papel", "Coador de pano bem limpo."], ["Balança", "1 colher de sopa cheia ≈ 6 g de pó."]],
  },
  {
    id: "cuscuz-nordestino",
    t: "Cuscuz nordestino",
    d: "Flocão, água e sal: café da manhã do Nordeste.",
    cat: "Café da manhã",
    time: "15 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: ["1 xícara de flocão de milho", "1/2 xícara de água", "1/2 colher (chá) de sal", "Manteiga para servir"],
    st: [
      "Misture o flocão com o sal e vá borrifando a água até a farinha ficar úmida e soltinha.",
      ["Descanse 10 minutos para hidratar.", 600, "Se apertar na mão e o punhado se manter, o ponto está certo."],
      ["Coloque na cuscuzeira e cozinhe no vapor por 8 minutos após a fervura.", 480],
      "Desenforme e passe manteiga por cima.",
    ],
    tips: ["Água demais vira massa empelotada; vá pouco a pouco.", "Sem cuscuzeira, use uma peneira sobre panela com água e tampe."],
    subs: [["Manteiga", "Leite de coco, ovo frito ou carne de sol."], ["Cuscuzeira", "Peneira de metal + panela + tampa."]],
  },
  {
    id: "mingau-aveia",
    t: "Mingau de aveia",
    d: "Quentinho, barato e pronto em 8 minutos.",
    cat: "Café da manhã",
    time: "8 min",
    serv: "1 porção",
    diff: "Fácil",
    ing: ["1/2 xícara de aveia em flocos", "1 xícara de leite", "1 colher (sopa) de açúcar ou mel", "Pitada de sal", "Canela"],
    st: [
      "Leve leite, aveia e sal ao fogo médio.",
      ["Cozinhe mexendo sempre por 5 minutos até engrossar.", 300, "Mexer sempre evita que grude e empelote."],
      "Desligue, adoce e polvilhe canela.",
    ],
    tips: ["Ele engrossa mais fora do fogo — desligue um pouco antes do ponto ideal.", "Pitada de sal realça o doce."],
    subs: [["Leite", "Água, leite vegetal ou metade e metade."], ["Aveia em flocos", "Flocão de milho ou farinha de aveia (menos tempo)."]],
  },
  {
    id: "pao-de-queijo",
    t: "Pão de queijo caseiro",
    d: "Crocante fora, elástico dentro.",
    cat: "Lanches",
    time: "45 min",
    serv: "20 unidades",
    diff: "Médio",
    ing: ["500 g de polvilho azedo", "1 xícara de leite", "1/2 xícara de óleo", "2 ovos", "200 g de queijo meia-cura ralado", "1 colher (chá) de sal"],
    st: [
      ["Ferva leite, óleo e sal e despeje sobre o polvilho, mexendo com colher.", null, "Escaldar o polvilho é o que dá a elasticidade típica."],
      ["Espere amornar por 10 minutos.", 600],
      "Junte os ovos um a um e sove até a massa ficar lisa; acrescente o queijo.",
      "Faça bolinhas e distribua na assadeira com espaço entre elas.",
      ["Asse a 180 °C por 25 minutos, até dourar.", 1500],
    ],
    tips: ["Massa mole? Junte polvilho aos poucos. Massa dura? Um pouco de leite.", "Congele cru: asse direto do congelador com 5 minutos a mais."],
    subs: [["Polvilho azedo", "Metade azedo e metade doce, para menos acidez."], ["Queijo meia-cura", "Parmesão + muçarela."]],
  },
  {
    id: "bolinho-chuva",
    t: "Bolinho de chuva",
    d: "Massa rápida frita, açúcar e canela.",
    cat: "Doces",
    time: "25 min",
    serv: "20 bolinhos",
    diff: "Fácil",
    ing: ["2 ovos", "1 xícara de leite", "2 xícaras de farinha", "3 colheres (sopa) de açúcar", "1 colher (sopa) de fermento em pó", "Óleo para fritar", "Açúcar e canela"],
    st: [
      "Bata ovos, leite e açúcar; junte a farinha e o fermento até virar massa grossa de colher.",
      ["Aqueça o óleo a fogo médio — teste com um pingo de massa: deve subir borbulhando em 3 segundos.", null, "Óleo frio encharca, óleo muito quente queima por fora e deixa cru dentro."],
      ["Frite às colheradas até dourar dos dois lados, 3 minutos.", 180],
      "Escorra em papel e passe no açúcar com canela ainda quente.",
    ],
    tips: ["Não frite muitos de uma vez: derruba a temperatura do óleo.", "Massa muito líquida espalha; deve cair pesada da colher."],
    subs: [["Leite", "Água ou leite vegetal."], ["Fermento em pó", "1/2 colher de bicarbonato + 1 de limão."]],
  },
  {
    id: "bolo-caneca",
    t: "Bolo de caneca de chocolate",
    d: "Sobremesa individual em 5 minutos de micro-ondas.",
    cat: "Doces",
    time: "5 min",
    serv: "1 porção",
    diff: "Fácil",
    ing: ["4 colheres (sopa) de farinha", "3 colheres (sopa) de açúcar", "2 colheres (sopa) de chocolate em pó", "1 ovo", "3 colheres (sopa) de leite", "2 colheres (sopa) de óleo", "1/2 colher (chá) de fermento"],
    st: [
      "Misture tudo na caneca com um garfo até não sobrar farinha seca.",
      ["Leve ao micro-ondas por 1 minuto e 40 segundos na potência máxima.", 100, "Cada micro-ondas é diferente: comece com 1min30 e vá somando 10 segundos."],
      "Espere 1 minuto antes de comer — o interior fica muito quente.",
    ],
    tips: ["Caneca cheia até no máximo 2/3, senão transborda.", "Passou do tempo? Fica borrachudo. Menos é mais."],
    subs: [["Chocolate em pó", "Cacau em pó (some 1 colher de açúcar)."], ["Óleo", "Manteiga derretida."]],
  },
  {
    id: "iogurte-granola",
    t: "Pote de iogurte com granola e frutas",
    d: "Montagem de 4 minutos, sem fogo.",
    cat: "Café da manhã",
    time: "4 min",
    serv: "1 porção",
    diff: "Fácil",
    ing: ["1 pote de iogurte natural", "3 colheres (sopa) de granola", "1 fruta picada", "1 colher (chá) de mel"],
    st: ["Coloque metade do iogurte no copo.", "Alterne camadas de fruta, granola e o resto do iogurte.", ["Coloque a granola de cima só na hora de comer.", null, "Granola misturada com antecedência murcha."]],
    tips: ["Iogurte natural sem açúcar + mel controla melhor o doce.", "Monte na véspera sem a granola para levar ao trabalho."],
    subs: [["Granola", "Aveia tostada na frigideira com mel."], ["Mel", "Melado, geleia ou banana amassada."]],
  },
  {
    id: "ovo-poche",
    t: "Ovo pochê",
    d: "Parece difícil, mas é só água, vinagre e 3 minutos.",
    cat: "Básico",
    time: "8 min",
    serv: "1 porção",
    diff: "Médio",
    ing: ["1 ovo bem fresco", "1 litro de água", "1 colher (sopa) de vinagre", "Sal"],
    st: [
      ["Aqueça a água até formar bolhas pequenas no fundo, sem ferver forte.", null, "Fervura forte despedaça a clara. Você quer água tremendo, não borbulhando."],
      "Junte o vinagre e faça um redemoinho com a colher.",
      "Quebre o ovo em uma xícara e deslize no centro do redemoinho.",
      ["Cozinhe 3 minutos para gema mole e retire com escumadeira.", 180],
    ],
    tips: ["Ovo velho espalha na água — use o mais fresco que tiver.", "Passar o ovo por uma peneira antes elimina a clara líquida solta."],
    subs: [["Vinagre", "Suco de limão."], ["Panela funda", "Frigideira alta com bastante água."]],
  },
  {
    id: "ovos-beneditinos",
    t: "Ovos beneditinos",
    d: "Ovo pochê, molho holandês e pão tostado.",
    cat: "Café da manhã",
    time: "30 min",
    serv: "2 porções",
    diff: "Difícil",
    ing: ["4 ovos para pochê", "2 gemas", "120 g de manteiga derretida morna", "1 colher (sopa) de suco de limão", "2 pães tipo muffin inglês", "4 fatias de bacon ou presunto", "Sal"],
    st: [
      ["Bata as gemas com o limão em banho-maria até clarear e engrossar levemente.", 180, "Água do banho-maria não pode ferver, senão a gema cozinha e talha."],
      ["Junte a manteiga morna em fio, batendo sem parar, até virar um creme liso.", 180],
      "Toste os pães e doure o bacon.",
      ["Faça os ovos pochê, 3 minutos cada.", 180],
      "Monte: pão, bacon, ovo e o molho por cima.",
    ],
    tips: ["Molho talhou? Bata 1 gema nova e junte o molho talhado em fio.", "Manteiga muito quente também talha — deve estar morna."],
    subs: [["Muffin inglês", "Pão francês ou brioche tostado."], ["Bacon", "Presunto, salmão defumado ou espinafre refogado."]],
  },
  {
    id: "waffle-caseiro",
    t: "Waffle caseiro",
    d: "Crocante por fora, macio por dentro.",
    cat: "Café da manhã",
    time: "25 min",
    serv: "4 waffles",
    diff: "Médio",
    ing: ["1 1/2 xícara de farinha", "2 colheres (sopa) de açúcar", "1 colher (sopa) de fermento", "2 ovos (claras separadas)", "1 1/4 xícara de leite", "1/3 xícara de manteiga derretida"],
    st: [
      "Misture os secos; à parte, gemas, leite e manteiga.",
      ["Bata as claras em neve e incorpore delicadamente à massa.", null, "As claras em neve são o que deixa o waffle leve."],
      ["Asse na máquina até parar de sair vapor, cerca de 4 minutos.", 240],
    ],
    tips: ["Não abra a máquina cedo demais — o waffle rasga.", "Sirva imediatamente: waffle empilhado murcha."],
    subs: [["Máquina de waffle", "A massa vira panqueca na frigideira."], ["Manteiga", "Óleo de coco ou óleo neutro."]],
  },
  {
    id: "smoothie-morango",
    t: "Smoothie de morango",
    d: "Gelado, cremoso e sem açúcar adicionado.",
    cat: "Bebidas",
    time: "4 min",
    serv: "2 copos",
    diff: "Fácil",
    ing: ["1 xícara de morangos congelados", "1 banana congelada", "1/2 xícara de iogurte natural", "1/2 xícara de leite", "Mel opcional"],
    st: ["Coloque os líquidos primeiro no liquidificador, depois as frutas.", ["Bata por 1 minuto, parando para mexer se travar.", 60, "Líquido embaixo faz as lâminas pegarem — evita travar."], "Prove e adoce se precisar."],
    tips: ["Fruta congelada substitui gelo sem aguar a bebida.", "Ficou grosso demais? Junte leite de 2 em 2 colheres."],
    subs: [["Iogurte", "Leite vegetal ou polpa de fruta."], ["Morango", "Manga, açaí ou frutas vermelhas."]],
  },
  {
    id: "suco-verde",
    t: "Suco verde",
    d: "Couve, limão e maçã batidos na hora.",
    cat: "Bebidas",
    time: "5 min",
    serv: "2 copos",
    diff: "Fácil",
    ing: ["2 folhas de couve", "1 maçã", "Suco de 1 limão", "300 ml de água gelada", "Gengibre a gosto"],
    st: ["Lave bem a couve e retire o talo grosso.", ["Bata tudo por 1 minuto.", 60], ["Coe se preferir textura lisa e beba na hora.", null, "Sucos verdes oxidam rápido: perdem cor e sabor em 20 minutos."]],
    tips: ["Água gelada preserva a cor verde.", "Maçã equilibra o amargor da couve sem precisar de açúcar."],
    subs: [["Couve", "Espinafre ou rúcula."], ["Maçã", "Abacaxi ou pera."]],
  },
  {
    id: "pao-alho",
    t: "Pão de alho de churrasco",
    d: "Manteiga de alho gratinada no forno.",
    cat: "Lanches",
    time: "20 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: ["1 baguete ou pão italiano", "100 g de manteiga em ponto de pomada", "4 dentes de alho amassados", "Cheiro-verde picado", "Queijo ralado", "Sal"],
    st: [
      "Misture manteiga, alho, cheiro-verde e sal.",
      "Faça cortes no pão sem separar as fatias e recheie com a manteiga.",
      ["Embrulhe em papel-alumínio e asse a 200 °C por 10 minutos.", 600],
      ["Abra o papel, cubra com queijo e volte por 5 minutos para gratinar.", 300, "Abrir no fim é o que deixa a superfície crocante."],
    ],
    tips: ["Alho cru queima fácil — a manteiga o protege.", "Manteiga gelada não espalha: espere amolecer naturalmente."],
    subs: [["Manteiga", "Requeijão + azeite."], ["Baguete", "Pão francês ou pão de forma tostado."]],
  },
  {
    id: "coxinha-assada",
    t: "Coxinha de frango assada",
    d: "Sabor de festa, sem fritura.",
    cat: "Lanches",
    time: "1 h 10 min",
    serv: "18 unidades",
    diff: "Difícil",
    ing: ["500 ml de caldo de galinha", "2 xícaras de farinha de trigo", "2 colheres (sopa) de manteiga", "2 xícaras de frango cozido desfiado e temperado", "Requeijão", "1 ovo batido e farinha de rosca"],
    st: [
      ["Ferva o caldo com a manteiga e junte a farinha de uma vez, mexendo forte.", 180, "Jogar a farinha de uma vez só evita bolotas cruas."],
      ["Cozinhe a massa mexendo por 4 minutos até desgrudar do fundo.", 240],
      ["Sove morna na bancada até ficar lisa.", 300],
      "Abra porções na mão, recheie com frango e requeijão e modele.",
      "Passe no ovo e na farinha de rosca.",
      ["Asse a 200 °C por 25 minutos, virando na metade.", 1500],
    ],
    tips: ["Massa grudando? Unte as mãos com óleo em vez de somar farinha.", "Um fio de azeite por cima antes de assar ajuda a dourar."],
    subs: [["Caldo de galinha", "Água do cozimento do frango temperada."], ["Requeijão", "Catupiry, cream cheese ou nada."]],
  },
  {
    id: "esfiha-aberta",
    t: "Esfiha aberta de carne",
    d: "Massa macia com recheio suculento de limão.",
    cat: "Lanches",
    time: "2 h",
    serv: "16 unidades",
    diff: "Difícil",
    ing: ["500 g de farinha de trigo", "10 g de fermento biológico seco", "250 ml de leite morno", "50 ml de óleo", "1 colher (chá) de açúcar e sal", "400 g de carne moída", "2 tomates e 1 cebola picados", "Suco de 1 limão"],
    st: [
      ["Dissolva o fermento no leite morno com açúcar e espere espumar, 10 minutos.", 600, "Leite quente demais mata o fermento: morno é temperatura de dedo."],
      ["Junte farinha, óleo e sal; sove por 10 minutos até a massa ficar lisa.", 600],
      ["Deixe crescer coberta até dobrar de volume, cerca de 1 hora.", 3600],
      "Misture a carne crua com tomate, cebola, limão e sal; escorra o excesso de líquido.",
      "Abra discos, coloque o recheio e deixe descansar 15 minutos.",
      ["Asse a 220 °C por 15 minutos.", 900],
    ],
    tips: ["Recheio muito molhado encharca a massa — escorra bem.", "Forno bem quente assa rápido e mantém a esfiha macia."],
    subs: [["Carne moída", "Frango desfiado, queijo com tomate ou ricota com espinafre."], ["Fermento seco", "30 g de fermento fresco."]],
  },
  {
    id: "hamburguer-caseiro",
    t: "Hambúrguer caseiro suculento",
    d: "Carne, sal e uma frigideira bem quente.",
    cat: "Lanches",
    time: "20 min",
    serv: "2 porções",
    diff: "Médio",
    ing: ["400 g de patinho ou acém moído (20% gordura)", "Sal grosso e pimenta", "2 pães de hambúrguer", "Queijo cheddar", "Manteiga"],
    st: [
      ["Modele bolas de 200 g sem apertar demais.", null, "Carne apertada vira almôndega dura; molde com carinho."],
      "Tempere com sal só na hora de ir para a chapa.",
      ["Amasse a bola na frigideira muito quente e não mexa por 2 minutos.", 120],
      ["Vire, coloque o queijo e cozinhe mais 2 minutos.", 120],
      "Toste os pães na manteiga e monte.",
    ],
    tips: ["Carne magra demais (patinho puro) resseca — 20% de gordura é o ideal.", "Só vire uma vez: cada virada tira sabor da crosta."],
    subs: [["Cheddar", "Muçarela, prato ou queijo coalho."], ["Pão de hambúrguer", "Pão francês achatado."]],
  },
  {
    id: "batata-frita-crocante",
    t: "Batata frita crocante",
    d: "O segredo é fritar duas vezes.",
    cat: "Lanches",
    time: "40 min",
    serv: "3 porções",
    diff: "Médio",
    ing: ["1 kg de batata asterix ou monalisa", "Óleo para fritura", "Sal"],
    st: [
      ["Corte em bastões e deixe de molho em água gelada por 20 minutos.", 1200, "A água tira o amido — é o que garante a crocância."],
      "Seque muito bem com pano ou papel.",
      ["Primeira fritura: óleo morno (160 °C) por 6 minutos, só para cozinhar. Escorra.", 360],
      ["Segunda fritura: óleo quente (190 °C) por 3 minutos, até dourar.", 180],
      "Sal só depois de escorrer.",
    ],
    tips: ["Batata molhada faz o óleo espirrar e não doura.", "Deixe esfriar entre as duas frituras — 10 minutos bastam."],
    subs: [["Fritadeira", "Panela funda com 3 dedos de óleo."], ["Fritura", "Air fryer a 200 °C por 20 minutos, com azeite."]],
  },
];

export const daily1 = makeAll(raw);
