import { makeAll, type Recipe } from "./recipe-types";

// Receitas de almoço e jantar do dia a dia — pensadas para cozinheiros de primeira viagem.
export const daily5: Recipe[] = makeAll([
  {
    id: "arroz-a-grega",
    t: "Arroz à grega",
    d: "Arroz colorido com cenoura, milho e uva-passa. Parece chique, é fácil demais.",
    cat: "Arroz e feijão",
    time: "30 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "2 xícaras de arroz branco",
      "1 cenoura ralada no ralo grosso",
      "1/2 xícara de milho verde",
      "1/2 xícara de ervilha (pode ser congelada)",
      "1/3 de xícara de uva-passa (opcional)",
      "1/2 cebola picada",
      "2 dentes de alho",
      "3 colheres (sopa) de óleo",
      "Sal a gosto",
    ],
    st: [
      "Lave o arroz até a água sair quase limpa e escorra bem.",
      ["Refogue a cebola e o alho no óleo até dourar levemente.", 120],
      ["Junte o arroz e frite por 2 minutos, mexendo sem parar.", 120],
      "Adicione a cenoura, o milho e a ervilha. Cubra com 4 xícaras de água fervente e tempere com sal.",
      ["Cozinhe em fogo baixo, tampa entreaberta, por 18 minutos.", 1080],
      "Desligue, junte a uva-passa, tampe e deixe descansar 5 minutos. Solte com garfo.",
    ],
    tips: [
      "A uva-passa vai no final: se cozinhar junto, solta muita água e deixa o arroz adocicado demais.",
      "Água já fervente faz o arroz cozinhar por igual — nunca use água fria aqui.",
      "Resto de arroz à grega vira arroz de forno no dia seguinte: cubra com queijo e gratine.",
    ],
    subs: [
      ["Uva-passa", "Omita ou use milho extra — não estraga a receita"],
      ["Ervilha e milho", "Mix de legumes congelado, direto do freezer"],
      ["Cenoura ralada", "Cenoura em cubinhos bem pequenos"],
    ],
  },
  {
    id: "feijao-tropeiro",
    t: "Feijão tropeiro",
    d: "Feijão misturado com farinha, bacon e ovos. Comida de sustância que rende bastante.",
    cat: "Arroz e feijão",
    time: "40 min",
    serv: "6 porções",
    diff: "Médio",
    ing: [
      "3 xícaras de feijão carioca cozido e escorrido",
      "150g de bacon em cubos",
      "1 calabresa em rodelas (opcional)",
      "1 cebola picada",
      "3 dentes de alho",
      "2 ovos batidos",
      "1 e 1/2 xícara de farinha de mandioca",
      "1/2 xícara de couve fatiada fina",
      "Sal, pimenta-do-reino e salsinha",
    ],
    st: [
      ["Frite o bacon na própria gordura em fogo médio até ficar crocante, uns 8 minutos.", 480],
      "Junte a calabresa e frite mais 3 minutos. Adicione cebola e alho e refogue até dourar.",
      ["Empurre tudo para o lado da panela, coloque os ovos batidos e mexa até cozinhar, como uma mexida.", 120],
      "Adicione o feijão escorrido e misture bem.",
      "Junte a farinha aos poucos, mexendo sempre, até ficar úmido mas soltinho.",
      ["Finalize com a couve, misture por 2 minutos, tempere e salpique salsinha.", 120],
    ],
    tips: [
      "Escorra bem o feijão: caldo demais empapuça a farinha.",
      "Prove antes de salgar — bacon e calabresa já trazem sal.",
      "Farofa de panela gruda: mexa sem parar depois que a farinha entra.",
    ],
    subs: [
      ["Bacon", "Linguiça calabresa dobrada ou apenas mais calabresa"],
      ["Farinha de mandioca", "Farinha de milho flocada (textura muda um pouco)"],
      ["Couve", "Repolho fatiado fino"],
    ],
  },
  {
    id: "frango-cremoso-panela",
    t: "Frango cremoso de uma panela só",
    d: "Cubos de frango dourados com creme de leite. Almoço completo em 25 minutos.",
    cat: "Aves",
    time: "25 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: [
      "600g de peito de frango em cubos",
      "1 cebola picada",
      "2 dentes de alho",
      "1 caixa de creme de leite",
      "1 colher (sopa) de manteiga",
      "Sal, pimenta-do-reino e páprica a gosto",
      "Cheiro-verde para finalizar",
    ],
    st: [
      "Tempere os cubos de frango com sal, pimenta e páprica.",
      ["Doure o frango na manteiga quente, em fogo alto, 6 a 8 minutos, mexendo de vez em quando.", 420, "Não lotar a panela é o segredo: frango espremido cozinha no próprio suco em vez de dourar."],
      "Retire o frango, refogue a cebola e o alho na mesma panela.",
      ["Volte o frango, junte o creme de leite e cozinhe em fogo baixo por 5 minutos.", 300],
      "Ajuste o sal, finalize com cheiro-verde e sirva com arroz branco.",
    ],
    tips: [
      "Seque o frango com papel-toalha antes de temperar — superfície seca doura mais rápido.",
      "Creme de leite em fogo baixo: fervura forte pode talhar.",
      "Molho ralo demais? Deixe ferver 2 minutos a mais, destampado.",
    ],
    subs: [
      ["Creme de leite", "Requeijão cremoso ou iogurte natural (adicionado fora do fogo)"],
      ["Peito de frango", "Coxa desossada — fica mais suculenta"],
      ["Manteiga", "2 colheres de azeite"],
    ],
  },
  {
    id: "frango-com-batata-forno",
    t: "Frango com batatas de forno",
    d: "Coxas de frango assadas junto com batatas na mesma assadeira. Só suja uma travessa.",
    cat: "Aves",
    time: "1h10",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "1kg de coxa e sobrecoxa de frango",
      "800g de batata em cubos grandes",
      "1 cebola em pétalas",
      "4 dentes de alho amassados",
      "Suco de 1 limão",
      "3 colheres (sopa) de azeite",
      "1 colher (sopa) de sal",
      "1 colher (chá) de páprica",
      "Alecrim ou orégano a gosto",
    ],
    st: [
      ["Tempere o frango com limão, alho, sal, páprica e metade do azeite. Deixe marinar 20 minutos (ou já tempere de véspera).", 1200],
      "Preaqueça o forno a 200°C.",
      "Espalhe as batatas e a cebola na assadeira, regue com o resto do azeite e salpique sal.",
      ["Acomode o frango por cima das batatas, pele para cima, e asse 45 a 55 minutos.", 3000, "O suco do frango cai sobre as batatas — é isso que deixa tudo saboroso."],
      "Fure a parte mais grossa: se o suco sair transparente, está pronto. Deixe dourar mais 10 minutos se quiser a pele crocante.",
    ],
    tips: [
      "Batatas em cubos do mesmo tamanho cozinham por igual.",
      "Pele para cima + forno quente = pele crocante. Não vire o frango no meio.",
      "Se a pele já estiver dourada mas a batata crua, cubra o frango com papel-alumínio.",
    ],
    subs: [
      ["Coxa e sobrecoxa", "Peito com osso ou sobrecoxa desossada (reduza 15 min)"],
      ["Alecrim", "Orégano, tomilho ou só sal e alho"],
      ["Batata", "Mandioca em pedaços pré-cozidos"],
    ],
  },
  {
    id: "omelete-de-forno",
    t: "Omelete de forno",
    d: "Omelete fofinho que você não precisa virar. Bate tudo, despeja e o forno trabalha.",
    cat: "Básico",
    time: "35 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "6 ovos",
      "1/2 xícara de leite",
      "1 tomate em cubos",
      "1/2 cebola picada",
      "1/2 xícara de queijo ralado",
      "1 xícara de presunto picado (opcional)",
      "Sal, pimenta e salsinha",
      "Manteiga para untar",
    ],
    st: [
      "Preaqueça o forno a 180°C e unte um refratário médio com manteiga.",
      "Bata os ovos com o leite, o sal e a pimenta até espumar.",
      "Misture o tomate, a cebola, o presunto, o queijo e a salsinha.",
      ["Despeje no refratário e asse 25 a 30 minutos, até o centro ficar firme.", 1620, "Espete um palito no centro: se sair limpo, está pronto."],
      "Deixe descansar 5 minutos antes de cortar — firma e não despedaça.",
    ],
    tips: [
      "Omelete cresce no forno e murcha fora dele — normal, o sabor continua ótimo.",
      "Não abra o forno nos primeiros 20 minutos: o choque de ar murcha o omelete.",
      "Sirva com salada verde que vira jantar completo.",
    ],
    subs: [
      ["Leite", "Água — perde um pouco da cremosidade, mas funciona"],
      ["Presunto", "Frango desfiado, atum escorrido ou só legumes"],
      ["Refratário", "Frigideira que possa ir ao forno (cabo de metal)"],
    ],
  },
  {
    id: "espaguete-ao-pesto-caseiro",
    t: "Espaguete ao pesto de manjericão",
    d: "Molho verde feito no liquidificador em 5 minutos. Massa com cara de restaurante.",
    cat: "Massas",
    time: "20 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: [
      "300g de espaguete",
      "2 xícaras de folhas de manjericão",
      "1/3 de xícara de azeite",
      "1/4 de xícara de queijo parmesão ralado",
      "2 colheres (sopa) de nozes ou castanha-de-caju",
      "1 dente de alho",
      "Sal a gosto",
    ],
    st: [
      ["Cozinhe o espaguete em água bem salgada pelo tempo da embalagem. Reserve 1 xícara da água do cozimento.", 480],
      "No liquidificador, bata manjericão, azeite, parmesão, nozes, alho e uma pitada de sal até virar um molho verde.",
      "Escorra a massa e volte para a panela quente, fora do fogo.",
      ["Misture o pesto, adicionando a água do cozimento aos poucos até ficar cremoso.", 120, "A água com amido é o que faz o molho abraçar a massa."],
      "Sirva com mais parmesão por cima.",
    ],
    tips: [
      "Nunca aqueça o pesto em fogo alto: o manjericão escurece e amarga.",
      "Sem nozes? Amendoins torrados sem sal funcionam bem.",
      "Pesto escurecido na geladeira não estragou — é oxidação. Misture e use em 3 dias.",
    ],
    subs: [
      ["Nozes/castanhas", "Amendoim torrado ou omita (pesto genovês mais simples)"],
      ["Manjericão", "Rúcula + espinafre para um pesto diferente"],
      ["Parmesão", "Qualquer queijo curado ralado"],
    ],
  },
  {
    id: "strogonoff-carne",
    t: "Strogonoff de carne",
    d: "O clássico de panela com molho rosé cremoso. Mais fácil do que parece.",
    cat: "Carnes",
    time: "35 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "600g de alcatra ou patinho em tiras",
      "1 cebola picada",
      "2 dentes de alho",
      "3 colheres (sopa) de ketchup",
      "1 colher (sopa) de mostarda",
      "1 caixa de creme de leite",
      "1 colher (sopa) de manteiga",
      "Sal e pimenta-do-reino",
      "Champignon fatiado (opcional)",
    ],
    st: [
      "Tempere a carne com sal e pimenta.",
      ["Doure a carne na manteiga bem quente, em duas levas, 3 minutos cada. Reserve.", 360, "Duas levas evitam que a carne solte água e cozinhe em vez de dourar."],
      "Na mesma panela, refogue a cebola e o alho até dourar.",
      "Volte a carne, adicione ketchup, mostarda e champignon. Misture bem.",
      ["Junte o creme de leite e cozinhe em fogo baixo por 5 minutos, sem deixar ferver forte.", 300],
      "Ajuste o sal e sirva com arroz branco e batata palha.",
    ],
    tips: [
      "Creme de leite entra por último e nunca ferve em fogo alto — senão talha.",
      "Carne cortada contra a fibra fica macia até na panela rápida.",
      "Molho deve ficar rosado: se escurecer demais, é ketchup de menos ou fogo alto demais.",
    ],
    subs: [
      ["Alcatra", "Frango em cubos (strogonoff de frango) ou cogumelos para versão sem carne"],
      ["Creme de leite", "Iogurte natural adicionado fora do fogo"],
      ["Champignon", "Omita ou use milho verde"],
    ],
  },
  {
    id: "carne-moida-batata",
    t: "Refogado de carne moída com batata",
    d: "Comida de mãe: carne moída com batata macia no molho. Rende muito e congela bem.",
    cat: "Carnes",
    time: "40 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "500g de carne moída",
      "3 batatas médias em cubos",
      "1 cebola picada",
      "2 dentes de alho",
      "2 tomates maduros picados",
      "1/2 xícara de molho de tomate",
      "Sal, pimenta e colorau",
      "Cheiro-verde",
    ],
    st: [
      ["Doure a carne moída em fogo alto, mexendo para desmanchar, uns 8 minutos.", 480],
      "Junte cebola e alho e refogue até a cebola murchar.",
      "Adicione o tomate e o colorau e cozinhe 3 minutos até o tomate desmanchar.",
      ["Junte a batata, o molho de tomate e 1 xícara de água. Tampe e cozinhe 15 minutos em fogo baixo.", 900],
      ["Destampe, ajuste o sal e cozinhe mais 5 minutos para encorpar o molho.", 300],
      "Finalize com cheiro-verde e sirva com arroz.",
    ],
    tips: [
      "Tomate maduro é o que dá molho natural — não pule esse passo.",
      "Garfo entra fácil na batata? Está pronto. Batata dura pede mais 5 minutos e um gole de água.",
      "Essa receita congela muito bem: faça dobrado e guarde metade.",
    ],
    subs: [
      ["Carne moída", "Frango moído ou proteína de soja hidratada"],
      ["Batata", "Chuchu ou abobrinha (cozinha mais rápido)"],
      ["Molho de tomate", "1 colher de extrato de tomate + água"],
    ],
  },
  {
    id: "bife-de-frango-milanesa",
    t: "Frango à milanesa crocante",
    d: "Empanado dourado por fora, suculento por dentro. O truque é a farinha de rosca dupla.",
    cat: "Aves",
    time: "30 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: [
      "3 filés de peito de frango",
      "2 ovos batidos com uma pitada de sal",
      "1 xícara de farinha de trigo",
      "1 e 1/2 xícara de farinha de rosca",
      "Suco de 1/2 limão",
      "2 dentes de alho amassados",
      "Sal e pimenta-do-reino",
      "Óleo para fritar",
    ],
    st: [
      ["Tempere os filés com limão, alho, sal e pimenta. Deixe 10 minutos.", 600],
      "Monte três pratos: um com farinha de trigo, um com os ovos batidos, um com farinha de rosca.",
      "Passe cada filé na farinha de trigo, depois no ovo, depois na farinha de rosca, pressionando bem.",
      ["Aqueça óleo (1 dedo de altura) até um palito de fósforo aceso sozinho... brincadeira: até um farelo de farinha chiar na hora.", 300],
      ["Frite os filés 3 a 4 minutos de cada lado, até dourar bem.", 420, "Fogo médio-alto: óleo frio encharca, óleo quente demais queima por fora e fica cru por dentro."],
      "Escorra em papel-toalha e sirva com limão e arroz.",
    ],
    tips: [
      "Filé muito grosso? Corte ao meio no sentido da espessura ou bata levemente com um martelo de carne (ou uma panela pequena).",
      "Pressione bem a farinha de rosca — casquinha solta é farinha que não grudou.",
      "Frite no máximo 2 filés por vez para o óleo não esfriar.",
    ],
    subs: [
      ["Peito de frango", "Bife de carne (à milanesa clássico) ou filé de peixe"],
      ["Fritura", "Air fryer: 200°C por 12 min, virando na metade, com fio de óleo"],
      ["Farinha de rosca", "Pão amanhecido processado"],
    ],
  },
  {
    id: "sardinha-escabeche",
    t: "Sardinha fresca assada",
    d: "Peixe barato, cheio de ômega-3 e pronto em 20 minutos de forno.",
    cat: "Peixes",
    time: "30 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: [
      "600g de sardinhas limpas",
      "Suco de 1 limão",
      "3 dentes de alho amassados",
      "Sal e pimenta-do-reino",
      "2 colheres (sopa) de azeite",
      "1 cebola em rodelas",
      "Coentro ou salsinha",
    ],
    st: [
      "Lave bem as sardinhas e seque com papel-toalha.",
      ["Tempere com limão, alho, sal e pimenta. Deixe 15 minutos.", 900],
      "Preaqueça o forno a 220°C e forre uma assadeira com papel-alumínio.",
      "Acomode as sardinhas, cubra com rodelas de cebola e regue com azeite.",
      ["Asse 15 a 20 minutos, até a pele dourar e a carne soltar da espinha.", 1080],
      "Finalize com coentro e sirva com arroz e vinagrete.",
    ],
    tips: [
      "Peixe pronto: carne opaca e soltando da espinha com facilidade.",
      "Papel-alumínio na assadeira evita o cheiro grudado na travessa.",
      "Peça ao peixeiro para limpar as sardinhas — economiza 20 minutos de trabalho.",
    ],
    subs: [
      ["Sardinha fresca", "Petinga, manjuba ou filé de tilápia (menos tempo de forno)"],
      ["Forno", "Frigideira tampada em fogo médio, 6 min de cada lado"],
      ["Coentro", "Salsinha ou cebolinha"],
    ],
  },
  {
    id: "omelete-forno-legumes",
    t: "Fritada de legumes",
    d: "Omelete italiano com os legumes que estiverem sobrando na geladeira.",
    cat: "Legumes",
    time: "25 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: [
      "5 ovos",
      "1 abobrinha em rodelas finas",
      "1 batata pequena em rodelas finas",
      "1/2 cebola fatiada",
      "1/2 xícara de queijo ralado",
      "2 colheres (sopa) de azeite",
      "Sal e pimenta-do-reino",
    ],
    st: [
      ["Refogue a batata no azeite em fogo médio por 6 minutos.", 360],
      ["Junte a abobrinha e a cebola e cozinhe mais 5 minutos, até amolecer.", 300],
      "Bata os ovos com sal, pimenta e metade do queijo.",
      "Despeje os ovos sobre os legumes na frigideira, espalhando bem.",
      ["Cozinhe em fogo baixo, tampado, 8 a 10 minutos, até firmar.", 540],
      ["Salpique o resto do queijo, tampe mais 2 minutos para derreter e sirva.", 120],
    ],
    tips: [
      "Não tem tampa de frigideira? Uma assadeira ou prato grande por cima resolve.",
      "Frigideira antiaderente é sua melhor amiga aqui — fritada gruda fácil em inox.",
      "Aceita qualquer legume: cenoura ralada, brócolis cozido, tomate, milho.",
    ],
    subs: [
      ["Abobrinha e batata", "Qualquer legume da geladeira — é receita de aproveitamento"],
      ["Queijo ralado", "Queijo minas em cubos ou requeijão em colheradas"],
      ["Frigideira tampada", "Finalize no forno ou grill por 5 minutos"],
    ],
  },
  {
    id: "macarrao-panela-pressao",
    t: "Macarrão de panela de pressão",
    d: "Macarrão com molho cozido junto na pressão, em 15 minutos e uma panela só.",
    cat: "Massas",
    time: "15 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: [
      "300g de macarrão parafuso ou penne",
      "1 lata de molho de tomate",
      "1/2 cebola picada",
      "2 dentes de alho",
      "1/2 xícara de água",
      "Sal, orégano e azeite",
      "Queijo ralado para servir",
    ],
    st: [
      "Refogue a cebola e o alho no azeite dentro da panela de pressão aberta.",
      "Adicione o molho de tomate, a água, o sal e o orégano.",
      "Junte o macarrão cru e misture bem — a massa precisa ficar coberta pelo líquido.",
      ["Tampe a panela e cozinhe 5 minutos depois de pegar pressão.", 300, "Não passe do tempo: massa na pressão vira mingau se cozinhar demais."],
      "Tire a pressão, abra com cuidado e mexa. Se estiver com muito líquido, ferva 2 minutos destampado.",
      "Sirva com bastante queijo ralado.",
    ],
    tips: [
      "A proporção importa: o macarrão precisa ficar submerso, senão cozinha torto.",
      "Espere a pressão sair sozinha por 2 minutos antes de abrir — o molho assenta.",
      "Dá para adicionar calabresa em rodelas ou frango desfiado junto com o molho.",
    ],
    subs: [
      ["Panela de pressão", "Panela comum: mesmo processo, 12 minutos mexendo de vez em quando"],
      ["Molho de tomate", "2 tomates maduros batidos no liquidificador + 1 colher de extrato"],
      ["Parafuso", "Qualquer massa curta — espaguete quebra e empapa"],
    ],
  },
  {
    id: "frango-molho-mostarda",
    t: "Frango ao molho de mostarda",
    d: "Filés dourados com molho cremoso de mostarda. Sofisticado com esforço mínimo.",
    cat: "Aves",
    time: "25 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: [
      "500g de filé de frango",
      "1 colher (sopa) de manteiga",
      "1 colher (sopa) de mostarda dijon (ou amarela)",
      "1 caixa de creme de leite",
      "1/2 cebola picada",
      "Sal e pimenta-do-reino",
      "Salsinha picada",
    ],
    st: [
      "Tempere os filés com sal e pimenta.",
      ["Doure na manteiga quente, 4 minutos de cada lado. Reserve.", 480],
      "Na mesma panela, refogue a cebola até murchar.",
      "Junte a mostarda e o creme de leite, raspando o fundo da panela para soltar os douradinhos.",
      ["Volte o frango ao molho e cozinhe 5 minutos em fogo baixo.", 300],
      "Salpique salsinha e sirva com arroz e batata.",
    ],
    tips: [
      "Os douradinhos do fundo da panela são sabor puro: raspe tudo quando o molho entrar.",
      "Mostarda amarela comum funciona — use um pouco mais, pois é mais suave.",
      "Molho engrossou demais? Um gole de leite resolve.",
    ],
    subs: [
      ["Mostarda dijon", "Mostarda amarela comum (dobre a quantidade)"],
      ["Creme de leite", "Requeijão cremoso"],
      ["Filé de frango", "Bife de porco ou alcatra fatiada"],
    ],
  },
  {
    id: "legumes-refogados-simples",
    t: "Legumes refogados na manteiga",
    d: "Cenoura, vagem e brócolis brilhantes e no ponto. O acompanhamento que resolve qualquer prato.",
    cat: "Legumes",
    time: "20 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "1 cenoura em palitos",
      "1 xícara de vagem cortada",
      "1/2 brócolis em floretes",
      "1 colher (sopa) de manteiga",
      "1 dente de alho fatiado",
      "Sal a gosto",
    ],
    st: [
      ["Cozinhe a cenoura e a vagem em água fervente com sal por 4 minutos.", 240],
      ["Junte o brócolis e cozinhe mais 3 minutos. Escorra bem.", 180, "Brócolis entra depois porque cozinha mais rápido — se entrar junto, desmancha."],
      ["Na frigideira, derreta a manteiga e doure o alho rapidamente, 30 segundos.", 30],
      ["Junte os legumes escorridos e refogue 2 minutos em fogo alto, mexendo.", 120],
      "Ajuste o sal e sirva na hora.",
    ],
    tips: [
      "Cozinhar antes e refogar depois = legume cozido por dentro e com gosto de manteiga por fora.",
      "Legume no ponto certo: macio, mas ainda com cor vibrante. Cinza e murcho = passou do ponto.",
      "Um fio de azeite no final realça o brilho e o sabor.",
    ],
    subs: [
      ["Cenoura, vagem e brócolis", "Qualquer mix: chuchu, abobrinha, couve-flor"],
      ["Manteiga", "Azeite"],
      ["Legumes frescos", "Mix congelado — pule o cozimento, refogue direto por 6 min"],
    ],
  },
  {
    id: "arroz-com-frango-panela",
    t: "Galinhada simples",
    d: "Arroz e frango cozidos juntos na mesma panela. Prato único que alimenta a família.",
    cat: "Arroz e feijão",
    time: "50 min",
    serv: "5 porções",
    diff: "Médio",
    ing: [
      "800g de frango em pedaços (coxa e sobrecoxa)",
      "2 xícaras de arroz",
      "1 cebola picada",
      "2 dentes de alho",
      "1 tomate picado",
      "1 colher (sopa) de colorau",
      "4 xícaras de água quente",
      "Sal, azeite e cheiro-verde",
    ],
    st: [
      "Tempere o frango com sal e alho.",
      ["Doure o frango no azeite quente, 5 minutos de cada lado. Reserve.", 600],
      "Na mesma panela, refogue a cebola e o tomate até desmanchar.",
      "Junte o colorau e o arroz e frite por 2 minutos, mexendo.",
      ["Volte o frango à panela, cubra com a água quente, ajuste o sal e cozinhe tampado em fogo baixo por 25 minutos.", 1500, "Não mexa depois que tampar — arroz mexido no cozimento fica empapado."],
      "Desligue, deixe descansar 5 minutos, solte com garfo e salpique cheiro-verde.",
    ],
    tips: [
      "Dourar o frango antes é o que dá gosto de galinhada — não pule.",
      "Água quente mantém a temperatura da panela e o cozimento uniforme.",
      "Sobras ficam ótimas requentadas com um fio de água no micro-ondas.",
    ],
    subs: [
      ["Frango em pedaços", "Peito em cubos (reduza 10 min) ou linguiça calabresa"],
      ["Colorau", "Açafrão-da-terra ou páprica"],
      ["Cheiro-verde", "Coentro, salsinha ou cebolinha"],
    ],
  },
  {
    id: "tilapia-manteiga-limao",
    t: "Tilápia na manteiga com limão",
    d: "Filé de peixe dourado com molho de manteiga e limão feito na mesma frigideira.",
    cat: "Peixes",
    time: "15 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: [
      "2 filés de tilápia",
      "Sal e pimenta-do-reino",
      "2 colheres (sopa) de farinha de trigo",
      "2 colheres (sopa) de manteiga",
      "Suco de 1 limão",
      "1 dente de alho fatiado",
      "Salsinha picada",
    ],
    st: [
      "Seque bem os filés, tempere com sal e pimenta e passe levemente na farinha.",
      ["Derreta metade da manteiga em fogo médio-alto e doure os filés, 3 minutos de cada lado.", 360, "Vire uma vez só: peixe virado várias vezes despedaça."],
      "Retire os filés para um prato.",
      ["Na mesma frigideira, derreta o resto da manteiga com o alho por 30 segundos.", 30],
      ["Junte o suco de limão e a salsinha, misture 1 minuto e despeje sobre o peixe.", 60],
    ],
    tips: [
      "Peixe seco antes de temperar é o segredo da casquinha dourada.",
      "A farinha é opcional, mas ajuda a segurar a umidade e dá cor.",
      "Molho de manteiga queima rápido: fogo baixo e olho na panela.",
    ],
    subs: [
      ["Tilápia", "Pescada, merluza ou filé de frango (mais 2 min por lado)"],
      ["Manteiga", "Azeite (muda o sabor, mas funciona)"],
      ["Limão", "Vinho branco seco — deixe evaporar 1 minuto a mais"],
    ],
  },
  {
    id: "batata-assada-recheada",
    t: "Batata assada recheada",
    d: "Batata inteira assada e recheada com frango cremoso. Jantar completo em si mesma.",
    cat: "Legumes",
    time: "1h",
    serv: "2 porções",
    diff: "Fácil",
    ing: [
      "2 batatas grandes (inglesas ou asterix)",
      "1 xícara de frango cozido e desfiado",
      "1/2 xícara de requeijão",
      "2 colheres (sopa) de queijo ralado",
      "Azeite, sal e pimenta",
      "Cheiro-verde",
    ],
    st: [
      "Lave as batatas, fure toda a superfície com um garfo, esfregue azeite e sal.",
      ["Asse a 200°C por 50 a 60 minutos, até o garfo entrar sem resistência.", 3300],
      ["Misture o frango com o requeijão, sal e pimenta.", 60],
      "Corte cada batata ao meio no sentido do comprimento e afrouxe a polpa com um garfo.",
      ["Recheie com o frango cremoso, cubra com queijo ralado e leve ao grill ou forno alto por 5 minutos.", 300],
      "Finalize com cheiro-verde.",
    ],
    tips: [
      "Batata grande e da mesma espessura cozinha por igual — escolha parecidas no mercado.",
      "Garfo entra como na manteiga? Está pronta. Resistência no centro pede mais 10 minutos.",
      "Sem grill? Fogo alto no forno por 5 minutos dá conta.",
    ],
    subs: [
      ["Frango desfiado", "Carne moída refogada, atum ou só requeijão com milho"],
      ["Requeijão", "Cream cheese ou maionese temperada"],
      ["Forno", "Micro-ondas: 10 a 12 min em potência alta, virando na metade"],
    ],
  },
  {
    id: "sopa-creme-frango",
    t: "Creme de frango com legumes",
    d: "Sopa cremosa e reconfortante, do tipo que abraça. Uma panela, 30 minutos.",
    cat: "Sopas",
    time: "35 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "2 peitos de frango",
      "1 cenoura em cubos",
      "1 batata em cubos",
      "1/2 cebola picada",
      "2 dentes de alho",
      "4 xícaras de água",
      "1 caixa de creme de leite",
      "Sal, pimenta e salsinha",
    ],
    st: [
      ["Cozinhe o frango na água com sal por 15 minutos. Retire, desfie e reserve o caldo.", 900],
      ["No mesmo caldo, cozinhe a cenoura e a batata por 10 minutos.", 600],
      "Bata metade dos legumes cozidos com um pouco do caldo no liquidificador e volte à panela — é isso que dá cremosidade.",
      "Junte o frango desfiado, a cebola e o alho refogados.",
      ["Adicione o creme de leite e aqueça 3 minutos sem ferver.", 180],
      "Ajuste o sal, salpique salsinha e sirva com torradas.",
    ],
    tips: [
      "Bater parte dos legumes no liquidificador espessa a sopa sem farinha nem amido.",
      "Guarde o caldo do cozimento: ele é a base de sabor.",
      "Creme de leite sempre por último e sem fervura forte.",
    ],
    subs: [
      ["Creme de leite", "Leite + 1 colher de amido de milho dissolvido"],
      ["Frango", "Omita e use mais legumes para versão vegetariana"],
      ["Cenoura e batata", "Mandioquinha, abóbora ou chuchu"],
    ],
  },
  {
    id: "pizza-frigideira",
    t: "Pizza de frigideira",
    d: "Pizza caseira sem forno e sem sova. Da massa ao prato em 20 minutos.",
    cat: "Lanches",
    time: "20 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: [
      "1 xícara de farinha de trigo",
      "1 colher (chá) de fermento em pó",
      "1/2 colher (chá) de sal",
      "1/2 xícara de água",
      "1 colher (sopa) de azeite",
      "1/2 xícara de molho de tomate",
      "150g de muçarela ralada",
      "Orégano e coberturas a gosto",
    ],
    st: [
      "Misture farinha, fermento e sal. Junte água e azeite e mexa até formar uma massa macia.",
      "Abra a massa com um rolo (ou garrafa) do tamanho da sua frigideira.",
      ["Coloque na frigideira seca em fogo médio e cozinhe 3 minutos, até dourar por baixo.", 180],
      "Vire a massa, espalhe o molho sobre o lado dourado, cubra com queijo e orégano.",
      ["Tampe e cozinhe em fogo baixo por 5 a 6 minutos, até o queijo derreter.", 330, "Tampa é essencial: é o calor preso que derrete o queijo."],
      "Sirva na hora.",
    ],
    tips: [
      "Fogo baixo depois de virar: fogo alto queima a base antes de derreter o queijo.",
      "Não exagere no molho — molho demais amolece a massa.",
      "A massa não precisa descansar nem crescer: o fermento em pó age no calor.",
    ],
    subs: [
      ["Muçarela", "Qualquer queijo que derreta: prato, minas padrão"],
      ["Molho de tomate", "Requeijão como base (pizza branca)"],
      ["Farinha de trigo", "Metade farinha integral funciona bem"],
    ],
  },
  {
    id: "salsicha-molho",
    t: "Salsicha ao molho com purê",
    d: "O clássico de dia de preguiça: salsicha no molho de tomate sobre purê cremoso.",
    cat: "Lanches",
    time: "25 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: [
      "6 salsichas de hot dog",
      "1/2 cebola picada",
      "1 dente de alho",
      "1 lata de molho de tomate",
      "1/2 xícara de água",
      "Sal, açúcar e orégano",
      "Purê de batata para acompanhar",
    ],
    st: [
      ["Corte as salsichas em 3 partes e doure em uma panela com um fio de óleo, 4 minutos.", 240],
      "Junte a cebola e o alho e refogue até murchar.",
      "Adicione o molho de tomate, a água, uma pitada de açúcar, sal e orégano.",
      ["Cozinhe em fogo baixo por 10 minutos, até o molho encorpar.", 600],
      "Sirva sobre purê de batata, arroz ou dentro de pão de cachorro-quente.",
    ],
    tips: [
      "Dourar a salsicha antes muda tudo: sabor defumado em vez de salsicha cozida.",
      "Pitada de açúcar corta a acidez do molho de tomate.",
      "Molho muito grosso? Um gole de água. Ralo demais? Mais 3 minutos de fogo.",
    ],
    subs: [
      ["Salsicha", "Linguiça calabresa ou tofu defumado em cubos"],
      ["Molho de tomate", "2 tomates maduros + extrato de tomate"],
      ["Purê", "Arroz branco ou pão francês"],
    ],
  },
  {
    id: "macarrao-salsicha-molho",
    t: "Macarrão com salsicha e molho",
    d: "O primeiro prato de muita gente que mora sozinho. Gostoso e impossível de errar.",
    cat: "Massas",
    time: "25 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: [
      "250g de macarrão (espaguete ou penne)",
      "4 salsichas em rodelas",
      "1/2 cebola picada",
      "1 dente de alho",
      "1 lata de molho de tomate",
      "Sal, orégano e queijo ralado",
    ],
    st: [
      ["Cozinhe o macarrão em água com sal pelo tempo da embalagem.", 480],
      ["Enquanto isso, doure as rodelas de salsicha em uma panela com fio de óleo, 4 minutos.", 240],
      "Junte cebola e alho e refogue até murchar.",
      ["Adicione o molho de tomate, tempere com sal e orégano e cozinhe 8 minutos.", 480],
      "Escorra a massa e misture ao molho. Sirva com queijo ralado.",
    ],
    tips: [
      "Comece o molho enquanto a massa cozinha — tudo fica pronto junto.",
      "Guarde um pouco da água do cozimento para acertar a consistência do molho.",
      "Uma pitada de pimenta calabresa levanta o prato inteiro.",
    ],
    subs: [
      ["Salsicha", "Calabresa, atum ou frango desfiado"],
      ["Molho de tomate", "Tomate pelado amassado com garfo"],
      ["Queijo ralado", "Parmesão, queijo minas curado ou omita"],
    ],
  },
  {
    id: "carne-panela-legumes",
    t: "Ensopado de carne com legumes",
    d: "Panela única, fogo baixo e paciência: carne desmanchando com cenoura e batata.",
    cat: "Carnes",
    time: "1h20",
    serv: "5 porções",
    diff: "Médio",
    ing: [
      "800g de acém ou músculo em cubos",
      "2 cenouras em rodelas grossas",
      "2 batatas em cubos grandes",
      "1 cebola picada",
      "3 dentes de alho",
      "2 tomates picados",
      "2 xícaras de água quente",
      "Sal, pimenta e louro",
      "2 colheres (sopa) de óleo",
    ],
    st: [
      ["Doure os cubos de carne no óleo quente, em duas levas, 5 minutos cada.", 600, "Fond dourado no fundo da panela = sabor. Não raspe ainda."],
      "Refogue a cebola e o alho, depois junte os tomates e cozinhe até desmanchar.",
      "Volte a carne, cubra com a água quente, adicione louro e pimenta.",
      ["Cozinhe em fogo baixo, tampado, por 45 minutos, mexendo de vez em quando.", 2700],
      ["Junte cenoura e batata, ajuste o sal e cozinhe mais 20 minutos, até tudo ficar macio.", 1200],
      "Prove, ajuste o tempero e sirva com arroz.",
    ],
    tips: [
      "Acém e músculo são cortes para cozimento longo: ficam macios; corte magro resseca.",
      "Não tenha pressa: carne dura depois de 45 minutos só precisa de mais tempo, não de mais fogo.",
      "Engrosse o molho amassando uma batata cozida contra a parede da panela.",
    ],
    subs: [
      ["Acém/músculo", "Paleta ou costela bovina"],
      ["Panela comum", "Pressão: 25 min de carne + 5 min com os legumes"],
      ["Cenoura e batata", "Mandioca, abóbora ou chuchu"],
    ],
  },
  {
    id: "frango-crosta-queijo",
    t: "Frango com crosta de queijo",
    d: "Filé com casquinha dourada de parmesão feita na frigideira. Sem farinha, sem fritura.",
    cat: "Aves",
    time: "20 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: [
      "2 filés de peito de frango",
      "1/2 xícara de parmesão ralado",
      "1 ovo batido",
      "Sal, pimenta e alho em pó",
      "1 colher (sopa) de azeite",
    ],
    st: [
      "Tempere os filés com sal, pimenta e alho em pó.",
      "Passe cada filé no ovo batido e depois no parmesão, pressionando para grudar.",
      ["Aqueça o azeite em fogo médio e doure os filés, 4 minutos de cada lado.", 480, "Vire com cuidado e uma vez só: a crosta solta se mexer demais."],
      ["Tampe a frigideira por 3 minutos para garantir que o centro cozinhe.", 180],
      "Sirva com salada ou legumes.",
    ],
    tips: [
      "O queijo forma a casquinha — não precisa de farinha de rosca.",
      "Fogo médio: queijo em fogo alto queima antes do frango cozinhar.",
      "Filé grosso? Cubra e cozinhe mais 3 minutos em fogo baixo.",
    ],
    subs: [
      ["Parmesão", "Qualquer queijo firme ralado"],
      ["Frango", "Filé de peixe firme (3 min por lado)"],
      ["Frigideira", "Air fryer: 200°C por 12 minutos"],
    ],
  },
  {
    id: "abobrinha-recheada",
    t: "Abobrinha recheada com carne",
    d: "Barquinhas de abobrinha com carne moída e queijo gratinado. Leve e bonito.",
    cat: "Legumes",
    time: "45 min",
    serv: "3 porções",
    diff: "Médio",
    ing: [
      "3 abobrinhas médias",
      "300g de carne moída",
      "1/2 cebola picada",
      "2 dentes de alho",
      "1 tomate picado",
      "1/2 xícara de molho de tomate",
      "1/2 xícara de queijo ralado",
      "Sal, pimenta e azeite",
    ],
    st: [
      "Corte as abobrinhas ao meio no sentido do comprimento e cave a polpa com uma colher, formando barquinhas.",
      "Pique a polpa retirada e reserve.",
      ["Refogue a carne moída até dourar, junte cebola, alho, tomate e a polpa picada. Cozinhe 8 minutos.", 480],
      "Junte o molho de tomate, ajuste o sal e a pimenta.",
      "Recheie as barquinhas com a carne e cubra com queijo.",
      ["Asse a 200°C por 20 a 25 minutos, até a abobrinha ficar macia e o queijo dourar.", 1380],
    ],
    tips: [
      "Deixe uma borda de 1 cm ao cavar: abobrinha cavada demais desmonta.",
      "Garfo entra fácil na casca? Está pronta.",
      "Regue a assadeira com um fio de azeite para a base não grudar.",
    ],
    subs: [
      ["Carne moída", "Frango moído, atum ou proteína de soja"],
      ["Abobrinha", "Berinjela ou chuchu (mesmo método)"],
      ["Queijo ralado", "Requeijão em colheradas por cima"],
    ],
  },
  {
    id: "wrap-frango",
    t: "Wrap de frango cremoso",
    d: "Jantar de semana rápido: frango cremoso enrolado em tortilha com salada.",
    cat: "Lanches",
    time: "20 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: [
      "2 tortilhas de trigo (rap10 ou pão sírio)",
      "300g de peito de frango em tiras",
      "3 colheres (sopa) de cream cheese ou requeijão",
      "Folhas de alface",
      "1 tomate em fatias",
      "Sal, páprica e azeite",
    ],
    st: [
      ["Tempere o frango com sal e páprica e doure no azeite em fogo alto, 6 minutos.", 360],
      ["Abaixe o fogo, junte o cream cheese e misture até virar um creme.", 120],
      "Aqueça as tortilhas 30 segundos de cada lado em uma frigideira seca.",
      "Monte: tortilha, alface, tomate e o frango cremoso.",
      "Enrole firme, corte ao meio e sirva.",
    ],
    tips: [
      "Tortilha aquecida enrola sem rachar — tortilha fria quebra.",
      "Não encha demais: wrap estourado é sempre excesso de recheio.",
      "Dá para levar enrolado em papel-alumínio para o trabalho.",
    ],
    subs: [
      ["Tortilha", "Pão sírio ou folhas de alface para versão sem carboidrato"],
      ["Cream cheese", "Maionese temperada ou iogurte natural"],
      ["Frango", "Atum, ovo mexido ou carne moída"],
    ],
  },
  {
    id: "risoto-frango-simples",
    t: "Risoto simples de frango",
    d: "Versão sem cerimônia do risoto: arroz cremoso com frango, sem vinho e sem frescura.",
    cat: "Arroz e feijão",
    time: "40 min",
    serv: "4 porções",
    diff: "Médio",
    ing: [
      "1 e 1/2 xícara de arroz arbóreo (ou branco comum)",
      "300g de peito de frango em cubos",
      "1 cebola picada",
      "2 dentes de alho",
      "5 xícaras de água quente com 1 cubo de caldo de galinha",
      "1/2 xícara de parmesão ralado",
      "1 colher (sopa) de manteiga",
      "Sal e azeite",
    ],
    st: [
      ["Doure os cubos de frango no azeite e reserve.", 300],
      "Na mesma panela, refogue a cebola e o alho até murchar.",
      ["Junte o arroz e frite 2 minutos, mexendo.", 120],
      ["Adicione o caldo quente concha a concha, mexendo sempre, só adicionando a próxima quando a anterior secar. Repita por 18 a 20 minutos.", 1140, "Mexer sempre é o que solta o amido e dá cremosidade — é o único trabalho de verdade."],
      ["Volte o frango à panela, junte manteiga e parmesão e misture 2 minutos.", 120],
      "Prove o sal, tampe e deixe descansar 2 minutos antes de servir.",
    ],
    tips: [
      "Caldo quente, nunca frio: líquido frio interrompe o cozimento a cada concha.",
      "Ponto do risoto: arroz al dente (com leve resistência no centro) e molho cremoso, não seco.",
      "Arroz branco comum funciona — fica menos cremoso, mas gostoso.",
    ],
    subs: [
      ["Arroz arbóreo", "Arroz branco comum (a cremosidade vem de mexer mais)"],
      ["Caldo de galinha", "Água quente com sal e um pouco de manteiga"],
      ["Frango", "Cogumelos, legumes ou linguiça"],
    ],
  },
  {
    id: "peixe-papelote",
    t: "Peixe no papillote com legumes",
    d: "Peixe cozido dentro de um pacote de papel-alumínio com legumes. Zero louça, zero erro.",
    cat: "Peixes",
    time: "30 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: [
      "2 filés de peixe branco (tilápia, pescada)",
      "1 cenoura em palitos finos",
      "1 abobrinha em meias-luas",
      "1/2 cebola fatiada",
      "Suco de 1 limão",
      "2 colheres (sopa) de azeite",
      "Sal, pimenta e salsinha",
    ],
    st: [
      "Preaqueça o forno a 200°C.",
      "Corte dois quadrados grandes de papel-alumínio (40 cm).",
      "No centro de cada um, faça uma cama de legumes, coloque o filé por cima e tempere com sal, pimenta, limão e azeite.",
      "Feche o pacote dobrando as bordas com firmeza, sem deixar abertura.",
      ["Asse por 18 a 20 minutos.", 1140, "O pacote vai inchar com o vapor — é o vapor que cozinha tudo."],
      "Abra com cuidado (vapor quente!) e sirva no próprio pacote.",
    ],
    tips: [
      "Legumes cortados finos cozinham no mesmo tempo do peixe — corte grosso fica cru.",
      "Pacote bem fechado é o segredo: vapor escapando = peixe seco.",
      "Não tem papel-alumínio? Papel-manteiga também funciona.",
    ],
    subs: [
      ["Peixe branco", "Salmão (mesmo tempo) ou filé de frango fino (+5 min)"],
      ["Cenoura e abobrinha", "Tomate, vagem ou batata em fatias bem finas"],
      ["Limão", "Vinho branco ou só azeite e sal"],
    ],
  },
  {
    id: "bolonhesa-lentilha",
    t: "Molho à bolonhesa de lentilha",
    d: "Bolonhesa sem carne que engana até carnívoro. Barata, rica em ferro e congela bem.",
    cat: "Massas",
    time: "45 min",
    serv: "4 porções",
    diff: "Fácil",
    ing: [
      "1 e 1/2 xícara de lentilha",
      "1 cebola picada",
      "2 dentes de alho",
      "1 cenoura ralada",
      "2 tomates maduros picados",
      "1 lata de molho de tomate",
      "Sal, pimenta, orégano e azeite",
      "Massa de sua preferência",
    ],
    st: [
      ["Cozinhe a lentilha em água por 20 minutos, até ficar macia mas firme. Escorra.", 1200],
      "Refogue cebola, alho e cenoura no azeite até murchar.",
      "Junte os tomates e cozinhe até desmanchar.",
      ["Adicione a lentilha e o molho de tomate e cozinhe 15 minutos em fogo baixo.", 900],
      "Tempere com sal, pimenta e orégano. Amasse algumas lentilhas contra a panela para encorpar.",
      "Sirva sobre a massa cozida com parmesão.",
    ],
    tips: [
      "Lentilha não precisa deixar de molho — é a leguminosa mais prática que existe.",
      "A cenoura ralada some no molho e dá doçura natural.",
      "Faça o dobro e congele metade: molho congelado salva jantares por semanas.",
    ],
    subs: [
      ["Lentilha", "Grão-de-bico cozido amassado ou proteína de soja"],
      ["Molho de tomate", "Tomates frescos maduros em dobro"],
      ["Massa", "Sirva sobre arroz ou purê de batata"],
    ],
  },
  {
    id: "nhoque-manteiga-salva",
    t: "Nhoque de batata na manteiga",
    d: "Nhoque caseiro com 3 ingredientes. O teste do primeiro bolinho garante o ponto da massa.",
    cat: "Massas",
    time: "1h",
    serv: "4 porções",
    diff: "Médio",
    ing: [
      "1kg de batata",
      "1 ovo",
      "1 e 1/2 a 2 xícaras de farinha de trigo",
      "Sal",
      "3 colheres (sopa) de manteiga",
      "Folhas de sálvia ou manjericão (opcional)",
      "Parmesão para servir",
    ],
    st: [
      ["Cozinhe as batatas com casca em água até espetar fácil com garfo, uns 25 minutos.", 1500],
      "Descasque ainda quentes e amasse até virar um purê bem liso (sem caroços!).",
      "Deixe amornar, junte o ovo, uma pitada de sal e a farinha aos poucos, até a massa desgrudar das mãos.",
      ["Teste: cozinhe 1 bolinho em água fervente. Se desmanchar, a massa precisa de mais farinha.", 120, "Esse teste salva a receita inteira — nunca pule."],
      "Enrole a massa em cilindros, corte em pedaços de 2 cm e marque com um garfo.",
      ["Cozinhe em água fervente com sal: quando os nhoques subirem à superfície, estão prontos.", 180],
      ["Derreta a manteiga com as ervas e envolva os nhoques. Sirva com parmesão.", 120],
    ],
    tips: [
      "Batata cozida com casca absorve menos água — massa mais firme com menos farinha.",
      "Farinha demais deixa o nhoque duro: adicione só até desgrudar.",
      "Nhoque que sobe está pronto; nhoque que demora demais na água desmancha.",
    ],
    subs: [
      ["Batata inglesa", "Batata doce ou abóbora cabotiá (mais seca)"],
      ["Manteiga e sálvia", "Molho de tomate ou molho branco"],
      ["Ovo", "Omita e use mais farinha (nhoque vegano)"],
    ],
  },
  {
    id: "frango-xadrez-simples",
    t: "Frango com legumes estilo oriental",
    d: "Refogado rápido com molho de shoyu. Mais rápido que pedir delivery.",
    cat: "Aves",
    time: "25 min",
    serv: "3 porções",
    diff: "Fácil",
    ing: [
      "500g de peito de frango em cubos",
      "1 cenoura em palitos",
      "1/2 pimentão em tiras",
      "1 cebola em pétalas",
      "3 colheres (sopa) de shoyu",
      "1 colher (sopa) de amido de milho",
      "1/2 xícara de água",
      "2 colheres (sopa) de óleo",
      "Gergelim e cebolinha (opcional)",
    ],
    st: [
      ["Doure o frango no óleo quente em fogo alto, 5 minutos. Reserve.", 300],
      ["Na mesma frigideira, refogue a cenoura 3 minutos, junte pimentão e cebola e refogue mais 2 minutos.", 300, "Legumes devem ficar al dente — crocantes, não moles."],
      "Misture shoyu, amido e água em uma tigela.",
      ["Volte o frango à frigideira, despeje o molho e mexa por 2 minutos, até engrossar e ficar brilhante.", 120],
      "Salpique gergelim e cebolinha e sirva com arroz branco.",
    ],
    tips: [
      "Fogo alto e legumes na sequência certa: o mais duro (cenoura) entra primeiro.",
      "O molho engrossa rápido com amido — mexa sem parar nesses 2 minutos.",
      "Deixe tudo cortado antes de acender o fogo: refogado rápido não espera.",
    ],
    subs: [
      ["Shoyu", "Molho inglês + pitada de açúcar"],
      ["Amido de milho", "Farinha de trigo dissolvida em água fria"],
      ["Frango", "Carne em tiras ou tofu firme"],
    ],
  },
  {
    id: "salada-completa-atum",
    t: "Salada completa com atum",
    d: "Salada que é jantar: proteína, grãos e vegetais numa tigela só.",
    cat: "Saladas",
    time: "15 min",
    serv: "2 porções",
    diff: "Fácil",
    ing: [
      "1 lata de atum escorrido",
      "1 xícara de grão-de-bico cozido (ou milho)",
      "Alface rasgada",
      "1 tomate em cubos",
      "1/2 pepino em rodelas",
      "1/4 de cebola roxa fatiada",
      "2 ovos cozidos em quartos",
      "Azeite, limão, sal e orégano",
    ],
    st: [
      "Monte a base de alface em uma tigela grande.",
      "Distribua por cima o grão-de-bico, o tomate, o pepino e a cebola.",
      "Adicione o atum e os ovos cozidos.",
      ["Tempere com azeite, limão, sal e orégano. Misture na hora de servir.", 60],
    ],
    tips: [
      "Tempere só na hora de servir: salada temperada antes murcha.",
      "Ovo cozido de 8 minutos (gema cremosa) é o ponto ideal para salada.",
      "Troque o que quiser: a fórmula é folha + proteína + grão + vegetal crocante.",
    ],
    subs: [
      ["Atum", "Frango desfiado, ovo cozido extra ou queijo em cubos"],
      ["Grão-de-bico", "Milho, feijão branco ou croutons"],
      ["Cebola roxa crua", "Cebola comum de molho em água 10 min (perde o ardor)"],
    ],
  },
]);
