/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as GeladeiraRouteImport } from './routes/geladeira'
import { Route as GuiasRouteImport } from './routes/guias'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanejarRouteImport } from './routes/planejar'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as ReceitasIndexRouteImport } from './routes/receitas.index'
import { Route as ReceitasIdRouteImport } from './routes/receitas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const GeladeiraRoute = GeladeiraRouteImport.update({
  id: '/geladeira',
  path: '/geladeira',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasRoute = GuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejarRoute = PlanejarRouteImport.update({
  id: '/planejar',
  path: '/planejar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasIndexRoute = ReceitasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceitasRoute,
} as any)
const ReceitasIdRoute = ReceitasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReceitasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/geladeira': typeof GeladeiraRoute
  '/guias': typeof GuiasRoute
  '/perfil': typeof PerfilRoute
  '/planejar': typeof PlanejarRoute
  '/receitas': typeof ReceitasRouteWithChildren
  '/receitas/$id': typeof ReceitasIdRoute
  '/receitas/': typeof ReceitasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/geladeira': typeof GeladeiraRoute
  '/guias': typeof GuiasRoute
  '/perfil': typeof PerfilRoute
  '/planejar': typeof PlanejarRoute
  '/receitas/$id': typeof ReceitasIdRoute
  '/receitas': typeof ReceitasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/geladeira': typeof GeladeiraRoute
  '/guias': typeof GuiasRoute
  '/perfil': typeof PerfilRoute
  '/planejar': typeof PlanejarRoute
  '/receitas': typeof ReceitasRouteWithChildren
  '/receitas/$id': typeof ReceitasIdRoute
  '/receitas/': typeof ReceitasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favoritos'
    | '/geladeira'
    | '/guias'
    | '/perfil'
    | '/planejar'
    | '/receitas'
    | '/receitas/$id'
    | '/receitas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favoritos'
    | '/geladeira'
    | '/guias'
    | '/perfil'
    | '/planejar'
    | '/receitas/$id'
    | '/receitas'
  id:
    | '__root__'
    | '/'
    | '/favoritos'
    | '/geladeira'
    | '/guias'
    | '/perfil'
    | '/planejar'
    | '/receitas'
    | '/receitas/$id'
    | '/receitas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritosRoute: typeof FavoritosRoute
  GeladeiraRoute: typeof GeladeiraRoute
  GuiasRoute: typeof GuiasRoute
  PerfilRoute: typeof PerfilRoute
  PlanejarRoute: typeof PlanejarRoute
  ReceitasRoute: typeof ReceitasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geladeira': {
      id: '/geladeira'
      path: '/geladeira'
      fullPath: '/geladeira'
      preLoaderRoute: typeof GeladeiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias': {
      id: '/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof GuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejar': {
      id: '/planejar'
      path: '/planejar'
      fullPath: '/planejar'
      preLoaderRoute: typeof PlanejarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas/': {
      id: '/receitas/'
      path: '/'
      fullPath: '/receitas/'
      preLoaderRoute: typeof ReceitasIndexRouteImport
      parentRoute: typeof ReceitasRoute
    }
    '/receitas/$id': {
      id: '/receitas/$id'
      path: '/$id'
      fullPath: '/receitas/$id'
      preLoaderRoute: typeof ReceitasIdRouteImport
      parentRoute: typeof ReceitasRoute
    }
  }
}

interface ReceitasRouteChildren {
  ReceitasIdRoute: typeof ReceitasIdRoute
  ReceitasIndexRoute: typeof ReceitasIndexRoute
}

const ReceitasRouteChildren: ReceitasRouteChildren = {
  ReceitasIdRoute: ReceitasIdRoute,
  ReceitasIndexRoute: ReceitasIndexRoute,
}

const ReceitasRouteWithChildren = ReceitasRoute._addFileChildren(
  ReceitasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritosRoute: FavoritosRoute,
  GeladeiraRoute: GeladeiraRoute,
  GuiasRoute: GuiasRoute,
  PerfilRoute: PerfilRoute,
  PlanejarRoute: PlanejarRoute,
  ReceitasRoute: ReceitasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
